
/** 路線ID */
export const LINE_IDS = {
  /** JR東日本 */
  jr_east: {
    /** 京浜東北線 */
    keihin_touhoku: 'jr-keihintouhoku',
    /** 宇都宮線 */
    utunomiya: 'jr-utunomiya',
    /** 高崎線 */
    takasaki: 'jr-takasaki',
    /** 湘南新宿ライン */
    shonan_shinjuku: 'jr-sho-nan_shinjuku',
    // "埼京線",
    saikyou: 'jr-saikyou',
    // "川越線",
    kawagoe: 'jr-kawagoe',
    /** 山手線 */
    yamanote: 'jr-yamanote',
    /** 常盤線 */
    tokiwa: 'jr-tokiwa',
    /** 中央線 */
    chuo: 'jr-chuo',
    /** 東海道本線 */
    tokaido: 'jr-tokaido',
    /** 横浜線 */
    yokohama: 'jr-yokohama',
    /** 根岸線 */
    negishi: 'jr-negishi',
    /**横須賀線 */
    yokosuka: 'jr-yokosuka',
    /** 南武線 */
    nanbu: 'jr-nanbu',
    /** 武蔵野線 */
    musashino: 'jr-musashino',

    shinkansen: {
      // 東海道新幹線
      tokaido: 'jr-tokaido-shinkansen',
      // 東北新幹線
      tohoku: 'jr-tohoku-shinkansen',
      // 新幹線はやぶさ
      hayabusa: 'jr-hayabusa',
      // 山形新幹線
      yamagata: 'jr-yamagata-shinkansen',
      // 秋田新幹線
      akita: 'jr-akita-shinkansen',
      // 上越新幹線
      jouetsu: 'jr-shouetsu-shinkansen',
      // 北陸新幹線
      hokuriku: 'jr-hokuriku-shinkansen',
    },
  },
  // 京急
  keikyu: {
    honsen: "keikyu-honsen",
    haneda_kuko: "keikyu-haneda-kuko",
  },
  toubu: {
    // "東武アーバンパークライン",
    urban_park_line: 'toubu-urban-park-line',
  },
  saitama_shintoshi: {
    // ニューシャトル
    new_shuttle: 'saitama_shintoshi_new_shuttle',
  },
  /** 東京メトロ */
  tokyo_metro: {
    /** 丸の内線 */
    marunouchi: 'tokyo-metro-marunouchi',
    /** 日比谷線 */
    hibiya: 'tokyo-metro-hibiya',
    /** 銀座線 */
    ginza: 'tokyo-metro-ginza',
    /** 半蔵門線 */
    hanzoumon: 'tokyo-metro-hanzoumon',
    /** 副都心線 */
    hukutoshin: 'tokyo-metro-hukutoshin',
  },
  /** 東京都交通局 */
  tokyo_koutsu_kyoku: {
    /** 大江戸線 */
    oedo: 'toeiooedo',
    /** 新宿線 */
    shinjuku: 'toeishinjuku',
  },
  /** 東京都営地下鉄 */
  tokyo_subway: {
    asakusa: 'toei-asakusa',
  },
  /** 相模鉄道 */
  sagami: {
    honsen: 'sagami-honsen',
    izumino: 'sagami-izumino',
  },
  odakyu: {
    odawara: 'odakyu-odawara',
    enoshima: 'odakyu-enoshima',
  },
  // 江ノ島電鉄
  enoshima: {
    enoshima: 'enoshima-enoshimadentetsu',
  },
  // 湘南モノレール
  shonam_monorail: {
    shonan_monorail: 'shonan-monorail',
  },
  /** 京王電鉄 */
  keiou: {
    keiou: 'keiou-keiou',
    keioushinsen: 'keiou-keioushinsen',
    /** 井の頭線 */
    inogashira: 'keiou-inogashira',
  },
  /** 東急電鉄 */
  tokyu: {
    denentoshi: 'tokyu-denentoshi',
    toyoko: 'tokyu-toyoko',
    tamagawa: 'tokyu-tamagawa',
    meguro: 'tokyu-meguro',
    ikegami: "tokyu-ikegami",
    kodomonokuni: "keikyu-kodomonokuni",
    oimachi: "tokyu-oimachi",
    setagaya: "tokyu-setagaya",
  },
  /** 横浜市営地下鉄 */
  yokohama_shieichikatetsu: {
    blue_line: 'yokohama-shieichikatetsu-blue-line',
    green_line: 'yokohama-shieichikatetsu-green-line',
  },
  /** 東京臨海高速鉄道*/
  toukyo_rinkai_kousoku: {
    /** りんかい線 */
    rinkai: 'toukyo-rinkai-kousoku-rinkai',
  }
}

/** 駅ID */
export const STATION_IDS = {
  /** JR東日本 */
  jr_east: {
    omiya: 'o-miya',
    saitama_shintoshin: 'saitama-shintoshin',
    yono: 'yono',
    kitaurawa: 'kitaurawa',
    urawa: 'urawa',
    minami_urawa: 'minami-urawa',
    warabi: 'warabi',
    nishikawaguchi: 'nishikawaguchi',
    kawaguti: 'kawaguchi',
    akahane: 'akahane',
    higashijujo: 'higashi-jujo',
    ouji: 'ouji',
    kaminakazato: 'kaminakazato',
    tabata: 'tabata',
    nishinippori: 'nishinippori',
    nippori: 'nippori',
    uguisudani: 'uguisudani',
    ueno: 'ueno',
    okachimachi: 'okachimachi',
    akihabara: 'akihabara',
    kanda: 'kanda',
    tokyo: 'tokyo',
    yurakucho: 'yurakucho',
    shinjuku: 'shinjuku',
    hamamatsucho: 'hamamatsucho',
    tamachi: 'tamachi',
    takanawa_gateway: 'takanawa-gateway',
    shinagawa: 'shinagawa',
    oimachi: 'oimachi',
    omori: 'omori',
    kamata: 'kamata',
    kawasaki: 'kawasaki',
    tsurumi: 'tsurumi',
    shinkoyasu: 'shinkoyasu',
    higashikanagawa: 'higashi-kanagawa',
    yokohama: 'yokohama',
    shinbashi: 'shinbashi',
    komagome: 'komagome',
    sugamo: 'sugamo',
    otsuka: 'otsuka',
    ikebukuro: 'ikebukuro',
    mejiro: 'mejiro',
    takadanobaba: 'takadanobaba',
    shinokubo: 'shinokubo',
    yoyogi: 'yoyogi',
    harajuku: 'harajuku',
    shibuya: 'shibuya',
    ebisu: 'ebisu',
    meguro: 'meguro',
    gotanda: 'gotanda',
    osaki: 'osaki',
    hachiouji: 'hachiouji',
    katakura: 'katakura',
    hachiouji_minamino: 'hachiouji-minamino',
    aihara: 'aihara',
    hashimoto: 'hashimoto',
    sagamihara: 'sagamihara',
    huchinobe: 'huchinobe',
    kobuchi: 'kobuchi',
    machida: 'machida',
    naruse: 'naruse',
    nagatsuta: 'nagatsuta',
    tokaichiba: 'tokaichiba',
    nakayama: 'nakayama',
    kamoi: 'kamoi',
    kodukue: 'kodukue',
    shinyokohama: 'shinyokohama',
    kikuna: 'kikuna',
    oguchi: 'oguchi',
    higashi_kanagawa: 'higashi-kanagawa',
    sakuragicho: 'sakuragicho',
    kannai: 'kannai',
    ishikawacho: 'ishikawacho',
    yamate: 'yamate',
    negishi: 'negishi',
    isogo: 'isogo',
    shin_sugita: 'shin-sugita',
    youkoudai: 'youkoudai',
    kounandai: 'kounandai',
    hongoudai: 'hongoudai',
    ofuna: 'ofuna',
    totsuka: 'totsuka',
    hujisawa: 'hujisawa',
    tsujido: 'tsujido',
    chigasaki: 'chigasaki',
    hiratsuka: 'hiratsuka',
    oiso: 'oiso',
    ninomiya: 'ninomiya',
    kozu: 'kozu',
    kamonomiya: 'kamonomiya',
    odawara: 'odawara',
    hayakawa: "hayakawa",
    nebukawa: "nebukawa",
    manazuru: "manazuru",
    yugawara: 'yugawara',
    atami: 'atami',
    // 中央線
    ochanomizu: 'ochanomizu',
    yotsuya: 'yotsuya',
    nakano: 'nakano',
    kouenji: 'kouenji',
    asagaya: 'asagaya',
    ogikubo: 'ogikubo',
    nisiogikubo: 'nishiogikubo',
    kisshouji: 'kisshouji',
    mitaka: 'mitaka',
    musashisakai: 'musashisakai',
    higashikoganei: 'higashikoganei',
    musashikoganei: 'musashikoganei',
    kokubunji: 'kokubunji',
    nishikokubunji: 'nishikokubunji',
    kunitachi: 'kunitachi',
    tachikawa: 'tachikawa',
    hino: 'hino',
    toyoda: 'toyoda',
    nishihachiouji: "nishihachiouji",
    takao: 'takao',
    // 高崎線
    oku: 'oku',
    miyahara: 'miyahara',
    ageo: 'ageo',
    kitaageo: 'kitaageo',
    okegawa: 'okegawa',
    kitamoto: 'kitamoto',
    kousu: 'kousu',
    kitakousu: 'kitakousu',
    hukiage: 'hukiage',
    gyouda: 'gyouda',
    kumagaya : 'kumagaya',
    kagohara : 'kagohara',
    hukaya : 'hukaya',
    okabe : 'okabe',
    honnjou: 'honnjou',
    jinbohara: 'jinbohara',
    /** 新町(群馬) */
    shinmachi: 'sinmachi',
    kuragano: 'kuragano',
    takasaki: 'takasaki',
    // 湘南新宿ライン
    utsunomiya: 'utsunomiya',
    suzunomiya: 'suzunomiya',
    isibashi: 'isibashi',
    jichiidai: 'jichiidai',
    koganei: 'koganei',
    koyama: 'koyama',
    mamada: 'mamada',
    nogi: 'nogi',
    hurukawa: 'hurukawa',
    kurihshi: 'kurihshi',
    higashiwashinomiya: 'higashiwashinomiya',
    kuki: 'kuki',
    shinshiraoka: 'shinshiraoka',
    shiraoka: 'shiraoka',
    hasuda: 'hasuda',
    higashiomiya: 'higashiomiya',
    toro: 'toro',
    maehashi: 'maehashi',
    shinmaebashi: 'shinmaebashi',
    /** 井野(群馬) */
    ino: 'ino',
    takasakitonyamachi: 'takasaki-tonyamachi',
    nishioi: "nishioi",
    musashikosugi: "musashikosugi",
    shinkawasaki: "shinkawasaki",
    hodogaya: "hodogaya",
    higashitotsuka: "higashitotsuka",
    kitakamakura: "kitakamakura",
    kamakura: "kamakura",
    zushi: "zushi",
    // 宇都宮線
    doro: 'doro',
    /** 岡本(栃木) */
    okamoto: 'okamoto',
    housekiji: 'housekiji',
    ujiie: 'ujiie',
    kamasusaka: 'kamasusaka',
    kataoka: 'kataoka',
    yaita: 'yaita',
    /**野崎(栃木) */
    nozaki: 'nozaki',
    nishisunano: 'nishisunano',
    nasusiohara: 'nasusiohara',
    kuroiso: 'kuroiso',
    //武蔵野線
    huchuhonmachi: 'huchuhonmachi',
    kitahuchu: 'kitahuchu',
    shinkohira: 'shinkohira',
    shinakitsu: 'shinakitsu',
    higashitokorozawa: "higashitokorozawa",
    shinza: "shinza",
    kitaasaka: "kitaasaka",
    musashiurawa: "musashiurawa",
    minamiurawa: "minamiurawa",
    higashiurawa: "higashiurawa",
    higashikawaguchi: "higashikawaguchi",
    minamikoshigaya: "minamikoshigaya",
    koshigaya_laketown: "koshigaya-laketown",
    /** 吉川(埼玉) */
    yoshikawa: "yoshikawa",
    yoshikawaminami: "yoshikawaminami",
    shinsangou: "shinsangou",
    /** 三郷(埼玉) */
    sangou: "sangou",
    minaminagareyama: "minaminagareyama",
    shinmatsudo: "shinmatsudo",
    shinyahashira: "shinyahashira",
    higashimatsudo: "higashimatsudo",
    ichikawaono: "ichikawaono",
    hunabashihouten: "hunabashihouten",
    nishihunabashi: "nishihunabashi",
    minamihunabashi: "minamihunabashi",
    shinnarashino: "shinnarashino",
    makuharitoyosuna: "makuharitoyosuna",
    kaihinmakuhari: "kaihinmakuhari",
    ichikawashiohama: "ichikawashiohama",
    shinurayasu: "shinurayasu",
    maihama: "maihama",
    kasairinkaikouen: "kasairinkaikouen",
    shinkiba: "shinkiba",
    shiomi: "shiomi",
    ecchujima: "ecchujima",
    hacchoubori: "hacchoubori",
    //南武線
    hamakawasaki: "hamakawasaki",
    odasakae: "odasakae",
    kawasakichinmachi: "kawasakichinmachi",
    hacchounawate: "hacchounawate",
    shitte: "shitte",
    yakou: "yakou",
    kashimada: "kashimada",
    hirama: "hirama",
    mukougawara: "mukougawara",
    mizonokuchi: "mizonokuchi",
    musashinakahara: "musashinakahara",
    musashishinjou: "musashishinjou",
    musashimizonokuchi: "musashimizonokuchi",
    tsudayama: "tsudayama",
    kuji: "kuji",
    syukugawara: "syukugawara",
    noto: "noto",
    /** 中野島(神奈川) */
    nakanojima: "nakanojima",
    inadatsutsumi: "inadatsutsumi",
    yanoguchi: "yanoguchi",
    inaginaganuma: "inaginaganuma",
    minamitama: "minamitama",
    bubaigawara: "bubaigawara",
    nishifu: "nishifu",
    yaho: "yaho",
    yakawa: "yakawa",
    nishikunitachi: "nishikunitachi",
  },
  /** 相模鉄道 */
  sagami: {
    ebina: "ebina",
    kashiwadai: "kashiwadai",
    sagamino: "sagamino",
    sagamiotsuka: "sagamiotsuka",
    futamatagawa: "futamatagawa",
    tsuruma: "tsuruma",
    seya: "seya",
    mitsukyo: "mitsukyo",
    kibougaoka: "kibougaoka",
    tsurugamine: "tsurugamine",
    nishiya: "nishiya",
    kamihoshikawa: "kamihoshikawa",
    wadacho: "wadacho",
    hoshikawa: "hoshikawa",
    tennocho: "tennocho",
    nishiyokohama: "nishiyokohama",
    hiranumabashi: "hiranumabashi",
  },
  /** 小田急電鉄 */
  odakyu: {
    sagamiono: "sagamiono",
    higashirinkan: "higashirinkan",
    chuorinkan: "chuorinkan",
    minamirinkan: "minamirinkan",
    tsuruma: "tsuruma",
    yamato: "yamato",
    sakuragaoka: "sakuragaoka",
    kouzashibuya: "kouzashibuya",
    chogo: "chogo",
    shonandai: "shonandai",
    mutsuainichidaimae: "mutsuainichidaimae",
    zengyo: "zengyo",
    fujisawahonmachi: "fujisawahonmachi",
    kugenuma: "kugenuma",
    honkugenuma: "honkugenuma",
    kugenumakaigan: "kugenumakaigan",
    kataseenoshima: "kataseenoshima",
  },
  /** 東急電鉄 */
  tokyu: {
    // 田園都市線
    ikejiriohashi: "ikejiriohashi",
    sangenjaya: "sangenjaya",
    komazawadaigaku: "komazawadaigaku",
    sakurashinmachi: "sakurashinmachi",
    yoga: "yoga",
    futakotamagawa: "futakotamagawa",
    futako_shinchi: "futako-shinchi",
    takatsu: "takatsu",
    mizonokuchi: "mizonokuchi",
    kajigaya: "kajigaya",
    miyazakidai: "miyazakidai",
    miyamaedaira: "miyamaedaira",
    washinuma: "washinuma",
    tama_plaza: "tama-plaza",
    azamino: "azamino",
    eda: "eda",
    ichigao: "ichigao",
    fujigaoka: "fujigaoka",
    aobadai: "aobadai",
    tana: "tana",
    tsukushino: "tsukushino",
    suzukakedai: "suzukakedai",
    minamimachida_grandberry_park: "minamimachida-grandberry-park",
    tsukimino: "tsukimino",
    // 多摩川線
    tamagawa: "tamagawa",
    numabe: "numabe",
    unoki: "unoki",
    simomaruko: "simomaruko",
    musashishinden: "musashishinden",
    yagutiwatashi: "yagutiwatashi",
    // 大井町線
    shimoshinmei: "shimoshinmei",
    togoshikouen: "togoshikouen",
    nakanobe: "nakanobe",
    ebaracho: "ebaracho",
    hatanodai: "hatanodai",
    kitasenzoku: "kitasenzoku",
    ookayama: "ookayama",
    midorigaoka: "midorigaoka",
    jiyugaoka: "jiyugaoka",
    kuhonbutsu: "kuhonbutsu",
    oyamadai: "oyamadai",
    todoroki: "todoroki",
    kaminoge: "kaminoge",
  }
};
