
/** 路線ID */
export const LINE_IDS = {
  /** JR・相鉄直通線*/
  jr_sotetsu_chokutsu: "jr-sotetsu-chokutsu",

  /** 京急 路線 */
  keikyu: {
    /** 本線 */
    honsen: "keikyu-honsen",
    /** 羽田空港線 */
    haneda_kuko: "keikyu-haneda-kuko",
    /** 逗子線 */
    zushi: "keikyu-zushi",
    /** 久里浜線 */
    kurihama: "keikyu-kurihama",
    /** 大師線 */
    daishi: "keikyu-daishi",
    /** シーサイドライン */
    sea_side: "keikyu-sea-side",
  },
  /** 東京都営地下鉄 路線 */
  tokyo_subway: {
    /** 浅草線 */
    asakusa: 'toei-asakusa',
    /** 三田線 */
    mita: 'toei-mita',
    /** 新宿線 */
    shinjuku: 'toei-shinjuku',
    /** 大江戸線 */
    oedo: 'toei-ooedo',
    /** 日暮里・舎人ライナー */
    nippori_toneri_liner: 'toei-nippori-toneri-liner',
    /** さくらトラム */
    sakura_tram: 'toei-sakura-tram',
  },
   /** 東京メトロ 路線 */
   tokyo_metro: {
    /** 銀座線 */
    ginza: 'tokyo-metro-ginza',
    /** 丸の内線 */
    marunouchi: 'tokyo-metro-marunouchi',
    /** 日比谷線 */
    hibiya: 'tokyo-metro-hibiya',
    /** 東西線 */
    touzai: 'tokyo-metro-touzai',
    /** 千代田線 */
    chiyoda: 'tokyo-metro-chiyoda',
    /** 有楽町線 */
    yurakucho: 'tokyo-metro-yurakucho',
    /** 半蔵門線 */
    hanzoumon: 'tokyo-metro-hanzoumon',
    /** 南北線 */
    nanboku: 'tokyo-metro-nanboku',
    /** 副都心線 */
    fukutoshin: 'tokyo-metro-fukutoshin',
  },
  /** 東京モノレール */
  tokyo_monorail: {
    haneda_kuko: "tokyo-monorail",
  },
  /** 千葉都市モノレール */
  chiba_toshi_monorail: {
    ichigou: "chiba-toshi-monorail-ichigou",
    nigou: "chiba-toshi-monorail-nigou",
  },
  /** 相模鉄道 */
  sagami: {
    /** 本線 */
    honsen: 'sagami-honsen',
    /** 相鉄いずみ野線 */
    izumino: 'sagami-izumino',
    /** 相鉄新横浜線 */
    sotetsushin_yokohama: 'sagami-sotetsushin_yokohama',
  },
   /** 小田急 路線*/
   odakyu: {
    /** 小田原線 */
    odawara: 'odakyu-odawara',
    /** 江ノ島線 */
    enoshima: 'odakyu-enoshima',
    /** 多摩線 */
    tama: 'odakyu-tama',
    /** 箱根登山線 */
    hakonetozan: 'odakyu-hakonetozan',
  },


  /** JR東日本 */
  jr_east: {
    // "埼京線(JA)",
    saikyou: 'jr-saikyou',
    /** 川越線(JA) */
    kawagoe: 'jr-kawagoe',
    /** 総武線(JB) */
    sobu: 'jr-sobu',
    /** 中央線(JC) */
    chuo: 'jr-chuo',
    /** 五日市線(JC) */
    itsukaichi: 'jr-itsukaichi',
    /** 京葉線(JE) */
    keiyou: 'jr-keiyou',
    /** 相模線(JG) */
    sagami: 'jr-sagami',
    /** 横浜線(JH) */
    yokohama: 'jr-yokohama',
    /** 鶴見線(JI) */
    tsurumi: 'jr-tsurumi',
    /** 常盤線(JJ) */
    tokiwa: 'jr-tokiwa',
    /** 京浜東北線(JK) */
    keihin_touhoku: 'jr-keihintouhoku',
    /** 根岸線(JK) */
    negishi: 'jr-negishi',
    /** 南武線(JN) */
    nanbu: 'jr-nanbu',
    /** 武蔵野線(JM) */
    musashino: 'jr-musashino',
    /** 南武支線(JN) */
    nanbu_shisen: 'jr-nanbu-shisen',
    /** 横須賀線(JO) */
    yokosuka: 'jr-yokosuka',
    /** 湘南新宿ライン(JS) */
    shonan_shinjuku: 'jr-sho-nan_shinjuku',
    /** 東海道本線(JT) */
    tokaido: 'jr-tokaido',
    /** 宇都宮線(JU) */
    utunomiya: 'jr-utunomiya',
    /** 高崎線(JU) */
    takasaki: 'jr-takasaki',
    /** 山手線(JY) */
    yamanote: 'jr-yamanote',
    /** 中央本線 */
    chuo_honsen: 'jr-chuo-honsen',
    /** 総武線快速(JO) */
    sobu_kaisoku: 'jr-sobu-kaisoku',
    /** 総武本線(JO) */
    sobu_honsen: 'jr-sobu-honsen',

    /** 磐越東線 */
    banetsutou: 'jr-banetsutou',


    /** 日光線 */
    nikko: 'jr-nikko',
    /** 烏山線 */
    karasuyama: 'jr-karasuyama',
    /** 水戸線 */
    mito: 'jr-mito',
    /** 青梅線 */
    oume: 'jr-oume',
    /** 八高線 */
    hachiko: 'jr-hachiko',
    /** 鹿島線 */
    kashima: 'jr-kashima',
    /** 成田線 */
    narita: 'jr-narita',
    /** 内房線 */
    uchibou: 'jr-uchibou',
    /** 外房線 */
    sotobou: 'jr-sotobou',
    /** 上越線 */
    jouetsu: 'jr-jouetsu',
    /** 両毛線 */
    ryomo: 'jr-ryomo',
    /** 吾妻線 */
    agatsuma: 'jr-agatsuma',

    /** 信越本線 */
    shinetsu_honsen: 'jr-shinetsu-honsen',
    /** 小海線 */
    koumi: 'jr-koumi',
    /** 弥彦線 */
    yahiko: 'jr-yahiko',
    /** 磐越西線 */
    banetsusai: 'jr-banetsusai',
    /** 白新線 */
    hakushin: 'jr-hakushin',
    /** 越後線 */
    echigo: 'jr-echigo',
    /** 篠ノ井線 */
    shinonoi: 'jr-shinonoi',
    /** 飯山線 */
    iiyama: 'jr-iiyama',

    /** 東北本線 */
    touhoku_honsen: 'jr-touhoku-honsen',
    /** 利府線 */
    rifu: 'jr-rifu',
    /** 気仙沼線 */
    kesennuma: 'jr-kesennuma',
    /** 石巻線 */
    ishimaki: 'jr-ishimaki',
    /**  水郡線 */
    suigun: 'jr-suigun',
    /** 山形線 */
    yamagata: 'jr-yamagata',
    /** 千石東北ライン */
    sengoku_touhoku_line: 'jr-sengoku-touhoku-line',
    /** 奥羽本線 */
    ouu_honsen: 'jr-ouu-honsen',
    /** 仙山線 */
    senzan: 'jr-senzan',
    /** 仙石線 */
    sengoku: 'jr-sengoku',
    /** 陸羽東線 */
    rikuutou: 'jr-rikuutou',
    /** 陸羽西線 */
    rikuusei: 'jr-rikuusei',
    /** 左沢線 */
    aterazawa: 'jr-aterazawa',
    /** 大船渡線 */
    ofunato: 'jr-ofunato',
    /** 北上線 */
    kitakami: 'jr-kitakami',
    /** 釜石線 */
    kamaishi: 'jr-kamaishi',
    /** 山田線 */
    yamada: 'jr-yamada',
    /** 田沢湖線 */
    tazawako: 'jr-tazawako',
    /** 八戸線 */
    hachinohe: 'jr-hachinohe',
    /** 米坂線 */
    yonesaka: 'jr-yonesaka',
    /** 羽越本線 */
    uetsu_honsen: 'jr-uetsu-honsen',
    /** 男鹿線 */
    oga: 'jr-oga',


    shinkansen: {
      // 東海道新幹線
      tokaido: 'jr-tokaido-shinkansen',
      // 東北新幹線
      tohoku: 'jr-tohoku-shinkansen',
      // 山形新幹線
      yamagata: 'jr-yamagata-shinkansen',
      // 秋田新幹線
      akita: 'jr-akita-shinkansen',
      // 上越新幹線
      jouetsu: 'jr-shouetsu-shinkansen',
      // 北陸新幹線
      hokuriku: 'jr-hokuriku-shinkansen',
      // 北海道新幹線
      hokkaido: 'jr-hokkaido-shinkansen',
    },
  },
  /** 東武鉄道 */
  toubu: {
    // "東武アーバンパークライン",
    urban_park_line: 'toubu-urban-park-line',
    /** 亀戸線 */
    kameido: 'toubu-kameido',
    /** 東上線 */
    toujou: 'toubu-toujou',
    /** 伊勢崎線 */
    isesaki: 'toubu-isesaki',
    /** 日光線 */
    nikko: 'toubu-nikko',
    /** 東武線 */
    toubu: 'toubu-toubu',
    /** スカイツリーライン */
    skytree: 'toubu-skytree',
    /** 東武生越線 */
    tobu_ogose: 'toubu-tobu-ogose',
    /** 東葉高速線 */
    touyou_kousoku: 'toubu-touyou-kousoku',
  },
  saitama_shintoshi_koutsu: {
    // ニューシャトル
    new_shuttle: 'saitama_shintoshi_new_shuttle',
  },
  /** 首都圏新都市鉄道 */
  shutoken_shintoshi: {
    /** つくばエクスプレス */
    tsukuba_express: 'shutoken-shintoshi-tsukuba-express',
  },

  /** 小田急箱根 */
  odakyu_hakone: {
    kousaku: "hakone-tozan-cable-car",
    hakone_rope_way: "hakone-rope-way",
  },
  // 江ノ島電鉄
  enoshima: {
    enoshima: 'enoshima-enoshimadentetsu',
  },
  // 湘南モノレール
  shonam_monorail: {
    shonan_monorail: 'shonan-monorail',
  },
  /** 京王電鉄 */
  keiou: {
    /** 京王線 */
    keiou: 'keiou-keiou',
    /** 京王新線 */
    keioushinsen: 'keiou-keioushinsen',
    /** 井の頭線 */
    inokashira: 'keiou-inokashira',
    /** 高尾線 */
    takao: 'keiou-takao',
    /** 相模線 */
    sagami: 'keiou-sagami',
    /** 京王競馬場 */
    keibajo: 'keiou-keibajo',
    /** 京王動物園 */
    dobutsuen: 'keiou-dobutsuen',
  },
  /**流鉄 */
  ryutetsu: {
    ryutetsu_ryuzan: "ryutetsu-ryutetsu",
  },
  /** 鹿島臨海鉄道 */
  kashiwa_rinkai: {
    daikashima: "kashiwa-rinkai-daikashima",
  },
  /** ひたちなか海浜鉄道 */
  hitachinaka_kaihin: {
    minato: "hitachinaka-kaihin-minato",
  },
  /** 東急電鉄 */
  toukyu: {
    denentoshi: 'tokyu-denentoshi',
    /** 東横線 */
    touyoko: 'tokyu-toyoko',
    /** 池上線 */
    ikegami: "tokyu-ikegami",
    /** 新横浜線 */
    shin_yokohama: "tokyu-shin_yokohama",
    /** 多摩川線 */
    tamagawa: 'tokyu-tamagawa',
    /** 目黒線 */
    meguro: 'tokyu-meguro',
    /** 大井町線 */
    oimachi: "tokyu-oimachi",
    /** こどもの国線 */
    kodomonokuni: "keikyu-kodomonokuni",
    /** 世田谷線 */
    setagaya: "tokyu-setagaya",
  },
  /** 横浜市営地下鉄 */
  yokohama_subway: {
    blue_line: 'yokohama-subway-blue-line',
    green_line: 'yokohama-subway-green-line',
  },
  /** 横浜高速鉄道 */
  yokohama_kousoku: {
    minato_mirai: 'yokohama-kousoku-minato-mirai',
  },
  /** 東京臨海高速鉄道*/
  toukyo_rinkai_kousoku: {
    /** りんかい線 */
    rinkai: 'toukyo-rinkai-kousoku-rinkai',
  },
  /** 西武鉄道 路線 */
  seibu: {
    tamagawa: "seibu-tamagawa",
    tamako: "seibu-tamako",
    kokubunji: "seibu-kokubunji",
    ikebukuro: "seibu-ikebukuro",
    seibu_yurakucho: "seibu-seibu-yurakucho",
    toyoshima: "seibu-toyoshima",
    seibu_sayama: "seibu-seibu-sayama",
    seibu_chichibu: "seibu-seibu-chichibu",
    seibu_toshimaen: "seibu-seibu-toshimaen",
    shinjuku: "seibu-shinjuku",
    seibuen: "seibu-seibuen",
    haijima: "seibu-haijima",
  },
  /** 東葉高速鉄道 */
  toyo_kousoku: {
    toyo_kousoku: 'toyo-kousoku-toyo-kousoku',
  },
  /** 舞浜リゾート */
  maihama_resort: {
    disney_resort: 'maihama-resort-disney-resort',
  },
  /** 多摩モノレール */
  tama_monorail: {
    tama_monorail: 'tama-monorail',
  },
  /** 京成電鉄　路線 */
  keisei: {
    honsen: 'keisei-honsen',
    chiba: 'keisei-chiba',
    shin_keisei: "shin-keisei",
    keisei_narita_sky_access: "keisei-narita-sky-access",
    kanamachi: "keisei-kanamachi",
    oshiage: "keisei-oshiage",
    narita: "keisei-narita",
  },
  /** 北総電鉄　路線 */
  hokusou: {
    hokusou: 'hokusou-hokusou',
  },
  // ゆりかもめ
  yurikamome: {
    yurikamome: 'yurikamome',
  },
  /** 北越急行 */
  hokuetsu_kyuko: {
    hokuhoku: "hokuhoku",
  },
  /** 秩父鉄道 */
  chichibu: {
    chichibu: 'chichibu-chichibu',
  },
  /** 上信電鉄 */
  joushin: {
    joushin: 'joushin-joushin',
  },
  /** 伊豆箱根鉄道 */
  izuhakone: {
    daiyuzan: 'izuhakone-daiyuzan',
    sunzu: "izuhakone-sunzu",
  },
   /** 関東鉄道 */
   kanto: {
    joso: "kanto-joso"
  },
  /** 埼玉高速鉄道 */
  saitama_kosoku: {
    saitama_stadium: "saitama-stadium",
  },
  /** JR東海 */
  jr_tokai: {
    tenryuhamanako: 'jr-tokai-tenryuhamanako',
    ida: 'jr-tokai-ida',
    chuohonsen: 'jr-tokai-chuohonsen',
    aonami: 'jr-tokai-aonami',
    hokurikuhonsen: 'jr-tokai-hokurikuhonsen',
  },
  /** JR西日本線 */
  jr_west: {
    kansai_honsen: 'jr-west-kansai-honsen',
    saninhonsen: 'jr-west-saninhonsen',
    nara: 'jr-west-nara',
    osaka_higashi: 'jr-west-osaka-higashi',
    oito: 'jr-west-oito',
    takayama_honsen: 'jr-west-takayama-honsen',
    johana: 'jr-west-johana',
    nanao: 'jr-west-nanao',
    kuzuryu: 'jr-west-kuzuryu',
    kosei: 'jr-west-kosei',
    kohama: 'jr-west-kohama',
    hokuriku_honsen: 'jr-west-hokuriku-honsen',

    shinkansen: {
      sanyo: 'jr-west-sanyo-shinkansen',
    }
  },

  /** 名古屋鉄道 */
  nagoya: {
    nagoyahonsen: 'nahoya-nagoyahonsen',
  },
  /** 名古屋市営交通 */
  nagoya_shiei_subway: {
    sakuradori: 'nagoya-shiei-subway-sakuradori',
    higashiyama: 'nagoya-shiei-subway-higashiyama',
  },
  /** 近江鉄道 */
  oumi: {
    honsen: 'omi-honsen',
  },
  /** 京都市営地下鉄 */
  kyoto_shiei_subway: {
    karasuma: 'kyoto-shiei-subway-karasuma',
  },
  /** 近畿日本鉄道 */
  kinki_nihon: {
    kyoto: 'kinki-nihon-kyoto',
  },
  /** OsakaMetro */
  osaka_metro: {
    midosuji: 'osaka-metro-midosuji',
  },

  /** しなの鉄道 */
  shinano: {
    shinano: 'shinano-shinano',
    kita_shinano: 'shinano-kita-shinano',
  },
  /** 上田電鉄 */
  ueda: {
    bessho: 'ueda-bessho',
  },
  /** 長野電鉄 */
  nagano: {
    nagano: 'nagano-nagano',
  },
  /** えちごトキめき鉄道 */
  echigo_tokimeki: {
    myoko_haneuma: 'echigo-tokimeki-myoko-haneuma',
    nihonkai_hisui: 'echigo-tokimeki-nihonkai-hisui',
  },
  /** あいの風とやま鉄道 */
  ainokaze_toyama: {
    ainokaze_toyama_tetsudo: 'ainokaze-toyama-ainokaze-toyama_tetsudo',
  },
  /** 富山地方鉄道(富山地鉄) */
  toyama_chiho: {
    /** 本線 */
    honsen: 'toyama-chitetsu-honsen',
    fujikoshi_takigami: 'toyama-chiho-fujikoshi-takigami',
    toyama_kido: 'toyama-chiho-toyama-kido',
    shinai_kanjo: 'toyama-chiho-shinai-kanjo',
    toyamako: 'toyama-chiho-toyamako',
  },
  /** 北陸鉄道 */
  hokuriku: {
    asanogawa: 'hokuriku-asanogawa',
  },
  /** IRいしかわ鉄道 */
  ir_ishikawa: {
    ir_ishikawa: 'ir-ishikawa-ir_ishikawa',
  },
  /** はぴラインふくい */
  hapi_line_fukui: {
    hapi_line_fukui: 'hapi-line-fukui-hapi_line_fukui',
  },
  /** えちぜん鉄道 */
  echizen: {
    katsuyama_eiheiji: 'echizen-katsuyama-eiheiji',
    mikuni_awara: 'echizen-mikuni-awara',
  },
  /** 福井鉄道 */
  fukui: {
    fukui_tetsudo: 'fukui-fukui_tetsudo',
    fukubu: 'fukui-fukubu',
  },

  /** 阿武隈急行 */
  abukuma_kyuko: {
    abukuma_kyuko: 'abukuma-kyuko',
  },
  /** 福島交通 */
  fukushima_koutsu: {
    iizaka: 'fukushima-koutsu-iizaka',
  },
  /** 仙台空港鉄道 */
  sendai_kuko: {
    access: 'sendai-kuko-access',
  },
  /** 仙台市地下鉄 */
  sendai_subway: {
    nanboku: 'sendai-shiei-subway-nanboku',
    touzai: 'sendai-shiei-subway-touzai',
  },
  /** IGRいわて銀河鉄道 */
  igr_iwate_ginga: {
    igr_iwate_ginga_tetudo: 'igr-iwate-ginga_tetudo',
  },
  /** 青い森鉄道 */
  aoimori: {
    aoimori_tetudo: 'aoimori-aoimori_tetudo',
  },
  /** 山形鉄道 */
  yamagata: {
    flower_nagai: 'yamagata-flower-nagai',
  },
  /** 秋田内陸縦貫鉄道 */
  akita_nairiku_jukan: {
    akita_nairiku: 'akita-nairiku-jukan-akita-nairiku',
  },
  /** 道南いさりび鉄道 */
  dounan_isaribi: {
    dounan_isaribi: 'dounan-isaribi-dounan-isaribi',
  },
  /** JR北海道 路線*/
  jr_hokkaidou: {
    /** 函館本線 */
    hakodate_honsen: 'jr-hokkaidou-hakodate-honsen',
    /** 富良野線 */
    furano: 'jr-hokkaidou-furano',
    /** 石北本線 */
    sekihoku_honsen: 'jr-hokkaidou-sekihoku-honsen',
    /** 宗谷本線 */
    souya_honsen: 'jr-hokkaidou-souya-honsen',
    /** 根室本線(滝川ー富良野) */
    nemuro_honsen1: 'jr-hokkaidou-nemuro-honsen1',
    /** 根室本線(新得―釧路) */
    nemuro_honsen2: 'jr-hokkaidou-nemuro-honsen2',
    /** 室蘭本線 */
    muroran_honsen1: 'jr-hokkaidou-muroran-honsen1',
    muroran_honsen2: 'jr-hokkaidou-muroran-honsen2',
    /** 千歳線 */
    chitose: 'jr-hokkaidou-chitose',
    /** 札沼線 */
    sassyou: 'jr-hokkaidou-sassyou',
    /** 学園都市線 */
    gakuentoshi: 'jr-hokkaidou-gakuentoshi',
    /** 釧網本線 */
    senmou_honsen: 'jr-hokkaidou-senmou-honsen',
    /** 花咲線 */
    hanasaki: 'jr-hokkaidou-hanasaki',
    /** 石勝線 */
    sekisyou: 'jr-hokkaidou-sekisyou',
    /** 日高本線 */
    hidaka_honsen: 'jr-hokkaidou-hidaka-honsen',
  },
  /** 札幌地下鉄 */
  sapporo_subway: {
    touzai: 'sapporo-subway-touzai',
    nanboku: 'sapporo-subway-nanboku',
    touhou: 'sapporo-subway-touhou',
  },
};

/** 駅ID */
export const STATION_IDS = {
  /** 京急駅 */
  keikyu: {
    kitashinagawa: 'kitashinagawa',
    shinbanba: 'shinbanba',
    aomonoyokocho: 'aomonoyocho',
    samezu: 'samezu',
    tachiaigawa: 'tachiaigawa',
    omorikaigan: 'omorikaigan',
    heiwajima: 'heiwajima',
    omorimachi: 'omorimachi',
    umeyashiki: 'umeyashiki',
    keikyukamata: 'keikyukamata',
    zoushiki: 'zoushiki',
    rokugodote: 'rokugodote',
    keikyukawasaki: 'keikyukawasaki',
    hacchonawate: 'hacchonawate',
    tsurumiichiba: 'tsurumiichiba',
    keikyutsurumi: 'keikyutsurumi',
    kagetusoujiji: 'kagetusoujiji',
    namamugi: 'namamugi',
    keikyushinkoyasu: 'keikyushinkoyasu',
    koyasu: 'koyasu',
    kanagawashinmachi: 'kanagawashinmachi',
    keikyuhigashikanagawa: 'keikyuhigashi-kanagawa',
    kanagawa: 'kanagawa',
    tobe: 'tobe',
    hinodecho: 'hinodecho',
    koganecho: 'koganecho',
    minamiota: 'minamiota',
    idogaya: 'idogaya',
    gumyouji: 'gumyouji',
    kamiooka: 'kamiooka',
    byobugaura: 'byobugaura',
    sugita: 'sugita',
    keikyutomioka: 'keikyutomioka',
    noukendai: 'noukendai',
    kanazawabunko: 'kanazawabunko',
    kanazawahakkei: 'kanazawahakkei',
    oppama: 'oppama',
    keikyutaura: 'keikyutaura',
    anjinduka: 'anjinduka',
    hemi: 'hemi',
    shioiri: 'shioiri',
    yokosukachuo: 'yokosukachuo',
    kenritsudaigaku: 'kenritsudaigaku',
    horinouchi: 'horinouchi',
    keikyuotsu: 'keikyuotsu',
    maborikaigan: 'maborikaigan',
    uraga: 'uraga',
    shinotsu: 'shinotsu',
    kitakurihama: 'kitakurihama',
    keikyukurihama: 'keikyukurihama',
    yrp_nobi: 'yrp-nobi',
    keikyunagsawa: 'keikyunaosawa',
    tsukuihama: 'tsukuihama',
    miurakaigan: 'miurakaigan',
    misakiguchi: 'misakiguchi',
    mutsuura: 'mutsuura',
    jinmuji: 'jinmuji',
    zushihayama: 'zushihayama',
    minatocho: 'minatocho',
    suzukicho: 'suzukicho',
    kawasakidaishi: 'kawasakidaishi',
    higashimonzen: 'higashimonzen',
    daishibashi: 'daishibashi',
    kojimashinden: 'kojimashinden',
    koujiya: 'koujiya',
    otorii: 'otorii',
    anamoriinari: 'anamoriinari',
    tenkubashi: 'tenkubashi',
    hanedakuko_daisan_terminal: 'hanedakuko-daisan-terminal',
    hanedakuko_dai1_dai2_terminal: 'hanedakuko-dai1-dai2-terminal',
    torihama: 'torihama',
    namiki_kita: 'namiki-kita',
    namiki_chuo: 'namiki-chuo',
    sachiura: 'sachiura',
    sangyou_hukkou_center: 'sangyou-hukkou-center',
    fukuura: 'fukuura',
    shidai_igakubu: 'shidai-igakubu',
    hakkeijima: 'hakkeijima',
    uminokouen_shibaguchi: 'uminokouen-shibaguchi',
    uminokouen_minamiguchi: 'uminokouen-minamiguchi',
    nojima_kouen: 'nojima-kouen',
    nanbushijo: 'nanbushijo',
  },
  /** 都営駅 */
  tokyo_subway: {
    // 浅草線
    honjo_azumabashi: 'honjo-azumaba-shi',
    asakusa: 'asakusa',
    kuramae: 'kuramae',
    asakusabashi: 'asakusabashi',
    higashi_nihonbashi: 'higashi-nihonbashi',
    ningyocho: 'ningyocho',
    nihonbashi: 'nihonbashi',
    takaracho: 'takaracho',
    higashi_ginza: 'higashi-ginza',
    daimon: 'daimon',
    mita: 'mita',
    sengakuji: 'sengakuji',
    takanawadai: 'takanawa-dai',
    gotanda: 'gotanda',
    togoshi: 'togoshi',
    nakanobe: 'nakanobe',
    magome: 'magome',
    nishimagome: 'nishimagome',
    // 新宿線
    shinohara: 'shinohara',
    mizue: 'mizue',
    ichinoe: 'ichinoe',
    funabori: 'funabori',
    higashi_oshima: 'higashi-oshima',
    oshima: 'oshima',
    nishi_oshima: 'nishi-oshima',
    sumiyoshi: 'sumiyoshi',
    kikukawa: 'kikukawa',
    morishita: 'morishita',
    hamacho: 'hamacho',
    bakuro_yokoyama: 'bakuro-yokoyama',
    iwamotocho: 'iwamotocho',
    ogawacho: 'ogawacho',
    jinbocho: 'jinbocho',
    kudanshita: 'kudanshita',
    akebonobashi: 'akebonobashi',
    shinsen_shinjuku: 'shinsen-shinjuku',
    // 大江戸線
    tochomae: 'tochomae',
    shinjuku_nishiguchi: 'shinjuku-nishiguchi',
    wakamatsukawada: 'wakamatsukawada',
    ushigomeyanagicho: 'ushigomeyanagicho',
    ushigomekagurazaka: 'ushigomekagurazaka',
    kasuga: 'kasuga',
    hongo_sancho_me: 'hongo-sancho-me',
    ueno_okachimachi: 'ueno-okachimachi',
    kiyosumishirakawa: 'kiyosumishirakawa',
    monzennakacho: 'monzennakacho',
    tsukishima: 'tsukishima',
    kachidoki: 'kachidoki',
    tsukijishijo: 'tsukijishijo',
    shiodome: 'shiodome',
    akabanebashi: 'akabanebashi',
    azabujuban: 'azabujuban',
    roppongi: 'roppongi',
    aoyama_itchome: 'aoyama-itchome',
    kokuritsu_kyogijo: 'kokuritsu-kyogijo',
    nishi_shinjuku_gochome: 'nishi-shinjuku-gochome',
    nakano_sakaue: 'nakano-sakaue',
    nakai: 'nakai',
    ochiaiminaminagasaki: 'ochiaiminaminagasaki',
    shin_egota: 'shin-egota',
    toshimaen: 'toshimaen',
    nerima_kasugacho: 'nerima-kasugacho',
    hikarigaoka: 'hikarigaoka',
    takawadai: 'takawadai',
    // 三田線
    nishi_takashimadaira: 'nishi-takashimadaira',
    shin_takashimadaira: 'shin-takashimadaira',
    takashimadaira: 'takashimadaira',
    renkon: 'renkon',
    shimura_sanchome: 'shimura-sanchome',
    shimura_sakaue: 'shimura-sakaue',
    honhasunuma: 'honhasunuma',
    itabashihoncho: 'itabashihoncho',
    itabashi_kuyakushomae: 'itabashi-kuyakushomae',
    shin_itabashi: 'shin-itabashi',
    nishi_sugamo: 'nishi-sugamo',
    nishidai: 'nishidai',
    sengoku: 'sengoku',
    hakusan: 'hakusan',
    uchisaiwaicho: 'uchisaiwaicho',
    onarimon: 'onarimon',
    shiba_koen: 'shiba-koen',
    // 日暮里舎人ライナー
    akado_shogakko_mae: 'akado-shogakko-mae',
    kumanomae: 'kumanomae',
    adachi_odai: 'adachi_odai',
    ougiohashi: 'ougiohashi',
    takano: 'takano',
    kouhoku: 'kouhoku',
    nishiaraidaishi_nishi: 'nishiaraidaishi-nishi',
    yazaike: 'yazaike',
    toneri_koen: 'toneri-koen',
    toneri: 'toneri',
    minumadaishinsui_koen: 'minumadai-shinsui-koen',
    // 東京さくらトラム
    minowabashi: 'toei-minowabashi',
    arakawa_icchumae: 'toei-arakawa-icchumae',
    arakawa_kuyakushomae: 'toei-arakawa-kuyakushomae',
    arakawa_nichoume: 'toei-arakawa-nichoume',
    arakawa_nanachoume: 'toei-arakawa-nanachoume',
    machiyaekimae: 'toei-machiyaekimae',
    machiya_nichoume: 'toei-machiya-nichoume',
    higashi_oku_sanchoume: 'toei-higashi-oku-sanchoume',
    miyanomae: 'toei-miyanomae',
    kodai: 'toei-kodai',
    arakawa_yuenchimae: 'toei-arakawa-yuenchimae',
    arakawa_shakomae: 'toei-arakawa-shakomae',
    kajiwara: 'toei-kajiwara',
    sakaechou: 'toei-sakaechou',
    oujiekimae: 'toei-oujiekimae',
    asukayama: 'toei-asukayama',
    takinogawa_icchome: 'toei-takinogawa-icchome',
    nishigawara_yonchoume: 'toei-nishigawara-yonchoume',
    shin_koushinduka: 'toei-shinkoushinduka',
    koushinduka: 'toei-koushinduka',
    sugamo_shinden: 'toei-sugamo-shinden',
    otsukaekimae: 'toei-otsukaekimae',
    mukouhara: 'toei-mukouhara',
    higashi_ikebukuro_yonchoume: 'toei-higashi-ikebukuro-yonchoume',
    toden_zoushigaya: 'toei-toden-zoushigaya',
    kishiboshinmae: 'toei-kishiboshinmae',
    gakusyuinshita: 'toei-gakusyuinshita',
    omokagebashi: 'toei-omokagebashi',
    waseda: 'toei-waseda',
  },
  /** 東京メトロ 駅 */
  tokyo_metro: {
    nakameguro: 'nakameguro',
    hiroo: 'hiroo',
    roppongi: 'roppongi',
    kamiyacho: 'kamiyacho',
    toranomon_hills: 'toranomon-hills',
    kasumigaseki: 'kasumigaseki',
    hibiya: 'hibiya',
    ginza: 'ginza',
    higashiginza: 'higashi-ginza',
    tsukiji: 'tsukiji',
    kayabacho: 'kayabacho',
    ningyocho: 'ningyocho',
    kodenmacho: 'kodenmacho',
    nakaokachimachi: 'naka-okachimachi',
    iriya: 'iriya',
    minowa: 'minowa',
    minamisenju: 'minamisenju',
    kitasenju: 'kitasenju',
    shinotuka: 'shinotuka',
    myogadani: 'myogadani',
    kourakuen: 'kourakuen',
    hongosanchome: 'hongosanchome',
    awajicho: 'awajicho',
    otemachi: 'otemachi',
    kokkaigijidomae: 'kokkaigijidome',
    akasakamitsuke: 'akasaka-mitsuke',
    yotsuya_sanchome: 'yotsuya-sanchome',
    shinjuku_gyoenmae: 'shinjuku-gyoenmae',
    shinjuku_sanchome: 'shinjuku-sanchome',
    nishishinjuku: 'nishishinjuku',
    nakano_sakaue: 'nakano-sakaue',
    shinnakano: 'shinnakano',
    higashi_koenji: 'higashi-koenji',
    shinkoenji: 'shinkoenji',
    minamiasagaya: 'minamiasagaya',
    // 有楽町線
    wakoshi: 'wakoshi',
    chikatetsu_narimasu: 'chikatetsu-narimasu',
    chikatetsu_akatsuka: 'chikatetsu-akatsuka',
    heiwadai: 'heiwadai',
    hikawadai: 'hikawadai',
    kotake_mukaihara: 'kotake-mukaihara',
    senkawa: 'senkawa',
    kanamecho: 'kanamecho',
    higashi_ikebukuro: 'higashi-ikebukuro',
    gokokuji: 'gokokuji',
    edogawabashi: 'edogawabashi',
    idabashi: 'idabashi',
    koujimachi: 'koujimachi',
    nagatacho: 'nagatacho',
    sakuradamon: 'sakuradamon',
    ginza_icchome: 'ginza-icchome',
    shintomicho: 'shintomicho',
    tsukishima: 'tsukishima',
    toyosu: 'toyosu',
    tatsumi: 'tatsumi',
    shinkiba: 'shinkiba',
    // 副都心線
    zoshigaya: 'zoshi-gaya',
    nishi_waseda: 'nishi-waseda',
    kitasandou: 'kitasandou',
    meiji_jingumae: 'meiji-jingumae',
    higashi_shinjuku: 'higashi-shinjuku',
    // 銀座線
    gaienmae: 'tokyo-metro-gaienmae',
    tameikesanno: 'tokyo-metro-tameikesanno',
    kyobashi: 'tokyo-metro-kyobashi',
    toranomon: 'tokyo-metro-toranomon',
    mitsukoshimae: 'tokyo-metro-mitsukoshimae',
    suehirocho: 'tokyo-metro-suehirocho',
    ueno_hirokoji: 'tokyo-metro-ueno-hirokoji',
    inaricho: 'tokyo-metro-inaricho',
    tawaramachi: 'tokyo-metro-tawaramachi',
    omotesando: 'tokyo-metro-omotesando',
    nihonbashi: 'tokyo-metro-nihonbashi',
    // 半蔵門線
    hanzomon: 'tokyo-metro-hanzomon',
    suitengumae: 'tokyo-metro-suitengumae',
    oshiage: 'oshiage',
    kiyosumi_shirakawa: 'kiyosumi_shirakawa',
    // 南北線
    shirokanedai: 'shirokanedai',
    shirokane_takanawa: 'shirokane-takanawa',
    roppongi_iccho_me: 'roppongi-iccho-me',
    todaimae: 'todaimae',
    honkomagome: 'honkomagome',
    nishigahara: 'nishigahara',
    oji_kamiya: 'oji-kamiya',
    shimo: 'shimo',
    akabane_iwabuchi: 'akabane-iwabuchi',
    oji: 'oji',
    // 千代田線
    yoyogi_koen: 'tokyo-metro-yoyogi-koen',
    nogizaka: 'tokyo-metro-nogisaka',
    akasaka: 'tokyo-metro-akasaka',
    nijubashimae: 'tokyo-metro-nijubashimae',
    yushima: 'tokyo-metro-yushima',
    nedu: 'tokyo-metro-nedu',
    sendagi: 'tokyo-metro-sendagi',
    shin_ochanomizu: 'tokyo-metro-shin-ochanomizu',
    machiya: 'tokyo-metro-machiya',
    ayase: 'tokyo-metro-ayase',
    kita_ayase: 'tokyo-metro-kita-ayase',
    // 東西線
    ochiai: 'tokyo-metoro-ochiai',
    waseda: 'tokyo-metro-waseda',
    kagurazaka: 'tokyo-metro-kagurazaka',
    takehashi: 'tokyo-metro-takehashi',
    kiba: 'tokyo-metro-kiba',
    touyocho: 'tokyo-metro-touyocho',
    minami_sunamachi: 'tokyo-metro-minami-sunamachi',
    nishi_kasai: 'tokyo-metro-nishi-kasai',
    kasai: 'tokyo-metro-kasai',
    urayasu: 'tokyo-metro-urayasu',
    minami_gyotoku: 'tokyo-metro-minami-gyotoku',
    gyotoku: 'tokyo-metro-gyotoku',
    myouden: 'tokyo-metro-myouden',
    baraki_nakayama: 'tokyo-metro-baraki-nakayama',
  },
  /** 千葉都市モノレール */
  chiba_toshi_monorail: {
    shiyakusyomae: 'chiba-toshi-monorail-shiyakusyomae',
    sakaemachi: 'chiba-toshi-monorail-sakaemachi',
    yoshikawa_kouen: 'chiba-toshi-monorail-yoshikawa-kouen',
    kenchoumae: 'chiba-toshi-monorail-kenchoumae',
    chiba_kouen: 'chiba-toshi-monorail-chiba-kouen',
    sakusabe: 'chiba-toshi-monorail-sakusabe',
    tendai: 'chiba-toshi-monorail-tendai',
    anagawa: 'chiba-toshi-monorail-anagawa',
    sports_center: 'chiba-toshi-monorail-sports-center',
    doubutsu_kouen: 'chiba-toshi-monorail-doubutsu-kouen',
    mitsuwadai: 'chiba-toshi-monorail-mitsuwadai',
    sakuragi: 'chiba-toshi-monorail-sakuragi',
    oguradai: 'chiba-toshi-monorail-oguradai',
    chishirodai_kita: 'chiba-toshi-monorail-chishirodai-kita',
    chishirodai: 'chiba-toshi-monorail-chishirodai',
  },
   /** 首都圏新都市 */
   shutoken_shintoshi: {
    tsukuba: 'tsukuba',
    kenkyugakuen: 'kenkyugakuen',
    banpakukinenkouen: 'banpakukinenkouen',
    midorino: 'midorino',
    miraidaira: 'miraidaira',
    moriya: 'moriya',
    kashiwa_tanaka: 'kashiwa-tanaka',
    kashiwanoha_campus: 'kashiwanoha-campus',
    nagareyama_otakanomori: 'nagareyama-otakanomori',
    nagareyama_centralpark: 'nagareyama-centralpark',
    sango_chuo: 'sango-chuo',
    yashio: 'yashio',
    rokucho: 'rokucho',
    aoi: 'aoi',
    shin_okachimachi: 'shin-okachimachi',
  },
  /** 東京モノレール 駅 */
  tokyo_monorail: {
    tennozu_isle: 'tennozu-isle',
    oi_keibajo_mae: 'oi-keibajo-mae',
    ryutsu_center: 'ryutsu-center',
    syouwajima: 'syouwajima',
    seibijo: 'seibijo',
    tenkubashi: 'tenkubashi',
    haneda_kuko_daisan_terminal: 'haneda-kuko-daisan-terminal',
    shin_seibijo: 'shin-seibijo',
    haneda_kuko_dai1_terminal: 'haneda-kuko-dai1-terminal',
    haneda_kuko_dai2_terminal: 'haneda-kuko-dai2-terminal',
  },
  /** ゆりかもめ 駅 */
  yurikamome: {
    takeshiba: 'yurikamome-takeshiba',
    hinode: 'yurikamome-hino-de',
    shibaurafuto: 'yurikamome-shibaurafuto',
    odaiba_kaihinkoen: 'yurikamome-odaiba-kaihinkoen',
    daiba: 'yurikamome-daiba',
    tokyo_kokusai_cruise_terminal: 'yurikamome-tokyo-kokusai-cruise-terminal',
    aomi: 'yurikamome-aomi',
    telecom_center: 'yurikamome-telecom-center',
    tokyo_big_sight: 'yurikamome-tokyo-big-sight',
    ariake: 'yurikamome-ariake',
    ariake_tennis_no_mori: 'yurikamome-ariake-tennis-no-mori',
    shijomae: 'yurikamome-shijo-mae',
    shin_toyosu: 'yurikamome-shin-toyosu',
  },
   /** 相鉄駅 */
   sagami: {
    ebina: "ebina",
    kashiwadai: "kashiwadai",
    sagamino: "sagamino",
    sagamiotsuka: "sagamiotsuka",
    futamatagawa: "futamatagawa",
    tsuruma: "tsuruma",
    seya: "seya",
    mitsukyo: "mitsukyo",
    kibougaoka: "kibougaoka",
    tsurugamine: "tsurugamine",
    nishiya: "nishiya",
    kamihoshikawa: "kamihoshikawa",
    wadacho: "wadacho",
    hoshikawa: "hoshikawa",
    tennocho: "tennocho",
    nishiyokohama: "nishiyokohama",
    hiranumabashi: "hiranumabashi",
    hazawayokohamakokudai: "hazawayokohamakokudai",
    // いずみ野線
    minami_makigahara: "sagami-minami-makigahara",
    ryokuentoshi: "sagami-ryokuentoshi",
    yayoidai: "sagami-yayoidai",
    izumino: "sagami-izumino",
    yumegaoka: "sagami-yumegaoka",
    izumichuo: "sagami-izumichuo",
  },
  /** 東急 駅 */
  toukyu: {
    // 田園都市線
    ikejiriohashi: "ikejiriohashi",
    sangenjaya: "sangenjaya",
    komazawadaigaku: "komazawadaigaku",
    sakurashinmachi: "sakurashinmachi",
    yoga: "yoga",
    futakotamagawa: "futakotamagawa",
    futako_shinchi: "futako-shinchi",
    takatsu: "takatsu",
    mizonokuchi: "mizonokuchi",
    kajigaya: "kajigaya",
    miyazakidai: "miyazakidai",
    miyamaedaira: "miyamaedaira",
    washinuma: "washinuma",
    tama_plaza: "tama-plaza",
    azamino: "azamino",
    eda: "eda",
    ichigao: "ichigao",
    fujigaoka: "fujigaoka",
    aobadai: "aobadai",
    tana: "tana",
    tsukushino: "tsukushino",
    suzukakedai: "suzukakedai",
    minamimachida_grandberry_park: "minamimachida-grandberry-park",
    tsukimino: "tsukimino",
    // 多摩川線
    tamagawa: "tamagawa",
    numabe: "numabe",
    unoki: "unoki",
    simomaruko: "simomaruko",
    musashishinden: "musashishinden",
    yagutiwatashi: "yagutiwatashi",
    // 大井町線
    shimoshinmei: "shimoshinmei",
    togoshikouen: "togoshikouen",
    nakanobe: "nakanobe",
    ebaracho: "ebaracho",
    hatanodai: "hatanodai",
    kitasenzoku: "kitasenzoku",
    ookayama: "ookayama",
    midorigaoka: "midorigaoka",
    jiyugaoka: "jiyugaoka",
    kuhonbutsu: "kuhonbutsu",
    oyamadai: "oyamadai",
    todoroki: "todoroki",
    kaminoge: "kaminoge",
    // 目黒線
    fudomae: "fudomae",
    musashikoyama: "musashikoyama",
    nishikoyama: "nishikoyama",
    senzoku: "senzoku",
    okuzawa: "okuzawa",
    denenchohu: "denenchohu",
    shinmaruko: "shinmaruko",
    motosumiyoshi: "motosumiyoshi",
    shin_tsunashima: "toukyu-shin-tsunashima",
    // 東横線
    daikanyama: "toukyu-daikanyama",
    yutenji: "toukyu-yutenji",
    gakugei_daigaku: "toukyu-gakugei-daigaku",
    toritsu_daigaku: "toukyu-toritsu-daigaku",
    tsunashima: "toukyu-tsunashima",
    okurayama: "toukyu-okurayama",
    myourenji: "toukyu-myourenji",
    hakuraku: "toukyu-hakuraku",
    higashi_hakuraku: "toukyu-higashi-hakuraku",
    tanmachi: "toukyu-tanmachi",
    // 池上線
    osaki_hirokoji: "toukyu-osaki-hirokoji",
    togoshi_ginza: "toukyu-togoshi-ginza",
    ebara_nakanobu: "toukyu-ebara-nakanobu",
    nagahara: "toukyu-nagahara",
    senzokuike: "toukyu-senzokuike",
    ishikawadai: "toukyu-ishikawadai",
    yukigaya_otsuka: "toukyu-yukigaya-otsuka",
    mitakeyama: "toukyu-mitakeyama",
    kugahara: "toukyu-kugahara",
    chidoricho: "toukyu-chidoricho",
    ikegami: "toukyu-ikegami",
    hasunuma: "toukyu-hasunuma",
    // 世田谷線
    nishitaishidou: "toukyu-nishitaishidou",
    wakabayashi: "toukyu-wakabayashi",
    syouinjinjamae: "toukyu-syouinjinja-mae",
    kamimachi: "toukyu-kamimachi",
    miyanosaka: "toukyu-miyanosaka",
    matsubara: "toukyu-matsubara",
    setagaya: "toukyu-setagaya",
    yamashita: "toukyu-yamashita",
    // こどもの国線
    onda: "toukyu-onda",
    kodomonokuni: "toukyu-kodomonokuni",
  },
   /** 横浜市営地下鉄 */
   yokohama_subway: {
    // blue line
    nakagawa: "yokohama-subway-nakagawa",
    center_kita: "yokohama-subway-center-kita",
    center_minami: "yokohama-subway-center-minami",
    nakamachidai: "yokohama-subway-nakamachidai",
    nippa: "yokohama-subway-nippa",
    kita_shin_yokohama: "yokohama-subway-kita-shin-yokohama",
    kishine_kouen: "yokohama-subway-kishine-kouen",
    katakurachou: "yokohama-subway-katakurachou",
    mitsuzawa_shimocho: "yokohama-subway-mitsuzawa-shimocho",
    mitsuzawa_kamicho: "yokohama-subway-mitsuzawa-kamicho",
    takashimachou: "yokohama-subway-takashimachou",
    isezakichoujamachi: "yokohama-subway-isezakichoujamachi",
    bantoubashi: "yokohama-subway-bantoubashi",
    yoshinochou: "yokohama-subway-yoshinochou",
    maita: "yokohama-subway-maita",
    gumyouji: "yokohama-subway-gumyouji",
    kounan_chuou: "yokohama-subway-kounan-chuou",
    kaminagaya: "yokohama-subway-kaminagaya",
    shimonagaya: "yokohama-subway-shimonagaya",
    maioka: "yokohama-subway-maioka",
    odoriba: "yokohama-subway-odoriba",
    nakada: "yokohama-subway-nakada",
    tateba: "yokohama-subway-tateba",
    shimo_iida: "yokohama-subway-shimo-iida",
    // green line
    hiyoshi: "yokohama-subway-hiyoshi",
    hiyoshi_honchou: "yokohama-subway-hiyoshi-honchou",
    takada: "yokohama-subway-takada",
    higashi_yamada: "yokohama-subway-higashi-yamada",
    kita_yamada: "yokohama-subway-kita-yamada",
    tuduki_fureainooka: "yokohama-subway-tuduki-fureainooka",
    kawawacho: "yokohama-subway-kawawacho",
  },
  /** 小田急駅 */
  odakyu: {
    sagamiono: "sagamiono",
    higashirinkan: "higashirinkan",
    chuorinkan: "chuorinkan",
    minamirinkan: "minamirinkan",
    tsuruma: "tsuruma",
    yamato: "yamato",
    sakuragaoka: "sakuragaoka",
    kouzashibuya: "kouzashibuya",
    chogo: "chogo",
    shonandai: "shonandai",
    mutsuainichidaimae: "mutsuainichidaimae",
    zengyo: "zengyo",
    fujisawahonmachi: "fujisawahonmachi",
    kugenuma: "kugenuma",
    honkugenuma: "honkugenuma",
    kugenumakaigan: "kugenumakaigan",
    kataseenoshima: "kataseenoshima",
    // 小田原線
    minamishinjuku: "minamishinjuku",
    sangubashi: "sangubashi",
    yoyogihachiman: "yoyogihachiman",
    yoyogiuehara: "yoyogiuehara",
    higashikitazawa: "higashikitazawa",
    shimokitazawa: "shimokitazawa",
    setagayadaita: "setagayadaita",
    umegaoka: "umegaoka",
    gotokuji: "gotokuji",
    kyodo: "kyodo",
    chitosefunabashi: "chitosefunabashi",
    soshigayaokura: "soshigayaokura",
    seijogakuenmae: "seijogakuenmae",
    kitami: "kitami",
    komae: "komae",
    izumitamagawa: "izumitamagawa",
    mukougaokayuen: "mukougaokayuen",
    ikuta: "ikuta",
    yomiuri_land_mae: "yomiuri-land-mae",
    yurigaoka: "yurigaoka",
    shinyurigaoka: "shinyurigaoka",
    soubudaimae: "soubudaimae",
    kakio: "kakio",
    tsurukawa: "tsurukawa",
    tamagawagakuenmae: "tamagawagakuenmae",
    odakyusagamihara: "odakyusagamihara",
    musashidaimae: "musashidaimae",
    zama: "zama",
    ebina: "ebina",
    honatsugi: "honatsugi",
    aikouishida: "aikouishida",
    isehara: "isehara",
    tsurumakionsen: "tsurumakionsen",
    toukaidaigakumae: "toukaidaigakumae",
    hadano: "hadano",
    shibusawa: "shibusawa",
    shinmatsuda: "shinmatsuda",
    kaisei: "kaisei",
    kayama: "kayama",
    tomizu: "tomizu",
    hotaruda: "hotaruda",
    ashigara: "ashigara",
    // 箱根登山線
    hakone_itabashi: "odakyu-hakone-itabashi",
    kazamatsuri: "odakyu-kazamatsuri",
    iryuda: "odakyu-iryuda",
    hakone_yumoto: "odakyu-hakone-yumoto",
    tounosawa: "odakyu-tounosawa",
    ohiradai: "odakyu-ohiradai",
    miyanoshita: "odakyu-miyanoshita",
    kowakidani: "odakyu-kowakidani",
    choukokunomori: "odakyu-choukokunomori",
    goura: "odakyu-goura",
    // 多摩線
    satsukidai: "odakyu-satsukidai",
    kurihira: "odakyu-kurihira",
    kurokawa: "odakyu-kurokawa",
    haruhino: "odakyu-haruhino",
    odakyu_eizan: "odakyu-odakyu-eizan",
    odakyu_tama_center: "odakyu-odakyu-tama-center",
    karakida: "odakyu-karakida",
  },
  /** 多摩モノレール */
  tama_monorail: {
    tama_center: "tama-monorail-tama-center",
    matsugatani: "tama-monorail-matsugatani",
    otsuka_teikyou_daigaku: "tama-monorail-otsuka-teikyou-daigaku",
    chuou_daigaku_myoujou_daigaku: "tama-monorail-chuou-daigaku-myoujou-daigaku",
    tama_doubutsu_kouen: "tama-monorail-tama-doubutsu-kouen",
    hodokubo: "tama-monorail-hodokubo",
    manganji: "tama-monorail-manganji",
    kousyukaidou: "tama-monorail-kousyukaidou",
    shibasaki_taiikukan: "tama-monorail-shibasaki-taiikukan",
    takamatsu: "tama-monorail-takamatsu",
    tachihi: "tama-monorail-tachihi",
    izumi_taiikukan: "tama-monorail-izumi-taiikukan",
    sunagawananaban: "tama-monorail-sunagawa-nanaban",
    tamagawajousui: "tama-monorail-tamagawa-jousui",
    sakurakaidou: "tama-monorail-sakurakaidou",
    kamikitadai: "tama-monorail-kamikitadai",
  },

  /** JR東日本駅 */
  jr_east: {
    //常盤線(JA)
    mikawashima: "mikawashima",
    minami_senju: "minami_senju",
    kita_senju: "kita_senju",
    ayase: "ayase",
    kameari: "kameari",
    kanamachi: "kanamachi",
    matsudo: "matsudo",
    kita_matsudo: "kita_matsudo",
    mahashi: "mahashi",
    shin_matsudo: "shin_matsudo",
    kita_kogane: "kita_kogane",
    minami_kashiwa: "minami_kashiwa",
    kashiwa: "kashiwa",
    kita_kashiwa: "kita_kashiwa",
    abiko: "abiko",
    tennodai: "tennodai",
    toride: "toride",
    fujishiro: "fujishiro",
    ryugasakishi: "ryugasakishi",
    ushiku: "ushiku",
    hitachino_ushiku: "hitachino_ushiku",
    arakawaoki: "arakawaoki",
    tuchiura: "tuchiura",
    kandachi: "kandachi",
    takahama: "takahama",
    ishioka: "ishioka",
    hadori: "hadori",
    iwama: "iwama",
    tomobe: "tomobe",
    uchihara: "uchihara",
    akatsuka: "akatsuka",
    kairakuen: "kairakuen",
    mito: "mito",
    katsuta: "katsuta",
    sawa: "sawa",
    toukai: "toukai",
    omika: "omika",
    hitachi_taga: "hitachi_taga",
    hitachi: "hitachi",
    ogitsu: "ogitsu",
    juo: "juo",
    takahagi: "takahagi",
    minami_nakazato: "minami_nakazato",
    isohara: "isohara",
    otsuko: "otsuko",
    nakoso: "nakoso",
    izumi: "izumi",
    yumoto: "yumoto",
    uchisato: "uchisato",
    iwaki: "iwaki",
    kusano: "kusano",
    yotsukura: "yotsukura",
    kunohama: "kunohama",
    suetsugi: "suetsugi",
    hirono: "hirono",
    j_village: "j_village",
    kido: "kido",
    tatsuta: "tatsuta",
    tomioka: "tomioka",
    yorunomori: "yorunomori",
    ono: "ono",
    futaba: "futaba",
    namie: "namie",
    momouchi: "momouchi",
    odaka: "odaka",
    iwaki_ota: "iwaki_ota",
    haranocho: "haranocho",
    kashima: "kashima",
    nittaki: "nittaki",
    soma: "soma",
    komagamine: "komagamine",
    shinchi: "shinchi",
    sakamoto: "sakamoto",
    yamashita: "yamashita",
    hamayoshida: "hamayoshida",
    watari: "watari",
    okuma: "okuma",
    iwanuma: "iwanuma",
    // 川越線(JA)
    nisshin: 'nisshin',
    nishi_omiya: 'nishi-omiya',
    sashiougi: 'sashiougi',
    minami_furuya: 'minami-furuya',
    kawagoe: 'kawagoe',
    nishi_kawagoe: 'nishi-kawagoe',
    matoba: 'matoba',
    kasahata: 'kasahata',
    musashi_takahagi: 'musashi-takahagi',
    komagawa: 'komagawa',
    // 総武線(JB)
    higashinakano: 'higashinakano',
    okubo: 'okubo',
    sendagaya: 'sendagaya',
    shinanomachi: 'shinanomachi',
    ichigaya: 'ichigaya',
    iidabashi: 'iidabashi',
    suidoubashi: 'suidobashi',
    asakusabashi: 'asakusabashi',
    ryogoku: 'ryogoku',
    kinshicho: 'kinshicho',
    kameido: 'kameido',
    hirai: 'hirai',
    shinkoiwa: 'shinkoiwa',
    koiwa: 'koiwa',
    ichikawa: 'ichikawa',
    motoyawata: 'motoyawata',
    shimousa_nakayama: 'shimousa-nakayama',
    nishifunabashi: 'nishifunabashi',
    funabashi: 'funabashi',
    nishihunabashi: 'nishihunabashi',
    higashi_funabashi: 'higashi-funabashi',
    tsudanuma: 'tsudanuma',
    makuharihongou: 'makuharihongou',
    makuhari: 'makuhari',
    shinkemigawa: 'shinkemigawa',
    inage: 'inage',
    nishichiba: 'nishichiba',
    chiba: 'chiba',
    bakurocho: 'bakurocho',
    shinnihonbashi: 'shinnihonbashi',
    // 中央線(JC)
    ochanomizu: 'ochanomizu',
    yotsuya: 'yotsuya',
    nakano: 'nakano',
    kouenji: 'kouenji',
    asagaya: 'asagaya',
    ogikubo: 'ogikubo',
    nishiogikubo: 'nishiogikubo',
    kichijoji: 'kichijoji',
    mitaka: 'mitaka',
    musashisakai: 'musashisakai',
    higashikoganei: 'higashikoganei',
    musashikoganei: 'musashikoganei',
    kokubunji: 'kokubunji',
    nishikokubunji: 'nishikokubunji',
    kunitachi: 'kunitachi',
    tachikawa: 'tachikawa',
    hino: 'hino',
    toyoda: 'toyoda',
    nishihachiouji: "nishihachiouji",
    takao: 'takao',
    // 相模線(JG)
    kita_chigasaki: 'jr-east-kita-chigasaki',
    kagawa: 'jr-east-kagawa',
    samukawa: 'jr-east-samukawa',
    miyayama: 'jr-east-miyayama',
    kurami: 'jr-east-kurami',
    kadosawabashi: 'jr-east-kadosawabashi',
    syake: 'jr-east-syake',
    ebina: 'jr-east-ebina',
    iriya: 'jr-east-iriya',
    soubudai_shita: 'jr-east-soubudai-shita',
    shimomizo: 'jr-east-shimomizo',
    harataima: 'jr-east-harataima',
    banda: 'jr-east-banda',
    kamimizo: 'jr-east-kamimizo',
    minami_hashimoto: 'jr-east-minami-hashimoto',
    // 鶴見線(JI)
    tsurumi: 'jr-east-tsurumi',
    kokudou: 'jr-east-kokudou',
    tsurumi_ono: 'jr-east-tsurumi-ono',
    bentenbashi: 'jr-east-bentenbashi',
    asano: 'jr-east-asano',
    anzen: 'jr-east-anzen',
    musashi_shiraishi: 'jr-east-musashi-shiraishi',
    shouwa: 'jr-east-shouwa',
    ougimachi: 'jr-east-ougimachi',
    shin_shibaura: 'jr-east-shin-shibaura',
    umi_shibaura: 'jr-east-umi-shibaura',
    okawa: 'jr-east-okawa',
    // 京葉線(JK)
    futamata_shinmachi: 'jr-east-futamata-shinmachi',
    shin_urayasu: "shin_urayasu",
    maihama: "maihama",
    kasai_rinkai_koen: "kasai_rinkai_koen",
    shiomi: "shiomi",
    ecchujima: "ecchujima",
    hacchobori: "hacchobori",
    shin_narashino: "shin_narashino",
    makuhari_toyosuna: "makuhari_toyosuna",
    kaihin_makuhari: "kaihin_makuhari",
    kemigawahama: "jr-east-kemigawahama",
    inage_kaigan: "inage_kaigan",
    chiba_minato: "chiba_minato",
    soga: "soga",
    // 八高線(JW)
    kita_hachiouji: 'jr-east-kita-hachiouji',
    komiya: 'jr-east-komiya',
    haijima: 'jr-east-haijima',
    higashi_fussa: 'jr-east-higashi-fussa',
    hakonegasaki: 'jr-east-hakonegasaki',
    kaneko: 'jr-east-kaneko',
    higashi_hanno: 'jr-east-higashi-hanno',
    moro: 'jr-east-moro',
    ogose: 'jr-east-ogose',
    myougaku: 'jr-east-myougaku',
    ogawamachi: 'jr-east-ogawamachi',
    takezawa: 'jr-east-takezawa',
    orihara: 'jr-east-orihara',
    yorii: 'jr-east-yorii',
    youdo: 'jr-east-youdo',
    matsuhisa: 'jr-east-matsuhisa',
    kodama: 'jr-east-kodama',
    tanshou: 'jr-east-tanshou',
    gunma_fujioka: 'jr-east-gunma-fujioka',
    kita_fujioka: 'jr-east-kita-fujioka',
    // 宇都宮線
    omiya: 'o-miya',
    saitama_shintoshin: 'saitama-shintoshin',
    yono: 'yono',
    kitaurawa: 'kitaurawa',
    urawa: 'urawa',
    minami_urawa: 'minami-urawa',
    warabi: 'warabi',
    nishikawaguchi: 'nishikawaguchi',
    kawaguti: 'kawaguchi',
    akahane: 'akahane',
    higashijujo: 'higashi-jujo',
    ouji: 'ouji',
    kaminakazato: 'kaminakazato',
    tabata: 'tabata',
    nishinippori: 'nishinippori',
    nippori: 'nippori',
    uguisudani: 'uguisudani',
    ueno: 'ueno',
    okachimachi: 'okachimachi',
    akihabara: 'akihabara',
    kanda: 'kanda',
    tokyo: 'tokyo',
    yurakucho: 'yurakucho',
    shinjuku: 'shinjuku',
    hamamatsucho: 'hamamatsucho',
    tamachi: 'tamachi',
    takanawa_gateway: 'takanawa-gateway',
    shinagawa: 'shinagawa',
    oimachi: 'oimachi',
    omori: 'omori',
    kamata: 'kamata',
    kawasaki: 'kawasaki',
    shinkoyasu: 'shinkoyasu',
    higashikanagawa: 'higashi-kanagawa',
    yokohama: 'yokohama',
    shinbashi: 'shinbashi',
    komagome: 'komagome',
    sugamo: 'sugamo',
    otsuka: 'otsuka',
    ikebukuro: 'ikebukuro',
    itabashi: 'itabashi',
    jujo: 'jujo',
    kitaakahane: 'kita-akahane',
    ukimafunado: 'ukima-funado',
    todakouen: 'todakouen',
    toda: 'toda',
    kitatoda: 'kitatoda',
    musashiurawa: 'musashiurawa',
    nakaurawa: 'nakaurawa',
    minamiyono: "minamiyono",
    yonohonmachi: "yonohonmachi",
    kitayono: "kitayono",
    mejiro: 'mejiro',
    takadanobaba: 'takadanobaba',
    shinokubo: 'shinokubo',
    yoyogi: 'yoyogi',
    harajuku: 'harajuku',
    shibuya: 'shibuya',
    ebisu: 'ebisu',
    meguro: 'meguro',
    gotanda: 'gotanda',
    osaki: 'osaki',
    hachiouji: 'hachiouji',
    katakura: 'katakura',
    hachiouji_minamino: 'hachiouji-minamino',
    aihara: 'aihara',
    hashimoto: 'hashimoto',
    sagamihara: 'sagamihara',
    huchinobe: 'huchinobe',
    kobuchi: 'kobuchi',
    machida: 'machida',
    naruse: 'naruse',
    nagatsuta: 'nagatsuta',
    tokaichiba: 'tokaichiba',
    nakayama: 'nakayama',
    kamoi: 'kamoi',
    kodukue: 'kodukue',
    shin_yokohama: 'shin_yokohama',
    kikuna: 'kikuna',
    oguchi: 'oguchi',
    higashi_kanagawa: 'higashi-kanagawa',
    sakuragicho: 'sakuragicho',
    kannai: 'kannai',
    ishikawacho: 'ishikawacho',
    yamate: 'yamate',
    negishi: 'negishi',
    isogo: 'isogo',
    shin_sugita: 'shin-sugita',
    youkoudai: 'youkoudai',
    kounandai: 'kounandai',
    hongoudai: 'hongoudai',
    ofuna: 'ofuna',
    totsuka: 'totsuka',
    hujisawa: 'hujisawa',
    tsujido: 'tsujido',
    chigasaki: 'chigasaki',
    hiratsuka: 'hiratsuka',
    oiso: 'oiso',
    ninomiya: 'ninomiya',
    kozu: 'kozu',
    kamonomiya: 'kamonomiya',
    odawara: 'odawara',
    hayakawa: "hayakawa",
    nebukawa: "nebukawa",
    manazuru: "manazuru",
    yugawara: 'yugawara',
    atami: 'atami',

    // 高崎線
    oku: 'oku',
    miyahara: 'miyahara',
    ageo: 'ageo',
    kitaageo: 'kitaageo',
    okegawa: 'okegawa',
    kitamoto: 'kitamoto',
    kounosu: 'kounosu',
    kitakounosu: 'kitakounosu',
    hukiage: 'hukiage',
    gyouda: 'gyouda',
    kumagaya : 'kumagaya',
    kagohara : 'kagohara',
    hukaya : 'hukaya',
    okabe : 'okabe',
    honnjou: 'honnjou',
    jinbohara: 'jinbohara',
    maebashi: 'maebashi',
    shinmachi: 'sinmachi',
    kuragano: 'kuragano',
    takasaki: 'takasaki',
    // 湘南新宿ライン
    utsunomiya: 'utsunomiya',
    suzumenomiya: 'suzumenomiya',
    ishibashi: 'ishibashi',
    jichiidai: 'jichiidai',
    koganei: 'koganei',
    oyama: 'oyama',
    mamada: 'mamada',
    nogi: 'nogi',
    koga: 'koga',
    kurihashi: 'kurihashi',
    higashiwashinomiya: 'higashiwashinomiya',
    kuki: 'kuki',
    shinshiraoka: 'shinshiraoka',
    shiraoka: 'shiraoka',
    hasuda: 'hasuda',
    higashiomiya: 'higashiomiya',
    toro: 'toro',
    maehashi: 'maehashi',
    shinmaebashi: 'shinmaebashi',
    ino: 'ino',
    takasakitonyamachi: 'takasaki-tonyamachi',
    nishioi: "nishioi",
    musashi_kosugi: "musashi_kosugi",
    shinkawasaki: "shinkawasaki",
    hodogaya: "hodogaya",
    higashitotsuka: "higashitotsuka",
    kitakamakura: "kitakamakura",
    kamakura: "kamakura",
    zushi: "zushi",
    nishinasuno: "nishinasuno",
    // 武蔵野線
    fuchuhonmachi: 'fuchuhonmachi',
    kitafuchu: 'kitafuchu',
    shinkohira: 'shinkohira',
    shinakitsu: 'shinakitsu',
    higashi_tokorozawa: "higashi_tokorozawa",
    shinza: "shinza",
    kita_asaka: "kita_asaka",
    nishi_urawa: "nishi_urawa",
    musashi_urawa: "musashi_urawa",
    higashi_urawa: "higashi_urawa",
    higashi_kawaguchi: "higashi_kawaguchi",
    minami_koshigaya: "minami_koshigaya",
    koshigaya_laketown: "koshigaya_laketown",
    yoshikawa: "yoshikawa",
    yoshikawa_minami: "yoshikawa_minami",
    shin_sango: "shinsango",
    sango: "sango",
    shin_yahashira: "shin_yahashira",
    ichikawa_ono: "ichikawa_ono",
    funabashi_houden: "funabashi_hoden",
    nishi_funabashi: "nishi_funabashi",
    minami_funabashi: "minami_funabashi",
    ichikawa_shiohama: "ichikawa_shiohama",

    // 横須賀線
    higashizushi: 'higashizushi',
    taura: 'taura',
    yokosuka: 'yokosuka',
    kinugasa: 'kinugasa',
    kurihama: 'kurihama',

    // 相模線
    atsugi: "atsugi",

    // 宇都宮線
    doro: 'doro',
    okamoto: 'okamoto',
    housyakuji: 'housyakuji',
    ujiie: 'ujiie',
    kamasusaka: 'kamasusaka',
    kataoka: 'kataoka',
    yaita: 'yaita',
    nozaki: 'nozaki',
    nishisunano: 'nishisunano',
    kuroiso: 'kuroiso',
    //武蔵野線(JM)
    huchuhonmachi: 'huchuhonmachi',
    kitahuchu: 'kitahuchu',
    minamiurawa: "minamiurawa",
    higashiurawa: "higashiurawa",
    higashikawaguchi: "higashikawaguchi",
    minamikoshigaya: "minamikoshigaya",
    minami_nagareyama: "minami_nagareyama",
    yoshikawaminami: "yoshikawaminami",
    minaminagareyama: "minaminagareyama",
    shinmatsudo: "shinmatsudo",
    shinyahashira: "shinyahashira",
    higashi_matsudo: "higash_imatsudo",
    ichikawaono: "ichikawaono",
    hunabashihouten: "hunabashihouten",
    minamihunabashi: "minamihunabashi",
    ichikawashiohama: "ichikawashiohama",
    shinurayasu: "shinurayasu",
    kasairinkaikouen: "kasairinkaikouen",
    shinkiba: "shinkiba",
    hacchoubori: "hacchoubori",
    //南武線(JN)
    hamakawasaki: "hamakawasaki",
    odasakae: "odasakae",
    kawasakichinmachi: "kawasakichinmachi",
    shitte: "shitte",
    yakou: "yakou",
    kashimada: "kashimada",
    hirama: "hirama",
    mukougawara: "mukougawara",
    mizonokuchi: "mizonokuchi",
    musashinakahara: "musashinakahara",
    musashishinjou: "musashishinjou",
    musashimizonokuchi: "musashimizonokuchi",
    tsudayama: "tsudayama",
    kuji: "kuji",
    syukugawara: "syukugawara",
    noto: "noto",
    nakanojima: "nakanojima",
    inadatsutsumi: "inadatsutsumi",
    yanoguchi: "yanoguchi",
    inaginaganuma: "inaginaganuma",
    minamitama: "minamitama",
    bubaigawara: "bubaigawara",
    nishifu: "nishifu",
    yaho: "yaho",
    yakawa: "yakawa",
    nishikunitachi: "nishikunitachi",
    noborito: "noborito",
    // 南武支線
    kawasaki_shinmachi: "kawasaki_shinmachi",
    // 総武本線(JO)
    nishi_chiba: 'jr-east-nishi_chiba',
    higashi_chiba: 'jr-east-higashi_chiba',
    tsuga: 'jr-east-tsuga',
    yotsukaidou: 'jr-east-yotsukaidou',
    monoi: 'jr-east-monoi',
    sakura: 'jr-east-sakura',
    minami_shisui: 'jr-east-minami_shisui',
    enokido: 'jr-east-enokido',
    yachimata: 'jr-east-yachimata',
    hyuga: 'jr-east-hyuga',
    narutou: 'jr-east-narutou',
    matsuo: 'jr-east-matsuo',
    yokoshiba: 'jr-east-yokoshiba',
    iigura: 'jr-east-iigura',
    youkaichiba: 'jr-east-youkaichiba',
    higata: 'jr-east-higata',
    asahi: 'jr-east-asahi',
    iioka: 'jr-east-iioka',
    kurahashi: 'jr-east-kurahashi',
    saruda: 'jr-east-saruda',
    matsugishi: 'jr-east-matsugishi',
    choshi: 'jr-east-choshi',

    // 東北本線
    takaku: 'jr-east-takaku',
    kurotawara: 'jr-east-kurotawara',
    toyohara: 'jr-east-toyohara',
    shirasaka: 'jr-east-shirasaka',
    shirakawa: 'jr-east-shirakawa',
    kudano: 'jr-east-kudano',
    izumizaki: 'jr-east-izumizaki',
    yabuki: 'jr-east-yabuki',
    kagamiishi: 'jr-east-kagamiishi',
    sukagawa: 'jr-east-sukagawa',
    asakanagamori: 'jr-east-asakanagamori',
    hiwada: 'jr-east-hiwada',
    gohyakugawa: 'jr-east-gohyakugawa',
    motomiya: 'jr-east-motomiya',
    sugita: 'jr-east-sugita',
    nihonmatsu: 'jr-east-nihonmatsu',
    adachi: 'jr-east-adachi',
    matsukawa: 'jr-east-matsukawa',
    kanayagawa: 'jr-east-kanayagawa',
    minami_fukushima: 'jr-east-minami-fukushima',
    higashi_fukushima: 'jr-east-higashi-fukushima',
    date: 'jr-east-date',
    kori: 'jr-east-kori',
    fujita: 'jr-east-fujita',
    kaida: 'jr-east-kaida',
    kosugou: 'jr-east-kosugou',
    shiraishi: 'jr-east-shiraishi',
    higashi_shiraishi: 'jr-east-higashi-shiraishi',
    kita_shirakawa: 'jr-east-kita-shirakawa',
    ogawara: 'jr-east-ogawara',
    funaoka: 'jr-east-funaoka',
    tsukinoki: 'jr-east-tsukinoki',
    tatekoshi: 'jr-east-tatekoshi',
    natori: 'jr-east-natori',
    minami_sendai: 'jr-east-minami-sendai',
    taishidou: 'jr-east-taishidou',
    nagamachi: 'jr-east-nagamachi',
    higashi_sendai: 'jr-east-higashi-sendai',
    iwakiri: 'jr-east-iwakiri',
    rikuzensannou: 'jr-east-rikuzensannou',
    kokufutagajou: 'jr-east-kokufutagajou',
    shiogama: 'jr-east-shiogama',
    matsushima: 'jr-east-matsushima',
    atago: 'jr-east-atago',
    shinainuma: 'jr-east-shinainuma',
    kashimadai: 'jr-east-kashimadai',
    matsuyamamachi: 'jr-east-matsuyamamachi',
    kogota: 'jr-east-kogota',
    tajiri: 'jr-east-tajiri',
    semine: 'jr-east-semine',
    umegasawa: 'jr-east-umegasawa',
    nitta: 'jr-east-nitta',
    ishikoshi: 'jr-east-ishikoshi',
    aburajima: 'jr-east-aburajima',
    hanaizumi: 'jr-east-hanaizumi',
    shimizuhara: 'jr-east-shimizuhara',
    arikabe: 'jr-east-arikabe',
    yamanome: 'jr-east-yamanome',
    hiraizumi: 'jr-east-hiraizumi',
    maezawa: 'jr-east-maezawa',
    rikuchuorii: 'jr-east-rikuchuorii',
    mizusawa: 'jr-east-mizusawa',
    kanegasaki: 'jr-east-kanegasaki',
    rokuhara: 'jr-east-rokuhara',
    murasakino: 'jr-east-murasakino',
    hanamaki: 'jr-east-hanamaki',
    hanamaki_kuko: 'jr-east-hanamaki-kuko',
    ishidoriya: 'jr-east-ishidoriya',
    hidume: 'jr-east-hidume',
    shiwa_chuo: 'jr-east-shiwa-chuo',
    furudate: 'jr-east-furudate',
    yahaba: 'jr-east-yahaba',
    iwate_iioka: 'jr-east-iwate-iioka',
    senbokumachi: 'jr-east-senbokumachi',

    // 両毛線
    shin_maebashi: 'jr-east-shin_maebashi',
    maebashi_oshima: 'jr-east-maebashi_oshima',
    komagata: 'jr-east-komagata',
    isezaki: 'jr-east-isezaki',
    kunisada: 'jr-east-kunisada',
    iwayado: 'jr-east-iwayado',
    kiryu: 'jr-east-kiryu',
    omata: 'jr-east-omata',
    yamamae: 'jr-east-yamamae',
    ashikaga: 'jr-east-ashikaga',
    ashikaga_flower_park: 'jr-east-ashikaga_flower_park',
    tomita: 'jr-east-tomita',
    sano: 'jr-east-sano',
    iwahune: 'jr-east-iwahune',
    ohirashita: 'jr-east-ohirashita',
    tochigi: 'jr-east-tochigi',
    omoigawa: 'jr-east-omoigawa',
    // 水戸線
    odabayashi: 'jr-east-odabayashi',
    yuki: 'jr-east-yuki',
    higashi_yuki: 'jr-east-higashi_yuki',
    kawashima: 'jr-east-kawashima',
    tamado: 'jr-east-tamado',
    shimodate: 'jr-east-shimodate',
    niibari: 'jr-east-niibari',
    yamato: 'jr-east-yamato',
    iwase: 'jr-east-iwase',
    haguro: 'jr-east-haguro',
    fukuhara: 'jr-east-fukuhara',
    inada: 'jr-east-inada',
    kasama: 'jr-east-kasama',
    shishido: 'jr-east-shishido',
    // 上越線
    gunmasousya: 'jr-east-gunmasousya',
    yagihara: 'jr-east-yagihara',
    shibukawa: 'jr-east-shibukawa',
    sikishima: 'jr-east-sikishima',
    tsukuda: 'jr-east-tsukuda',
    iwamoto: 'jr-east-iwamoto',
    numata: 'jr-east-numata',
    gokan: 'jr-east-gokan',
    kamimoku: 'jr-east-kamimoku',
    minakami: 'jr-east-minakami',
    yubiso: 'jr-east-yubiso',
    doai: 'jr-east-doai',
    tsuchitaru: 'jr-east-tsuchitaru',
    echigo_nakazato: 'jr-east-echigo_nakazato',
    iwabara_skijoumae: 'jr-east-iwabara_skijoumae',
    ishiuchi: 'jr-east-ishiuchi',
    osawa: 'jr-east-osawa',
    jouetsu_kokusai_skijoumae: 'jr-east-jouetsu_kokusai_skijoumae',
    shiozawa: 'jr-east-shiozawa',
    muikamachi: 'jr-east-muikamachi',
    itsukamachi: 'jr-east-itsukamachi',
    yairo: 'jr-east-yairo',
    koide: 'jr-east-koide',
    echigo_horinouchi: 'jr-east-echigo_horinouchi',
    kita_horinouchi: 'jr-east-kita_horinouchi',
    echigo_kawaguchi: 'jr-east-echigo_kawaguchi',
    odiya: 'jr-east-odiya',
    echigo_takiya: 'jr-east-echigo_takiya',
    miyauchi: 'jr-east-miyauchi',
    // 吾妻線
    kanashima: 'jr-east-kanashima',
    soboshima: 'jr-east-soboshima',
    onokami: 'jr-east-onokami',
    onokami_onsen: 'jr-east-onokami_onsen',
    ichishiro: 'jr-east-ichishiro',
    nakanojou: 'jr-east-nakanojo',
    gunma_haramachi: 'jr-east-gunma-haramachi',
    tougen: 'jr-east-tougen',
    yakura: 'jr-east-yakura',
    iwashima: 'jr-east-iwashima',
    kawaharayu_onsen: 'jr-east-kawaharayu_onsen',
    naganohara_kusatsuguchi: 'jr-east-naganohara_kusatsuguchi',
    gunma_otsu: 'jr-east-gunma-otsu',
    haneo: 'jr-east-haneo',
    fukurogura: 'jr-east-fukurogura',
    manza_kazawaguchi: 'jr-east-manza_kazawa-guchi',
    omae: 'jr-east-omae',
    // 只見線
    aidu_wakamatsu: 'jr-east-aidu_wakamatsu',
    nanokachou: 'jr-east-nanokachou',
    nishi_wakamatsu: 'jr-east-nishi_wakamatsu',
    aidu_hongou: 'jr-east-aidu_hongou',
    aidu_takada: 'jr-east-aidu_takada',
    niitsuru: 'jr-east-niitsuru',
    wakamiya: 'jr-east-wakamiya',
    aidu_sakashita: 'jr-east-aidu_sakashita',
    toudera: 'jr-east-toudera',
    aidu_sakamoto: 'jr-east-aidu_sakamoto',
    aidu_yanaidu: 'jr-east-aidu_yanaidu',
    goudo: 'jr-east-goudo',
    takiya: 'jr-east-takiya',
    aidu_ehara: 'jr-east-aidu_ehara',
    aidu_nishikata: 'jr-east-aidu_nishikata',
    aidu_miyashita: 'jr-east-aidu_miyashita',
    hayado: 'jr-east-hayado',
    aidu_mizunuma: 'jr-east-aidu_mizunuma',
    aidu_nakagawa: 'jr-east-aidu_nakagawa',
    aidu_kawaguchi: 'jr-east-aidu_kawaguchi',
    honna: 'jr-east-honna',
    aidu_kosugawa: 'jr-east-aidu_kosugawa',
    aidu_yokota: 'jr-east-aidu_yokota',
    aidu_oshio: 'jr-east-aidu_oshio',
    aidu_shiozawa: 'jr-east-aidu_shiozawa',
    aidu_gamou: 'jr-east-aidu_gamou',
    tadami: 'jr-east-tadami',
    oshirakawa: 'jr-east-osirakawa',
    irihirose: 'jr-east-irihirose',
    kamijou: 'jr-east-kamijou',
    echigosuhara: 'jr-east-echigosuhara',
    uonumatanaka: 'jr-east-uonumatanaka',
    echigo_hirose: 'jr-east-echigo_hirose',
    yabukami: 'jr-east-yabukami',
    // 飯山線
    toyono: 'jr-east-toyono',
    shinano_asaano: 'jr-east-shinano_asaano',
    tategahana: 'jr-east-tategahana',
    kami_imai: 'jr-east-kami_imai',
    kaesa: 'jr-east-kaesa',
    hasu: 'jr-east-hasu',
    iiyama: 'jr-east-iiyama',
    kita_iiyama: 'jr-east-kita_iiyama',
    shinanodaira: 'jr-east-shinanodaira',
    togarinozawa_onsen: 'jr-east-togarinozawa_onsen',
    kamisakai: 'jr-east-kamisakai',
    kami_kuwanagawa: 'jr-east-kami_kuwanagawa',
    kuwanagawa: 'jr-east-kuwanagawa',
    nishi_otaki: 'jr-east-nishi_otaki',
    shinano_shiratori: 'jr-east-shinano_shiratori',
    hirataki: 'jr-east-hirataki',
    yokokura: 'jr-east-yokokura',
    morimiyanohara: 'jr-east-morimiyanohara',
    ashidaki: 'jr-east-ashidaki',
    echigo_tanaka: 'jr-east-echigo_tanaka',
    tsunan: 'jr-east-tsunan',
    echigo_shikawatari: 'jr-east-echigo_shikawatari',
    echigo_tazawa: 'jr-east-echigo_tazawa',
    echigo_mizusawa: 'jr-east-echigo_mizusawa',
    doichi: 'jr-east-doichi',
    tookaichi: 'jr-east-tookaichi',
    uonumanakajou: 'jr-east-uonumanakajou',
    shimojou: 'jr-east-shimojou',
    echigo_iwasawa: 'jr-east-echigo_iwasawa',
    uchigamaki: 'jr-east-uchigamaki',
    // 信越本線
    naoetsu: 'jr-east-naoetsu',
    kuroi: 'jr-east-kuroi',
    saigata: 'jr-east-saigata',
    dosokohama: 'jr-east-dosokohama',
    katamachi: 'jr-east-katamachi',
    jougehama: 'jr-east-jougehama',
    kakizaki: 'jr-east-kakizaki',
    yoneyama: 'jr-east-yoneyama',
    kasajima: 'jr-east-kasajima',
    oumigawa: 'jr-east-oumigawa',
    kujiranami: 'jr-east-kujiranami',
    ibarame: 'jr-east-ibarame',
    yasuda: 'jr-east-yasuda',
    houjou: 'jr-east-houjou',
    echigo_hirota: 'jr-east-echigo_hirota',
    nagatori: 'jr-east-nagatori',
    tsukayama: 'jr-east-tsukayama',
    echigo_iwatsuka: 'jr-east-echigo_iwatsuka',
    raikouji: 'jr-east-raikouji',
    maekawa: 'jr-east-maekawa',

    //上越新幹線
    honjo_waseda: "honjo_waseda",
    joumoukougen: "joumoukougen",
    echigo_yuzawa: "echigo_yuzawa",
    gala_yuzawa: "gala-yuzawa",
    urasa: "urasa",
    nagaoka: "nagaoka",
    tsubame_sanjo: "tsubame-sanjo",
    niigata: "niigata",
    // 東北新幹線
    nasu_shiobara: "jr-nasu_shiobara",
    shin_shirakawa: "jr-shin_shirakawa",
    kooriyama: "jr-kooriyama",
    fukushima: "jr-fukushima",
    shiroishi_zao: "jr-shiroishi_zao",
    sendai: "jr-sendai",
    furukawa: "jr-furukawa",
    kurikoma_kogen: "jr-kurikoma_kogen",
    ichinoseki: "jr-ichinoseki",
    mizusawaesashi: "jr-mizusawaesashi",
    kitakami: "jr-kitakami",
    shin_hanamaki: "jr-shin_hanamaki",
    morioka: "jr-morioka",
    iwate_numakunai: "jr-iwate_numakunai",
    ninohe: "jr-ninohe",
    hachinohe: "jr-hachinohe",
    shichinohe_towada: "jr-shichinohe_towada",
    shin_aomori: "jr-shin_aomori",
    // 山形新幹線
    shinjo: "jr-shinjo",
    oishida: "jr-oishida",
    murayama: "jr-murayama",
    sakuranbo_higashine: "jr-sakuranbo_higashine",
    tendo: "jr-tendo",
    yamagata : "jr-yamagata",
    kaminoyama_onsen: "jr-kaminoyama_onsen",
    akayu: "jr-akayu",
    takahata: "jr-takahata",
    yonezawa: "jr-yonezawa",
    // 秋田新幹線
    shizukuishi: "jr-shizukuishi",
    tazawako: "jr-tazawako",
    kakunodate: "jr-kakunodate",
    omagari: "jr-omagari",
    akita: "jr-akita",
    // 北陸新幹線
    annaka_haruna: "jr-annaka_haruna",
    karuizawa: "jr-karuizawa",
    sakudaira: "jr-sakudaira",
    nagano: "jr-nagano",
    joetsu_myoko: "jr-joetsu_myoko",
    // 北海道新幹線
    oku_tsugaru_imabetsu: "jr-okutsugaru_imabetsu",

    duplicate: {
      fukushima: {
        /** 植田 */
        ueda: "ueda",
        negishi: "negishi",
      },
      kanagawa: {
        negishi: "negishi",
      },
      nagano: {
        /** 上田 */
        ueda: "ueda",
      }
    }
  },

  /** 臨海高速鉄道 */
  toukyo_rinkai_kousoku: {
    shinonome: 'rinkai-shinonome',
    kokusaitenjijyo: 'rinkai-kokusaitenjijyo',
    tokyo_teleport: 'rinkai-tokyo-teleport',
    shinagawa_seaside: 'rinkai-shinagawa-seaside',
  },

  /** 小田急箱根 駅*/
  odakyu_hakone: {
    // 鋼索線
    kouenshimo: 'odakyu-hakone-kouenshimo',
    kouenkami: 'odakyu-hakone-kouenkami',
    naka_goura: 'odakyu-hakone-naka-goura',
    kami_goura: 'odakyu-hakone-kami_goura',
    souunzan: 'hakone-ropeway-souunzan',
    // 箱根ロープウェイ
    owakudani: 'hakone-ropeway-owakudani',
    ubako: 'hakone-ropeway-ubako',
    tougendai: 'hakone-tougendai',
  },



  /** 横浜高速 駅 */
  yokohama_kousoku: {
    shin_takashima: "yokohama-kousoku-shin-takashima",
    minato_mirai: "yokohama-kousoku-minato-mirai",
    basyamichi: "yokohama-kousoku-basyamichi",
    nihon_odori: "yokohama-kousoku-nihon-odori",
    motomachi_chukagai: "yokohama-kousoku-motomachi-chukagai",
  },
  /** 東武 駅 */
  tobu: {
    // 東武東上線
    kita_ikebukuro: "tobu-kita-ikebukuro",
    shimoitabashi: "tobu-shimoitabashi",
    oyama: "tobu-oyama",
    nakaitabashi: "tobu-nakaitabashi",
    tokiwadai: "tobu-tokiwadai",
    kamiitabashi: "tobu-kamiitabashi",
    toubu_nerima: "tobu-toubu-nerima",
    shimoakatsuka: "tobu-shimoakatsuka",
    narimasu: "tobu-narimasu",
    asaka: "tobu-asaka",
    asakadai: "tobu-asakadai",
    shigi: "tobu-shigi",
    yanasegawa: "tobu-yanasegawa",
    mizuhodai: "tobu-mizuhodai",
    tsuruse: "tobu-tsuruse",
    fujimino: "tobu-fujimino",
    kamihukuoka: "tobu-kamihukuoka",
    shinkawagashi: "tobu-shinkawagashi",
    kawagoeshi: "tobu-kawagoeshi",
    kasumigaseki: "tobu-kasumigaseki",
    tsurugashima: "tobu-tsurugashima",
    wakaba: "tobu-wakaba",
    sakato: "tobu-sakato",
    kita_sakato: "tobu-kita-sakato",
    kousaka: "tobu-kousaka",
    higashi_matsuyama: "tobu-higashi-matsuyama",
    shinrin_koen: "tobu-shinrin-koen",
    tsukinowa: "tobu-tsukinowa",
    musashi_arashiyama: "tobu-musashi-arashiyama",
    ogawamachi: "tobu-ogawamachi",
    tobu_takezawa: "tobu-tobu-takezawa",
    minami_yorii: "tobu-minami-yorii",
    dankin: "tobu-dankin",
    hachigata: "tobu-hachigata",
    tamayodo: "tobu-tamayodo",
    yorii: "tobu-yorii",
    // アーバンパークライン
    kita_omiya: "tobu-kita-omiya",
    omiya_koen: "tobu-omiya-koen",
    owada: "tobu-owada",
    nanasato: "tobu-nanasato",
    iwatsuki: "tobu-iwatsuki",
    higashi_iwatsuki: "tobu-higashi-iwatsuki",
    toyoharu: "tobu-toyoharu",
    yagisaki: "tobu-yagisaki",
    kasukabe: "tobu-kasukabe",
    fujinoushijima: "tobu-fujinoushijima",
    minami_sakurai: "tobu-minami-sakurai",
    kawama: "tobu-kawama",
    nanakoudai: "tobu-nanakoudai",
    shimizu_koen: "tobu-shimizu-koen",
    atago: "tobu-atago",
    nodashi: "tobu-nodashi",
    umesato: "tobu-umesato",
    unga: "tobu-unga",
    edogawadai: "tobu-edogawadai",
    hatsuishi: "tobu-hatsuishi",
    toyoshiki: "tobu-toyoshiki",
    shin_kashiwa: "tobu-shin-kashiwa",
    masuo: "tobu-masuo",
    sakasai: "tobu-sakasai",
    takayanagi: "tobu-takayanagi",
    mutsumi: "tobu-mutsumi",
    kamagaya: "tobu-kamagaya",
    magomesawa: "tobu-magomesawa",
    tsukada: "tobu-tsukada",
    shin_funabashi: "tobu-shin-funabashi",
    // 東葉高速線
    higashi_kaijin: "tobu-higashi-kaijin",
    hasama: "tobu-hasama",
    kita_narashino: "tobu-kita-narashino",
    funabashi_nichidaimae: "tobu-funabashi-nichidaimae",
    yachiyo_midorigaoka: "tobu-yachiyo-midorigaoka",
    yachiyo_chuou: "tobu-yachiyo-chuou",
    murakami: "tobu-murakami",
    touyou_katsutadai: "tobu-touyou-katsutadai",
  },
  /** 西部駅 */
  seibu: {
    // 西武池袋線
    shiinamachi: "shiinamachi",
    higashi_nagasaki: "higashi-nagasaki",
    ekoda: "ekoda",
    sakuradai: "sakuradai",
    nerima: "nerima",
    nakamurabashi: "nakamurabashi",
    fujimidai: "fujimidai",
    nerima_takanodai: "nerima-takanodai",
    syakujiikoen: "syakujiikoen",
    oizumi_gakuen: "oizumi-gakuen",
    hoya: "hoya",
    hibarigaoka: "hibarigaoka",
    higashi_kurume: "higashi-kurume",
    kiyose: "kiyose",
    akitsu: "akitsu",
    tokorozawa: "tokorozawa",
    nishi_tokorozawa: "nishi-tokorozawa",
    kotesashi: "kotesashi",
    sayamagaoka: "sayamagaoka",
    musashi_fujisawa: "musashi-fujisawa",
    inariyamakoen: "inariyama-koen",
    irumashi: "irumashi",
    bushi: "bushi",
    motokaji: "motokaji",
    hanno: "hanno",
    // 新宿線
    seibu_shinjuku: "seibu-seibu-shinjuku",
    shimo_ochiai: "seibu-shimo-ochiai",
    arai_yakushimae: "seibu-arai-yakushimae",
    numabashi: "seibu-numabashi",
    nogata: "seibu-nogata",
    toritsu_kasei: "seibu-toritsu-kasei",
    washinomiya: "seibu-washinomiya",
    shimo_igusa: "seibu-shimo-igusa",
    iogi: "seibu-iogi",
    kami_igusa: "seibu-kami-igusa",
    kami_syakujii: "seibu-kami-syakujii",
    musashiseki: "seibu-musashiseki",
    higashi_fushimi: "seibu-higashi-fushimi",
    kodaira: "seibu-kodaira",
    higashi_murayama: "seibu-higashi-murayama",
    seibu_yazawa: "seibu-seibu-yazawa",
    tanashi: "seibu-tanashi",
    hana_koganei: "seibu-hana-koganei",
    kumegawa: "seibu-kumegawa",
    kuko_koen: "seibu-kuko-koen",
    shin_tokorozawa: "seibu-shin-tokorozawa",
    iriso: "seibu-iriso",
    sayamashi: "seibu-sayamashi",
    shin_sayama: "seibu-shin-sayama",
    minami_otsuka: "seibu-minami-otsuka",
    hon_kawagoe: "seibu-hon-kawagoe",
  },
  /** 京成駅 */
  keisei: {
    keisei_tsudanuma: "keisei-keisei-tsudanuma",
    shin_tsudanuma: "keisei-shin-tsudanuma",
    maehara: "keisei-maehara",
    yakuendai: "keisei-yakuendai",
    narashino: "keisei-narashino",
    kita_narashino: "keisei-kita-narashino",
    takanekido: "keisei-takanekido",
    takanekodan: "keisei-takanekodan",
    takifudo: "keisei-takifudo",
    misaki: "keisei-misaki",
    futawakodai: "keisei-futawa-kodai",
    kamagaya_daibutsu: "keisei-kamagaya-daibutsu",
    hatsutomi: "keisei-hatsutomi",
    shin_kamagaya: "keisei-shin-kamagaya",
    kita_hatsutomi: "keisei-kita-hatsutomi",
    kunugiyama: "keisei-kunugiyama",
    motoyama: "keisei-motoyama",
    goko: "keisei-goko",
    tokiwadaira: "keisei-tokiwadaira",
    yahashira: "keisei-yahashira",
    minoridai: "keisei-minoridai",
    matsuto_shinden: "keisei-matsuto-shinden",
    kami_hongo: "keisei-kami-hongo",
    matsuto: "keisei-matsuto",
    // 本線
    keisei_ueno: "keisei-keisei-ueno",
    shin_mikawashima: "keisei-shin-mikawashima",
    senju_ohashi: "keisei-senju-ohashi",
    keisei_sekiya: "keisei-sekiya",
    horikirisyobuen: "keise-horikirisyobuen",
    ohanadyaya: "keisei-ohanadyaya",
    aoto: "keisei-aoto",
    keisei_takasago: "keisei-keisei-takasago",
    keisei_koiwa: "keisei-keisei-koiwa",
    edogawa: "keisei-edogawa",
    kounodai: "keisei-kounodai",
    ichikawa_mama: "keisei-ichikawa-mama",
    sugano: "keisei-sugano",
    keisei_hachiman: "keisei-hachiman",
    onigoe: "keisei-onigoe",
    keisei_nakayama: "keisei-keisei-nakayama",
    higashi_nakayama: "keisei-higashi-nakayama",
    keisei_nishifuna: "keisei-keisei-nishifuna",
    kaijin: "keisei-kaijin",
    keisei_funabashi: "keisei-keisei-funabashi",
    daijingushita: "keisei-daijingushita",
    funabashi_keibajo: "keisei-funabashi-keibajo",
    yatsu: "keisei-yatsu",
    keisei_okubo: "keisei-keisei-okubo",
    mimomi: "keisei-mimomi",
    yachiyodai: "keisei-yachiyodai",
    keisei_towada: "keisei-keisei-towada",
    katsutadai: "keisei-ka-tsutadai",
    shidu: "keisei-shidu",
    yukarigaoka: "keisei-yukarigaoka",
    keisei_shirai: "keisei-keisei-shirai",
    keisei_sakura: "keisei-keisei-sakura",
    osakura: "keisei-osakura",
    keisei_shisui: "keisei-keisei-shisui",
    sougosandou: "keisei-sougosandou",
    koudunomori: "keisei-koudunomori",
    keisei_narita: "keisei-keisei-narita",
    kuko_daini_bill: "keisei-kuko-daini-bill",
    narita_kuko: "keisei-narita-kuko",
    // スカイアクセス
    higashi_matsudo: "keisei-higashi-matsudo",
    narita_yukawa: "keisei-narita-yukawa",
  },
  /** 北総鉄道 駅 */
  hokusou: {
    // 北総線
    inaba_nihon_idai: "hokusou-inaba-nihon-idai",
    inzai_makinohara: "hokusou-inzai-makinohara",
    chiba_newtown_chuo: "hokusou-chiba-newtown-chuo",
    komuro: "hokusou-komuro",
    shirai: "hokusou-shirai",
    nishi_shirai: "hokusou-nishi-shirai",
    omachi: "hokusou-omachi",
    matsuhidai: "hokusou-matsuhidai",
    akiyama: "hokusou-akiyama",
    kitakokubun: "hokusou-kitakokubun",
    yagiri: "hokusou-yagiri",
    shin_shibamata: "hokusou-shin-shibamata",
  },
  /** 京王 駅 */
  keio: {
    // 京王線
    sasatsuka: "keio-sasatsuka",
    daitabashi: "keio-daitabashi",
    meidaimae: "keio-meidaimae",
    shimotakaido: "keio-shimotakaido",
    sakurajosui: "keio-sakurajosui",
    kami_kitazawa: "keio-kami-kitazawa",
    yawatayama: "keio-yawatayama",
    roka_koen: "keio-roka-koen",
    chitose_karasuyama: "keio-chitose-karasuyama",
    senkawa: "keio-senkawa",
    tsutsujigaoka: "keio-tsutsujigaoka",
    sibasaki: "keio-sibasaki",
    kokuryo: "keio-kokuryo",
    fuda: "keio-fuda",
    chofu: "keio-chofu",
    nishi_chofu: "keio-nishi-chofu",
    tobitakyu: "keio-tobitakyu",
    musashinodai: "keio-musashinodai",
    tamareien: "keio-tamareien",
    higashi_fuchu: "keio-higashi-fuchu",
    fuchu: "keio-fuchu",
    nakakawahara: "keio-nakakawahara",
    seiseki_sakuragaoka: "keio-seiseki-sakuragaoka",
    mogusaen: "keio-mogusaen",
    takahatafudo: "keio-takahatafudo",
    minamidaira: "keio-minamidaira",
    hirayamajoshikoen: "keio-hira-yamajoshikoen",
    naganuma: "keio-naganuma",
    kitano: "keio-kitano",
    keio_hachioji: "keio-keio-hachioji",
    // 京王新線
    hatsudai: "keio-hatsudai",
    hatagaya: "keio-hata-gaya",
    // 井の頭線
    shinsen: "keio-shinsen",
    komaba_todaimae: "keio-komaba-todaimae",
    ikenoue: "keio-ikenoue",
    shindaita: "keio-shindaita",
    higashi_matsubara: "keio-higashi-matsubara",
    eifukucho: "keio-eifukucho",
    nishi_eifuku: "keio-nishi-eifuku",
    hamadayama: "keio-hamadayama",
    takaido: "keio-takaido",
    fujimigaoka: "keio-fujimigaoka",
    kugayama: "keio-kugayama",
    mitakadai: "keio-mitakadai",
    inokashirakoen: "keio-inokashirakoen",
    // 相模原線
    keiou_tamagawa: "keio-keiou-tamagawa",
    keiou_inadatutsumi: "keio-keiou-inadatutsumi",
    keiou_yomiuri_land: "keio-keiou-yomiuri-land",
    inagi: "keio-inagi",
    wakabadai: "keio-wakabadai",
    keiou_nagayama: "keio-keiou-nagayama",
    keiou_tama_center: "keio-keiou-tama-center",
    keiou_horinouchi: "keio-keiou-horinouchi",
    minami_osawa: "keio-minami-osawa",
    tamasakai: "keio-tamasakai",
  },
  /** 埼玉新都市交通 駅 */
  saitama_shintoshi_koutsu: {
    tetsudou_hakubutsukan: "saitama-shintoshi-koutsu-tetsudou-hakubutsukan",
    kamonomiya: "saitama-shintoshi-koutsu-kamonomiya",
    higashi_miyahara: "saitama-shintoshi-koutsu-higashi-miyahara",
    konba: "saitama-shintoshi-koutsu-konba",
    yosinohara: "saitama-shintoshi-koutsu-yosinohara",
    haraichi: "saitama-shintoshi-koutsu-haraichi",
    syounan: "saitama-shintoshi-koutsu-syounan",
    maruyama: "saitama-shintoshi-koutsu-maruyama",
    shiku: "saitama-shintoshi-koutsu-shiku",
    ina_chuou: "saitama-shintoshi-koutsu-ina-chuou",
    hanuki: "saitama-shintoshi-koutsu-hanuki",
    uchijuku: "saitama-shintoshi-koutsu-uchijuku",
  },
  // JR東海 駅
  jr_tokai: {
    mishima: "mishima",
    shinfuji: "jr-tokai-shinfuji",
    shizuoka: "shizuoka",
    kakegawa: "kakegawa",
    hamamatsu: "hamamatsu",
    toyohashi: "toyohashi",
    mikawaanjo: "mikawaanjo",
    nagoya: "nagoya",
    gifuhashima: "gifuhashima",
    maibara: "maibara",
    kyoto: "kyoto",
    shinosaka: "shin-osaka",
  },
  // JR西駅
  jr_west: {
    // 北陸新幹線
    itoigawa: "jr-itoigawa",
    kurobe_unaduki_onsen: "jr-kurobe_unaduki_onsen",
    toyama: "jr-toyama",
    shin_takaoka: "jr-shin_takaoka",
    kanazawa: "jr-kanazawa",
    komatsu: "jr-komatsu",
    kaga_onsen: "jr-kaga_onsen",
    awara_onsen: "jr-awara_onsen",
    fukui: "jr-fukui",
    echizen_takefu: "jr-echizen_takefu",
    tsuruga: "jr-tsuruga",
  },
  // 富山地鉄駅
  toyama_chiho: {
    unaduki_onsen: "toyama-chitetsu-unaduki_onsen",
    otozawa: "toyama-chitetsu-otozawa",
    uchiyama: "toyama-chitetsu-uchiyama",
    manamoto: "toyama-chitetsu-manamoto",
    shimotachi: "toyama-chitetsu-shimotachi",
    shimotachiguchi: "toyama-chitetsu-shimotachiguchi",
    urayama: "toyama-chitetsu-urayama",
    tochiya: "toyama-chitetsu-tochiya",
    wakaba: "toyama-chitetsu-wakaba",
    shitayama: "toyama-chitetsu-shitayama",
    shin_kurobe: "toyama-chitetsu-shin_kurobe",
    nagaya: "toyama-chitetsu-nagaya",
    ogyu: "toyama-chitetsu-ogyu",
    higashi_mikkaichi: "toyama-chitetsu-higashi_mikkaichi",
    dentetsu_kurobe: "toyama-chitetsu-dentetsu_kurobe",
    dentetsu_ishida: "toyama-chitetsu-dentetsu_ishida",
    kyoden: "toyama-chitetsu-kyoden",
    shin_uotsu: "toyama-chitetsu-shin_uotsu",
    dentetsu_uotsu: "toyama-chitetsu-dentetsu_uotsu",
    nishi_uotsu: "toyama-chitetsu-nishi_uotsu",
    ecchu_nakamura: "toyama-chitetsu-ecchu_nakamura",
    hayatsuki_kazumi: "toyama-chitetsu-hayatsukikazumi",
    hama_kazumi: "toyama-chitetsu-hama_kazumi",
    namekawa: "toyama-chitetsu-namekawa",
    naka_namerikawa: "toyama-chitetsu-naka_namerikawa",
    nishi_namerikawa: "toyama-chitetsu-nishi_namerikawa",
    nishi_kazumi: "toyama-chitetsu-nishi_kazumi",
    naka_kazumi: "toyama-chitetsu-naka_kazumi",
    shin_miyakawa: "toyama-chitetsu-shin_miyakawa",
    kamiichi: "toyama-chitetsu-kamiichi",
    shin_ainogi: "toyama-chitetsu-shin_ainogi",
    ainogi: "toyama-chitetsu-ainogi",
    ecchuizumi: "toyama-chitetsu-ecchuizumi",
    terada: "toyama-chitetsu-terada",
    ecchu_funabashi: "toyama-chitetsu-ecchu_funabashi",
    ecchu_sango: "toyama-chitetsu-ecchu_sango",
    ecchu_ebara: "toyama-chitetsu-ecchu_ebara",
    higashi_shinjo: "toyama-chitetsu-higashi_shinjo",
    shinjo_tanaka: "toyama-chitetsu-shinjo_tanaka",
    inarimachi: "toyama-chitetsu-inarima-chi",
    dentetsu_toyama: "toyama-chitetsu-dentetsu_toyama",
  },
  // 福井鉄道駅
  fukui: {
    // 福井鉄道線
    jinai_joshi_koko: "fukui-jinai-joshi-koko",
    fukuieki: "fukui-fukuieki",
    fukui_joushi_daimyomachi: "fukui-fukui-joushi-daimyomachi",
    asuwayama_koenguchi: "fukui-aswayama-koenguchi",
    shokokaigijo_mae: "fukui-shokokaigijo-mae",
  },
  /** 流鉄 */
  ryutetsu: {
    nagareyama: "ryutetsu-nagareyama",
    heiwadai: "ryutetsu-heiwadai",
    hiregasaki: "ryutetsu-hiregasaki",
    koganejoato: "ryutetsu-koganejoato",
    koya: "ryutetsu-koya",
    mahashi: "ryutetsu-mahashi",
  },
  /** 伊豆箱根鉄道 */
  izu_hakone: {
    // 大雄山線
    daiyuzan: "izu-hakone-daiyuzan",
    fuji_film_mae: "izu-hakone-fuji-film-mae",
    wadagahara: "izu-hakone-wadagahara",
    tsukahara: "izu-hakone-tsukahara",
    iwahara: "izu-hakone-iwahara",
    sagami_numata: "izu-hakone-sagami-numata",
    iidaoka: "izu-hakone-iidaoka",
    anabe: "izu-hakone-anabe",
    gohyakurakan: "izu-hakone-gohyakurakan",
    isaida: "izu-hakone-isaida",
    midoricho: "izu-hakone-midoricho",
    // 駿豆線
    mishima_hirokoji: "izu-hakone-mishima-hirokoji",
    mishima_tamachi: "izu-hakone-mishima-tamachi",
    mishima_futsukamachi: "izu-hakone-mishima-futsukamachi",
    daiba: "izu-hakone-daiba",
    haragi: "izu-hakone-haragi",
    izu_nita: "izu-hakone-izu-nita",
    nibiyama: "izu-hakone-nibiyama",
    izu_nagaoka: "izu-hakone-izu-nagaoka",
    takyou: "izu-hakone-takyou",
    ohito: "izu-hakone-ohito",
    makinokou: "izu-hakone-makinokou",
    syuzenji: "izu-hakone-syuzenji",
  },
  /** JR北海道 */
  jr_hokkaidou: {
    kikonai: "jr-hokkaidou-kikonai",
    // 函館本線
    hakodate: "jr-hokkaidou-hakodate",
    goryoukaku: "jr-hokkaidou-goryoukaku",
    kikyou: "jr-hokkaidou-kikyou",
    onakayama: "jr-hokka-idou-onakayama",
    nanae: "jr-hokkaidou-nanae",
    shin_hakodate_hokuto: "jr-hokkaidou-shin-hakodate-hokuto",
    niyama: "jr-hokkaidou-niyama",
    onuma: "jr-hokkaidou-onuma",
    onuma_kouen: "jr-hokkaidou-onuma-kouen",
    akaigawa: "jr-hokkaidou-akaigawa",
    komagatake: "jr-hokkaidou-komagatake",
    mori: "jr-hokkaidou-mori",
    ishikura: "jr-hokkaidou-ishikura",
    otoshibe: "jr-hokkaidou-otoshibe",
    nodaoi: "jr-hokkaidou-nodaoi",
    yamakoshi: "jr-hokkaidou-yamakoshi",
    yakumo: "jr-hokkaidou-yakumo",
    yamazaki: "jr-hokkaidou-yamazaki",
    kuroiwa: "jr-hokkaidou-kuroiwa",
    kunnui: "jr-hokkaidou-kunnui",
    osyamanbe: "jr-hokkaidou-osyamanbe",
    hutamata: "jr-hokkaidou-hutamata",
    kuromatsunai: "jr-hokkaidou-kuromatsunai",
    neppu: "jr-hokkaidou-neppu",
    mena: "jr-hokkaidou-mena",
    rankoshi: "jr-hokkaidou-rankoshi",
    konbu: "jr-hokkaidou-konbu",
    niseko: "jr-hokkaidou-niseko",
    hirafu: "jr-hokkaidou-hirafu",
    kucchan: "jr-hokkaidou-kucchan",
    kozawa: "jr-hokkaidou-kozawa",
    ginzan: "jr-hokkaidou-ginzan",
    shikaribetsu: "jr-hokkaidou-shikaribetsu",
    nigi: "jr-hokkaidou-nigi",
    yoichi: "jr-hokkaidou-yoichi",
    ranshima: "jr-hokkaidou-ranshima",
    shioya: "jr-hokkaidou-shioya",
    otaru: "jr-hokkaidou-otaru",
    minami_otaru: "jr-hokkaidou-minami-otaru",
    otaru_chikkou: "jr-hokkaidou-otaru-chikkou",
    asari: "jr-hokkaidou-asari",
    zenibako: "jr-hokkaidou-zenibako",
    hoshimi: "jr-hokkaidou-hoshimi",
    hoshioki: "jr-hokkaidou-hoshioki",
    inaho: "jr-hokkaidou-inaho",
    teine: "jr-hokkaidou-teine",
    inadumi_kouen: "jr-hokkaidou-inadumi-kouen",
    hassamu: "jr-hokkaidou-hassamu",
    hassamu_chuou: "jr-hokkaidou-hassamu-chuou",
    kotoni: "jr-hokkaidou-kotoni",
    souen: "jr-hokkaidou-souen",
    sapporo: "jr-hokkaidou-sapporo",
    naeba: "jr-hokkaidou-naeba",
    shiroishi: "jr-hokkaidou-shiroishi",
    atsubetsu: "jr-hokkaidou-atsubetsu",
    shinrin_kouen: "jr-hokkaidou-shinrin-kouen",
    oasa: "jr-hokkaidou-oasa",
    nopporo: "jr-hokkaidou-nopporo",
    takasago: "jr-hokkaidou-takasago",
    ebetsu: "jr-hokkaidou-ebetsu",
    toyohoro: "jr-hokkaidou-toyohoro",
    horomui: "jr-hokkaidou-horomui",
    kami_horomui: "jr-hokkaidou-kami-horomui",
    iwamizawa: "jr-hokkaidou-iwamizawa",
    minenobu: "jr-hokkaidou-minenobu",
    kousyunai: "jr-hokkaidou-kousyunai",
    bibai: "jr-hokkaidou-bibai",
    chashinai: "jr-hokkaidou-chashinai",
    naie: "jr-hokkaidou-naie",
    toyonuma: "jr-hokkaidou-toyonuma",
    sunagawa: "jr-hokkaidou-sunagawa",
    takikawa: "jr-hokkaidou-takikawa",
    ebeotsu: "jr-hokkaidou-ebeotsu",
    moseushi: "jr-hokkaidou-moseushi",
    fukagawa: "jr-hokkaidou-fukagawa",
    osamunai: "jr-hokkaidou-osamunai",
    chikabumi: "jr-hokkaidou-chikabumi",
    asahikawa: "jr-hokkaidou-asahikawa",
    // 富良野線
    kaguraoka: "jr-hokkaidou-kaguraoka",
    midorigaoka: "jr-hokkaidou-midorigaoka",
    nishi_goryou: "jr-hokkaidou-nishi-goryou",
    nishi_mizuho: "jr-hokkaidou-nishi-mizuho",
    nishi_kagura: "jr-hokkaidou-nishi-kagura",
    nishi_seiwa: "jr-hokkaidou-nishi-seiwa",
    chiyogaoka: "jr-hokkaidou-chiyogaoka",
    kita_biei: "jr-hokkaidou-kita-biei",
    biei: "jr-hokkaidou-biei",
    bibaushi: "jr-hokkaidou-bibaushi",
    kami_furano: "jr-hokkaidou-kami-furano",
    nishinaka: "jr-hokka-idou-nishinaka",
    lavender_batake: "jr-hokkaidou-lavender-batake",
    naka_furano: "jr-hokkaidou-naka-furano",
    shikauchi: "jr-hokkaidou-shikauchi",
    gakuden: "jr-hokkaidou-gakuden",
    furano: "jr-hokkaidou-furano",
    // 宗谷本線
    asahikawa_shijou: "jr-hokkaidou-asahikawa-shijou",
    shin_asahikawa: "jr-hokkaidou-shin-asahikawa",
    nagayama: "jr-hokkaidou-nagayama",
    kita_nagayama: "jr-hokkaidou-kita-nagayama",
    pippu: "jr-hokkaidou-pippu",
    ranru: "jr-hokkaidou-ranru",
    shiokari: "jr-hokkaidou-shiokari",
    wassamu: "jr-hokkoaidou-wassamu",
    kenbuchi: "jr-hokkaidou-kenbuchi",
    shibetsu: "jr-hokkaidou-shibetsu",
    tayoro: "jr-hokkaidou-tayoro",
    mizuho: "jr-hokkaidou-mizuho",
    furen: "jr-hokkaidou-furen",
    nayoro_koukou: "jr-hokka-idou-nayoro-koukou",
    nayoro: "jr-hokkaidou-nayoro",
    nisshin: "jr-hokkaidou-nisshin",
    chiebun: "jr-hokkaidou-chiebun",
    chihoku: "jr-hokkaidou-chihoku",
    bihuka: "jr-hokkaidou-bihuka",
    teshiogawa_onsen: "jr-hokkaidou-teshiogawa_onsen",
    sakkuru: "jr-hokkaidou-sakkuru",
    otoineppu: "jr-hokkaidou-otoineppu",
    osashima: "jr-hokkaidou-osashima",
    saku: "jr-hokkaidou-saku",
    teshionakagawa: "jr-hokka-idou-teshionakagawa",
    toikanbetsu: "jr-hokkaidou-toikanbetsu",
    nukanan: "jr-hokkaidou-nukanan",
    onoppunai: "jr-hokkaidou-onoppunai",
    minami_horonobe: "jr-hokkaidou-minami-horonobe",
    horonobe: "jr-hokkaidou-horonobe",
    shimonuma: "jr-hokkaidou-shimonuma",
    toyohu: "jr-hokkaidou-toyohu",
    kabutonuma: "jr-hokkaidou-kabutonuma",
    yuchi: "jr-hokkaidou-yuchi",
    bakkai: "jr-hokkaidou-bakkai",
    minami_wakkanai: "jr-hokka-idou-minami-wakkanai",
    wakkanai: "jr-hokka-idou-wakkanai",
    // 石北本線
    minami_nagayama: "jr-hokka-idou-minami-nagayama",
    higashi_asahikawa: "jr-hokkaidou-higashi-asahikawa",
    sakuraoka: "jr-hokkaidou-sakuraoka",
    touma: "jr-hokkaidou-touma",
    ikaushi: "jr-hokkaidou-ikaushi",
    aibetsu: "jr-hokkaidou-aibetsu",
    naka_aibetsu: "jr-hokkaidou-naka-aibetsu",
    antaroma: "jr-hokkaidou-antaroma",
    kamikawa: "jr-hokkaidou-kamikawa",
    shirataki: "jr-hokka-idou-shirataki",
    maru_seppu: "jr-hokkaidou-maru-seppu",
    setose: "jr-hokkaidou-setose",
    engaru: "jr-hokkaidou-engaru",
    ankoku: "jr-hokkaidou-ankoku",
    ikutahara: "jr-hokkaidou-ikutahara",
    nishi_rubeshibe: "jr-hokkaidou-nishi-rubeshibe",
    rubeshibe: "jr-hokkaidou-rubeshibe",
    ainonai: "jr-hokkaidou-ainonai",
    higashi_ainonai: "jr-hokkaidou-higashi-ainonai",
    nishi_kitami: "jr-hokkaidou-nishi-kitami",
    kitami: "jr-hokkaidou-kitami",
    hakuyou: "jr-hokkaidou-hakuyou",
    itoshino: "jr-hokkaidou-itoshino",
    tanno: "jr-hokkaidou-tanno",
    hiushinai: "jr-hokkaidou-hiushinai",
    bihoro: "jr-hokka-idou-bihoro",
    nishi_memanbetsu: "jr-hokkaidou-nishi-memanbetsu",
    memanbetsu: "jr-hokkaidou-memanbetsu",
    yobito: "jr-hokkaidou-yobito",
    abashiri: "jr-hokkaidou-abashiri",
    // 釧網本線
    kushiro: "jr-hokkaidou-kushiro",
    higashi_kushiro: "jr-hokkaidou-higashi-kushiro",
    toya: "jr-hokkaidou-toya",
    kushiro_onsen: "jr-hokkaidou-kushiro_onsen",
    hosooka: "jr-hokkaidou-hosooka",
    touro: "jr-hokkaidou-touro",
    kayanuma: "jr-hokkaidou-kayanuma",
    shibecha: "jr-hokkaidou-shibecha",
    isobunnai: "jr-hokkaidou-isobunnai",
    masyu: "jr-hokkaidou-masyu",
    biruwa: "jr-hokkaidou-biruwa",
    kawayu_onsen: "jr-hokkaidou-kawayu_onsen",
    midori: "jr-hokkaidou-midori",
    sattsuru: "jr-hokkaidou-sattsuru",
    kiyosatocho: "jr-hokkaidou-kiyosatocho",
    nakasyari: "jr-hokkaidou-nakasyari",
    shiretoko_syari: "jr-hokkaidou-shiretoko-syari",
    yamubetsu: "jr-hokkaidou-yamubetsu",
    hamakoshimizu: "jr-hokkaidou-hamakoshimizu",
    genseikaen: "jr-hokkaidou-genseikaen",
    kitahama: "jr-hokkaidou-kitahama",
    mokoto: "jr-hokkaidou-mokoto",
    masuura: "jr-hokkaidou-masuura",
    katsuradai: "jr-hokkaidou-katsuradai",
    // 花咲線
    musa: "jr-hokkaidou-musa",
    beppo: "jr-hokkaidou-beppo",
    kami_oboro: "jr-hokkaidou-kami-oboro",
    oboro: "jr-hokkaidou-oboro",
    monshizu: "jr-hokkaidou-monshizu",
    akkeshi: "jr-hokkaidou-akkeshi",
    chanai: "jr-hokkaidou-chanai",
    hamanaka: "jr-hokkaidou-hamanaka",
    anebetsu: "jr-hokkaidou-anebetsu",
    attoko: "jr-hokkaidou-attoko",
    bettoga: "jr-hokkaidou-bettoga",
    ochiishi: "jr-hokkaidou-ochiishi",
    konbumori: "jr-hokkaidou-konbumori",
    nishi_wada: "jr-hokkaidou-nishi-wada",
    // 根室本線1
    higashi_takikawa: "jr-hokkaidou-higashi-takikawa",
    akabira: "jr-hokkaidou-akabira",
    moshiri: "jr-hokkaidou-moshiri",
    hirakishi: "jr-hokkaidou-hirakishi",
    ashibetsu: "jr-hokkaidou-ashibetsu",
    kami_ashibetsu: "jr-hokkaidou-kami-ashibetsu",
    nokanan: "jr-hokkaidou-nokanan",
    // 根室本線2
    shintoku: "jr-hokkaidou-shintoku",
    tokachi_shimizu: "jr-hokkaidou-tokachi-shimizu",
    mikage: "jr-hokkaidou-mikage",
    memuro: "jr-hokkaidou-memuro",
    taisei: "jr-hokkaidou-taisei",
    nishi_obihiro: "jr-hokkaidou-nishi-obihiro",
    hakurindai: "jr-hokkaidou-hakurindai",
    obihiro: "jr-hokkaidou-obihiro",
    satsunai: "jr-hokkaidou-satsunai",
    makubetsu: "jr-hokkaidou-makubetsu",
    toshibetsu: "jr-hokkaidou-toshibetsu",
    ikeda: "jr-hokkaidou-ikeda",
    tofutsu: "jr-hokkaidou-tofutsu",
    toyokoro: "jr-hokkaidou-toyokoro",
    shinyoshino: "jr-hokkaidou-yoshino",
    urahoro: "jr-hokkaidou-urahoro",
    atsunai: "jr-hokkaidou-atsunai",
    onbetsu: "jr-hokkaidou-onbetsu",
    shiranuka: "jr-hokkaidou-shiranuka",
    nishi_syoro: "jr-hokkaidou-nishi-syoro",
    syoro: "jr-hokkaidou-syoro",
    otanoshike: "jr-hokkaidou-otanoshike",
    shin_otanoshike: "jr-hokkaidou-shin-otanoshike",
    shinfuji: "jr-hokkaidou-shin-fuji",
    higashi_nemuro: "jr-hokkaidou-higashi-nemuro",
    nemuro: "jr-hokkaidou-nemuro",
    // 石勝線
    minami_chitose: "jr-hokkaidou-minami-chitose",
    oiwake: "jr-hokkaidou-oiwake",
    kawabata: "jr-hokkaidou-kawabata",
    shin_yubari: "jr-hokkaidou-shin-yubari",
    shimukappu: "jr-hokkaidou-shimukappu",
    tomamu: "jr-hokkaidou-tomamu",
    // 千歳線
    tomakomai: "jr-hokkaidou-tomakomai",
    numanohata: "jr-hokkaidou-numanohata",
    uenae: "jr-hokkaidou-uenae",
    shin_chitose_kuko: "jr-hokkaidou-shin-chitose-kuko",
    chitose: "jr-hokkaidou-chitose",
    osatsu: "jr-hokkaidou-osatsu",
    sapporo_beer_teien: "jr-hokkaidou-sapporo-beer-teien",
    eniwa: "jr-hokkaidou-eniwa",
    megumino: "jr-hokkaidou-megumino",
    shimamatsu: "jr-hokkaidou-shimamatsu",
    kita_hiroshima: "jr-hokkaidou-kita-hiroshima",
    kami_nopporo: "jr-hokkaidou-kami-nopporo",
    heiwa: "jr-hokkaidou-heiwa",
    shin_sapporo: "jr-hokkaidou-shin-sapporo",
    // 室蘭本線
    shizukari: "jr-hokkaidou-shizukari",
    kohoro: "jr-hokkaidou-kohoro",
    rebunn: "jr-hokkaidou-rebunn",
    okishi: "jr-hokkaidou-okishi",
    toyoura: "jr-hokkaidou-toyoura",
    touya: "jr-hokkaidou-touya",
    usu: "jr-hokkaidou-usu",
    nagawa: "jr-hokkaidou-nagawa",
    datemonbetsu: "jr-hokkaidou-datemonbetsu",
    kitahunaoka: "jr-hokkaidou-kitahunaoka",
    mareppu: "jr-hokkaidou-mareppu",
    kogane: "jr-hokkaidou-kogane",
    sakimori: "jr-hokkaidou-sakimori",
    motowanishi: "jr-hokkaidou-motowanishi",
    higashi_muroran: "jr-hokkaidou-higashi-muroran",
    washibetsu: "jr-hokkaidou-washibetsu",
    horobetsu: "jr-hokkaidou-horobetsu",
    tomiura: "jr-hokkaidou-tomiura",
    noboribetsu: "jr-hokkaidou-noboribetsu",
    kojouhama: "jr-hokkaidou-kojouhama",
    takeura: "jr-hokkaidou-takeura",
    kita_yoshihara: "jr-hokkaidou-kita-yoshihara",
    hagino: "jr-hokkaidou-hagino",
    shiraoi: "jr-hokkaidou-shiraoi",
    syadai: "jr-hokkaidou-syadai",
    nishikioka: "jr-hokkaidou-nishikioka",
    aoba: "jr-hokkaidou-aoba",
    toasa: "jr-hokaidou-toasa",
    hayakita: "jr-hokkaidou-hayakita",
    abira: "jr-hokkaidou-abira",
    mikawa: "jr-hokkaidou-mikawa",
    furusan: "jr-hokkaidou-furusan",
    yuni: "jr-hokkaidou-yuni",
    itoi: "jr-hokkaidou-itoi",
    kuriyama: "jr-hokkaidou-kuriyama",
    kurioka: "jr-hokkaidou-kurioka",
    kurisawa: "jr-hokkaidou-kurisawa",
    shibun: "jr-hokkaidou-shibun",
    wanishi: "jr-hokkaidou-wanishi",
    misaki: "jr-hokkaidou-misaki",
    bokoi: "jr-hokkaidou-bokoi",
    muroran: "jr-hokkaidou-muroran",
    // 日高本線
    yufutsu: "jr-hokkaidou-yufutsu",
    hamaatsuma: "jr-hokkaidou-hamaatsuma",
    mukawa: "jr-hokkaidou-mukawa",
  },
  /** 札幌地下鉄　駅 */
  sapporo_subway: {
    // 東西線
    miyanozawa: "supporo-subway-miyanozawa",
    hassamu_minami: "supporo-subway-hassamu-minami",
    kotoni: "supporo-subway-kotoni",
    nijuuyonken: "supporo-subway-nijuuyonken",
    nishi_nijuuhatchome: "supporo-subway-nishi-nijuuhatchome",
    maruyama_kouen: "supporo-subway-maruyama-kouen",
    nishi_juhacchome: "supporo-subway-nishi-juhacchome",
    nishi_juicchoume: "supporo-subway-nishi-juicchoume",
    odouri: "supporo-subway-odouri",
    bass_center_minami: "supporo-subway-bass-center-minami",
    kikusui: "supporo-subway-kikusui",
    higashi_sapporo: "supporo-subway-higashi-sapporo",
    shiraishi: "supporo-subway-shiraishi",
    nangou_nanachoume: "supporo-subway-nangou-nanachoume",
    nangou_jusanchoume: "supporo-subway-nangou-jusanchoume",
    nangou_juhacchoume: "supporo-subway-nangou-juhacchoume",
    oyachi: "supporo-subway-oyachi",
    hibarigaoka: "supporo-subway-hibarigaoka",
    shin_sapporo: "supporo-subway-shin-sapporo",
  },
};
