import { TrainLine } from "@/types/line";
import { LINE_IDS } from "../line-ids";
import { COMPANIES } from "../companies";
import {
  EXTRA1,
  Extra1,
  Extra2,
  EXTRA2,
  EXTRA3,
  Extra3,
  EXTRA4,
  Extra4,
  RAPID,
  RAPID_COMMUTER,
  ServiceType,
} from "@/types/service-type";
import { Section } from "@/types/Section";
import { StopStation } from "@/types/stop-station";
import { STATION_IDS } from "../station-ids";

export const jr_east_lines = {
  [LINE_IDS.jr_east.toukaidou]: new TrainLine({
    name: "東海道本線(JR東日本)",
    reading: "とうかいどうほんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [new Extra1("快速アクティー")],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.shinbashi, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.shinagawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kawasaki, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.yokohama, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.totsuka, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ofuna, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hujisawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.tsujido, []),
        new StopStation(STATION_IDS.jr_east.chigasaki, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hiratsuka, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.oiso, []),
        new StopStation(STATION_IDS.jr_east.ninomiya, []),
        new StopStation(STATION_IDS.jr_east.koudu, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kamonomiya, []),
        new StopStation(STATION_IDS.jr_east.odawara, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hayakawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.nebukawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.manazuru, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.yugawara, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.atami, ["extra1"]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.keihin_touhoku]: new TrainLine({
    name: "京浜東北線",
    reading: "けいひんとうほくせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [RAPID],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.omiya, [RAPID]),
        new StopStation(STATION_IDS.jr_east.saitama_shintoshin, [RAPID]),
        new StopStation(STATION_IDS.jr_east.yono, [RAPID]),
        new StopStation(STATION_IDS.jr_east.urawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.minami_urawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.warabi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nishikawaguchi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kawaguti, [RAPID]),
        new StopStation(STATION_IDS.jr_east.akahane, [RAPID]),
        new StopStation(STATION_IDS.jr_east.higashijujo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.ouji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kaminakazato, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tabata, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nishinippori),
        new StopStation(STATION_IDS.jr_east.nippori),
        new StopStation(STATION_IDS.jr_east.uguisudani),
        new StopStation(STATION_IDS.jr_east.ueno, [RAPID]),
        new StopStation(STATION_IDS.jr_east.okachimachi),
        new StopStation(STATION_IDS.jr_east.akihabara, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kanda, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tokyo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.yurakucho),
        new StopStation(STATION_IDS.jr_east.shinbashi),
        new StopStation(STATION_IDS.jr_east.hamamatsucho, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tamachi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.takanawa_gateway, [RAPID]),
        new StopStation(STATION_IDS.jr_east.shinagawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.oimachi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.omori, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kamata, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kawasaki, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tsurumi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.shinkoyasu, [RAPID]),
        new StopStation(STATION_IDS.jr_east.higashikanagawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.yokohama, [RAPID]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.yamanote]: new TrainLine({
    name: "山手線",
    reading: "やまのてせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.shinagawa, []),
        new StopStation(STATION_IDS.jr_east.takanawa_gateway, []),
        new StopStation(STATION_IDS.jr_east.tamachi, []),
        new StopStation(STATION_IDS.jr_east.hamamatsucho, []),
        new StopStation(STATION_IDS.jr_east.shinbashi, []),
        new StopStation(STATION_IDS.jr_east.yurakucho, []),
        new StopStation(STATION_IDS.jr_east.tokyo, []),
        new StopStation(STATION_IDS.jr_east.kanda, []),
        new StopStation(STATION_IDS.jr_east.akihabara, []),
        new StopStation(STATION_IDS.jr_east.okachimachi, []),
        new StopStation(STATION_IDS.jr_east.ueno, []),
        new StopStation(STATION_IDS.jr_east.uguisudani, []),
        new StopStation(STATION_IDS.jr_east.nippori, []),
        new StopStation(STATION_IDS.jr_east.nishinippori, []),
        new StopStation(STATION_IDS.jr_east.tabata, []),
        new StopStation(STATION_IDS.jr_east.komagome, []),
        new StopStation(STATION_IDS.jr_east.sugamo, []),
        new StopStation(STATION_IDS.jr_east.ohtsuka, []),
        new StopStation(STATION_IDS.jr_east.ikebukuro, []),
        new StopStation(STATION_IDS.jr_east.mejiro, []),
        new StopStation(STATION_IDS.jr_east.takadanobaba, []),
        new StopStation(STATION_IDS.jr_east.shin_ohkubo, []),
        new StopStation(STATION_IDS.jr_east.shinjuku, []),
        new StopStation(STATION_IDS.jr_east.yoyogi, []),
        new StopStation(STATION_IDS.jr_east.harajuku, []),
        new StopStation(STATION_IDS.jr_east.shibuya, []),
        new StopStation(STATION_IDS.jr_east.ebisu, []),
        new StopStation(STATION_IDS.jr_east.meguro, []),
        new StopStation(STATION_IDS.jr_east.gotanda, []),
        new StopStation(STATION_IDS.jr_east.osaki, []),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.yokohama]: new TrainLine({
    name: "横浜線",
    reading: "よこはません",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.hachiouji, []),
        new StopStation(STATION_IDS.jr_east.katakura, []),
        new StopStation(STATION_IDS.jr_east.hachiouji_minamino, []),
        new StopStation(STATION_IDS.jr_east.aihara, []),
        new StopStation(STATION_IDS.jr_east.hashimoto, []),
        new StopStation(STATION_IDS.jr_east.sagamihara, []),
        new StopStation(STATION_IDS.jr_east.huchinobe, []),
        new StopStation(STATION_IDS.jr_east.kobuchi, []),
        new StopStation(STATION_IDS.jr_east.machida, []),
        new StopStation(STATION_IDS.jr_east.naruse, []),
        new StopStation(STATION_IDS.jr_east.nagatsuta, []),
        new StopStation(STATION_IDS.jr_east.tokaichiba, []),
        new StopStation(STATION_IDS.jr_east.nakayama, []),
        new StopStation(STATION_IDS.jr_east.kamoi, []),
        new StopStation(STATION_IDS.jr_east.kodukue, []),
        new StopStation(STATION_IDS.jr_east.shin_yokohama, []),
        new StopStation(STATION_IDS.jr_east.kikuna, []),
        new StopStation(STATION_IDS.jr_east.oguchi, []),
        new StopStation(STATION_IDS.jr_east.higashi_kanagawa, []),
        new StopStation(STATION_IDS.jr_east.yokohama, []),
        new StopStation(STATION_IDS.jr_east.sakuragicho, []),
        new StopStation(STATION_IDS.jr_east.kannai, []),
        new StopStation(STATION_IDS.jr_east.ishikawacho, []),
        new StopStation(STATION_IDS.jr_east.yokohama, []),
        new StopStation(STATION_IDS.jr_east.negishi, []),
        new StopStation(STATION_IDS.jr_east.isogo, []),
        new StopStation(STATION_IDS.jr_east.shin_sugita, []),
        new StopStation(STATION_IDS.jr_east.youkoudai, []),
        new StopStation(STATION_IDS.jr_east.kounandai, []),
        new StopStation(STATION_IDS.jr_east.hongoudai, []),
        new StopStation(STATION_IDS.jr_east.ofuna, []),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.negishi]: new TrainLine({
    name: "根岸線",
    reading: "ねぎしせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.yokohama, []),
        new StopStation(STATION_IDS.jr_east.sakuragicho, []),
        new StopStation(STATION_IDS.jr_east.kannai, []),
        new StopStation(STATION_IDS.jr_east.ishikawacho, []),
        new StopStation(STATION_IDS.jr_east.yamate, []),
        new StopStation(STATION_IDS.jr_east.negishi, []),
        new StopStation(STATION_IDS.jr_east.isogo, []),
        new StopStation(STATION_IDS.jr_east.shin_sugita, []),
        new StopStation(STATION_IDS.jr_east.youkoudai, []),
        new StopStation(STATION_IDS.jr_east.kounandai, []),
        new StopStation(STATION_IDS.jr_east.hongoudai, []),
        new StopStation(STATION_IDS.jr_east.ofuna, []),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.chuou_honsen]: new TrainLine({
    name: "中央本線(東京ー塩尻)",
    reading: "ちゅうおうほんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [RAPID],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kanda),
        new StopStation(STATION_IDS.jr_east.ochanomizu),
        new StopStation(STATION_IDS.jr_east.yotsuya),
        new StopStation(STATION_IDS.jr_east.shinjuku),
        new StopStation(STATION_IDS.jr_east.nakano, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kouenji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.asagaya, [RAPID]),
        new StopStation(STATION_IDS.jr_east.ogikubo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nishi_ogikubo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kichijoji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.mitaka, [RAPID]),
        new StopStation(STATION_IDS.jr_east.musashisakai, [RAPID]),
        new StopStation(STATION_IDS.jr_east.higashi_koganei, [RAPID]),
        new StopStation(STATION_IDS.jr_east.musashi_koganei, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kokubunji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nishikokubunji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kunitachi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tachikawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.hino, [RAPID]),
        new StopStation(STATION_IDS.jr_east.toyoda, [RAPID]),
        new StopStation(STATION_IDS.jr_east.hachiouji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nishi_hachiouji, [RAPID]),
        new StopStation(STATION_IDS.jr_east.takao, [RAPID]),
        new StopStation(STATION_IDS.jr_east.sagamiko),
        new StopStation(STATION_IDS.jr_east.fujino),
        new StopStation(STATION_IDS.jr_east.uenohara),
        new StopStation(STATION_IDS.jr_east.shiotsu),
        new StopStation(STATION_IDS.jr_east.yanagawa),
        new StopStation(STATION_IDS.jr_east.torisawa),
        new StopStation(STATION_IDS.jr_east.saruhashi),
        new StopStation(STATION_IDS.jr_east.ohtsuki),
        new StopStation(STATION_IDS.jr_east.hatsukari),
        new StopStation(STATION_IDS.jr_east.sasago),
        new StopStation(STATION_IDS.jr_east.kai_yamato),
        new StopStation(STATION_IDS.jr_east.katsunuma_budoukyou),
        new StopStation(STATION_IDS.jr_east.enzan),
        new StopStation(STATION_IDS.jr_east.higashi_yamanashi),
        new StopStation(STATION_IDS.jr_east.yamanashishi),
        new StopStation(STATION_IDS.jr_east.kasugaichou),
        new StopStation(STATION_IDS.jr_east.isawa_onsen),
        new StopStation(STATION_IDS.jr_east.sakaori),
        new StopStation(STATION_IDS.jr_east.koufu),
        new StopStation(STATION_IDS.jr_east.ryuou),
        new StopStation(STATION_IDS.jr_east.shiozaki),
        new StopStation(STATION_IDS.jr_east.nirasaki),
        new StopStation(STATION_IDS.jr_east.shinpu),
        new StopStation(STATION_IDS.jr_east.anayama),
        new StopStation(STATION_IDS.jr_east.hinoharu),
        new StopStation(STATION_IDS.jr_east.nagasaka),
        new StopStation(STATION_IDS.jr_east.kobuchizawa),
        new StopStation(STATION_IDS.jr_east.shinano_sakai),
        new StopStation(STATION_IDS.jr_east.fujimi),
        new StopStation(STATION_IDS.jr_east.suzuran_no_sato),
        new StopStation(STATION_IDS.jr_east.aoyanagi),
        new StopStation(STATION_IDS.jr_east.chino),
        new StopStation(STATION_IDS.jr_east.kami_suwa),
        new StopStation(STATION_IDS.jr_east.shimo_suwa),
        new StopStation(STATION_IDS.jr_east.okaya),
        new StopStation(STATION_IDS.jr_east.midoriko),
        new StopStation(STATION_IDS.jr_east.shiojiri),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.chuou_honsen_okaya_shiojiri]: new TrainLine({
    name: "中央本線(岡谷ー塩尻)",
    reading: "ちゅうおうほんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.okaya),
        new StopStation(STATION_IDS.jr_east.kawagishi),
        new StopStation(STATION_IDS.jr_east.tatsuno),
        new StopStation(STATION_IDS.jr_east.shinano_kawashima),
        new StopStation(STATION_IDS.jr_east.ono),
        new StopStation(STATION_IDS.jr_east.shiojiri),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.oume]: new TrainLine({
    name: "青梅線",
    reading: "おうめせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [new ServiceType("青梅快特", "extra1")],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tachikawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.nishi_tachikawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.higashi_nakagami, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.nakagami, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.akishima, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.haijima, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ushihama, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.fussa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hamura, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ozaku, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kabe, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.higashi_oume, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.oume, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.miyanohira, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hinatawada, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ishigamimae, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.futamatao, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ikusabata, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.sawai, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.mitake, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kawai, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kori, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.hatonosu, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.shiromaru, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.okutama, ["extra1"]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.chuo_soubu_kankou]: new TrainLine({
    name: "中央・総武緩行線(中央・総武線各停)",
    reading: "ちゅうおう・そうぶかんこうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.mitaka, []),
        new StopStation(STATION_IDS.jr_east.kichijoji),
        new StopStation(STATION_IDS.jr_east.nishi_ogikubo),
        new StopStation(STATION_IDS.jr_east.ogikubo),
        new StopStation(STATION_IDS.jr_east.asagaya),
        new StopStation(STATION_IDS.jr_east.kouenji),
        new StopStation(STATION_IDS.jr_east.nakano),
        new StopStation(STATION_IDS.jr_east.higashi_nakano),
        new StopStation(STATION_IDS.jr_east.ohkubo),
        new StopStation(STATION_IDS.jr_east.shinjuku),
        new StopStation(STATION_IDS.jr_east.yoyogi),
        new StopStation(STATION_IDS.jr_east.sendagaya),
        new StopStation(STATION_IDS.jr_east.shinanomachi),
        new StopStation(STATION_IDS.jr_east.yotsuya),
        new StopStation(STATION_IDS.jr_east.ichigaya),
        new StopStation(STATION_IDS.jr_east.iidabashi),
        new StopStation(STATION_IDS.jr_east.suidoubashi),
        new StopStation(STATION_IDS.jr_east.ochanomizu),
        new StopStation(STATION_IDS.jr_east.akihabara),
        new StopStation(STATION_IDS.jr_east.asakusabashi),
        new StopStation(STATION_IDS.jr_east.ryogoku),
        new StopStation(STATION_IDS.jr_east.kinshicho),
        new StopStation(STATION_IDS.jr_east.kameido),
        new StopStation(STATION_IDS.jr_east.hirai),
        new StopStation(STATION_IDS.jr_east.shinkoiwa),
        new StopStation(STATION_IDS.jr_east.koiwa),
        new StopStation(STATION_IDS.jr_east.ichikawa),
        new StopStation(STATION_IDS.jr_east.motoyawata),
        new StopStation(STATION_IDS.jr_east.shimousa_nakayama),
        new StopStation(STATION_IDS.jr_east.nishifunabashi),
        new StopStation(STATION_IDS.jr_east.funabashi),
        new StopStation(STATION_IDS.jr_east.higashi_funabashi),
        new StopStation(STATION_IDS.jr_east.tsudanuma),
        new StopStation(STATION_IDS.jr_east.makuharihongou),
        new StopStation(STATION_IDS.jr_east.makuhari),
        new StopStation(STATION_IDS.jr_east.shinkemigawa),
        new StopStation(STATION_IDS.jr_east.inage),
        new StopStation(STATION_IDS.jr_east.nishichiba),
        new StopStation(STATION_IDS.jr_east.chiba),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.sobu_kaisoku]: new TrainLine({
    name: "総武快速線",
    reading: "そうぶかいそくせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.chiba),
        new StopStation(STATION_IDS.jr_east.inage),
        new StopStation(STATION_IDS.jr_east.tsudanuma),
        new StopStation(STATION_IDS.jr_east.funabashi),
        new StopStation(STATION_IDS.jr_east.ichikawa),
        new StopStation(STATION_IDS.jr_east.shinkoiwa),
        new StopStation(STATION_IDS.jr_east.kinshicho),
        new StopStation(STATION_IDS.jr_east.bakurocho),
        new StopStation(STATION_IDS.jr_east.shin_nihonbashi),
        new StopStation(STATION_IDS.jr_east.tokyo),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.soubu_honsen]: new TrainLine({
    name: "総武本線(総武線快速)",
    reading: "そうぶほんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [new Extra1("総武線快速")],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.shin_nihonbashi, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.bakurocho, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.kinshicho, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.kameido),
        new StopStation(STATION_IDS.jr_east.hirai),
        new StopStation(STATION_IDS.jr_east.shinkoiwa, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.koiwa),
        new StopStation(STATION_IDS.jr_east.ichikawa, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.motoyawata),
        new StopStation(STATION_IDS.jr_east.shimousa_nakayama),
        new StopStation(STATION_IDS.jr_east.nishifunabashi),
        new StopStation(STATION_IDS.jr_east.funabashi, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.higashi_funabashi),
        new StopStation(STATION_IDS.jr_east.tsudanuma, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.makuharihongou),
        new StopStation(STATION_IDS.jr_east.makuhari),
        new StopStation(STATION_IDS.jr_east.shinkemigawa),
        new StopStation(STATION_IDS.jr_east.inage, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.nishi_chiba),
        new StopStation(STATION_IDS.jr_east.chiba, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.higashi_chiba),
        new StopStation(STATION_IDS.jr_east.tsuga),
        new StopStation(STATION_IDS.jr_east.yotsukaidou),
        new StopStation(STATION_IDS.jr_east.monoi),
        new StopStation(STATION_IDS.jr_east.sakura),
        new StopStation(STATION_IDS.jr_east.minami_shisui),
        new StopStation(STATION_IDS.jr_east.enokido),
        new StopStation(STATION_IDS.jr_east.yachimata),
        new StopStation(STATION_IDS.jr_east.hyuga),
        new StopStation(STATION_IDS.jr_east.narutou),
        new StopStation(STATION_IDS.jr_east.matsuo),
        new StopStation(STATION_IDS.jr_east.yokoshiba),
        new StopStation(STATION_IDS.jr_east.iigura),
        new StopStation(STATION_IDS.jr_east.youkaichiba),
        new StopStation(STATION_IDS.jr_east.higata),
        new StopStation(STATION_IDS.jr_east.asahi),
        new StopStation(STATION_IDS.jr_east.iioka),
        new StopStation(STATION_IDS.jr_east.kurahashi),
        new StopStation(STATION_IDS.jr_east.saruda),
        new StopStation(STATION_IDS.jr_east.matsugishi),
        new StopStation(STATION_IDS.jr_east.choushi),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.yokosuka]: new TrainLine({
    name: "横須賀線",
    reading: "よこすかせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.shinbashi),
        new StopStation(STATION_IDS.jr_east.shinagawa),
        new StopStation(STATION_IDS.jr_east.nishioi),
        new StopStation(STATION_IDS.jr_east.musashi_kosugi),
        new StopStation(STATION_IDS.jr_east.shinkawasaki),
        new StopStation(STATION_IDS.jr_east.yokohama),
        new StopStation(STATION_IDS.jr_east.hodogaya),
        new StopStation(STATION_IDS.jr_east.higashitotsuka),
        new StopStation(STATION_IDS.jr_east.totsuka),
        new StopStation(STATION_IDS.jr_east.ofuna),
        new StopStation(STATION_IDS.jr_east.kitakamakura),
        new StopStation(STATION_IDS.jr_east.kamakura),
        new StopStation(STATION_IDS.jr_east.zushi),
        new StopStation(STATION_IDS.jr_east.higashizushi),
        new StopStation(STATION_IDS.jr_east.taura),
        new StopStation(STATION_IDS.jr_east.yokosuka),
        new StopStation(STATION_IDS.jr_east.kinugasa),
        new StopStation(STATION_IDS.jr_east.kurihama),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.kawagoe]: new TrainLine({
    name: "川越線",
    reading: "かわごえせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.nisshin),
        new StopStation(STATION_IDS.jr_east.nishi_omiya),
        new StopStation(STATION_IDS.jr_east.sashiougi),
        new StopStation(STATION_IDS.jr_east.minami_furuya),
        new StopStation(STATION_IDS.jr_east.kawagoe),
        new StopStation(STATION_IDS.jr_east.nishi_kawagoe),
        new StopStation(STATION_IDS.jr_east.matoba),
        new StopStation(STATION_IDS.jr_east.kasahata),
        new StopStation(STATION_IDS.jr_east.musashi_takahagi),
        new StopStation(STATION_IDS.jr_east.komagawa),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.saikyou]: new TrainLine({
    name: "埼京線",
    reading: "さいきょうせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [RAPID, RAPID_COMMUTER],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.osaki, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.ebisu, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.shibuya, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.shinjuku, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.ikebukuro, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.itabashi, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.jujo, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.akahane, [RAPID, RAPID_COMMUTER]),
        new StopStation(STATION_IDS.jr_east.kitaakahane),
        new StopStation(STATION_IDS.jr_east.ukimafunado),
        new StopStation(STATION_IDS.jr_east.todakouen, [RAPID]),
        new StopStation(STATION_IDS.jr_east.toda),
        new StopStation(STATION_IDS.jr_east.kitatoda),
        new StopStation(STATION_IDS.jr_east.musashi_urawa, [
          RAPID,
          RAPID_COMMUTER,
        ]),
        new StopStation(STATION_IDS.jr_east.naka_urawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.minamiyono, [RAPID]),
        new StopStation(STATION_IDS.jr_east.yono_honmachi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kita_yono, [RAPID]),
        new StopStation(STATION_IDS.jr_east.omiya, [RAPID, RAPID_COMMUTER]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shonan_shinjuku]: new TrainLine({
    name: "湘南新宿ライン",
    reading: "しょうなんしんじゅくらいん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.utsunomiya),
        new StopStation(STATION_IDS.jr_east.suzumenomiya),
        new StopStation(STATION_IDS.jr_east.ishibashi),
        new StopStation(STATION_IDS.jr_east.jichiidai),
        new StopStation(STATION_IDS.jr_east.koganei),
        new StopStation(STATION_IDS.jr_east.oyama),
        new StopStation(STATION_IDS.jr_east.mamada),
        new StopStation(STATION_IDS.jr_east.nogi),
        new StopStation(STATION_IDS.jr_east.ofuna),
        new StopStation(STATION_IDS.jr_east.koga),
        new StopStation(STATION_IDS.jr_east.kurihashi),
        new StopStation(STATION_IDS.jr_east.higashiwashinomiya),
        new StopStation(STATION_IDS.jr_east.kuki),
        new StopStation(STATION_IDS.jr_east.shinshiraoka),
        new StopStation(STATION_IDS.jr_east.shiraoka),
        new StopStation(STATION_IDS.jr_east.hasuda),
        new StopStation(STATION_IDS.jr_east.higashiomiya),
        new StopStation(STATION_IDS.jr_east.toro),
        new StopStation(STATION_IDS.jr_east.maebashi),
        new StopStation(STATION_IDS.jr_east.shinmaebashi),
        new StopStation(STATION_IDS.jr_east.ino),
        new StopStation(STATION_IDS.jr_east.takasakitonyamachi),
        new StopStation(STATION_IDS.jr_east.takasaki),
        new StopStation(STATION_IDS.jr_east.kuragano),
        new StopStation(STATION_IDS.jr_east.shinmachi),
        new StopStation(STATION_IDS.jr_east.jinbohara),
        new StopStation(STATION_IDS.jr_east.honnjou),
        new StopStation(STATION_IDS.jr_east.okabe),
        new StopStation(STATION_IDS.jr_east.hukaya),
        new StopStation(STATION_IDS.jr_east.kagohara),
        new StopStation(STATION_IDS.jr_east.kumagaya),
        new StopStation(STATION_IDS.jr_east.gyouda),
        new StopStation(STATION_IDS.jr_east.hukiage),
        new StopStation(STATION_IDS.jr_east.kitakounosu),
        new StopStation(STATION_IDS.jr_east.kounosu),
        new StopStation(STATION_IDS.jr_east.kitamoto),
        new StopStation(STATION_IDS.jr_east.okegawa),
        new StopStation(STATION_IDS.jr_east.kitaageo),
        new StopStation(STATION_IDS.jr_east.ageo),
        new StopStation(STATION_IDS.jr_east.miyahara),
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.urawa),
        new StopStation(STATION_IDS.jr_east.akahane),
        new StopStation(STATION_IDS.jr_east.ikebukuro),
        new StopStation(STATION_IDS.jr_east.shinjuku),
        new StopStation(STATION_IDS.jr_east.shibuya),
        new StopStation(STATION_IDS.jr_east.ebisu),
        new StopStation(STATION_IDS.jr_east.osaki),
        new StopStation(STATION_IDS.jr_east.nishioi),
        new StopStation(STATION_IDS.jr_east.musashi_kosugi),
        new StopStation(STATION_IDS.jr_east.shinkawasaki),
        new StopStation(STATION_IDS.jr_east.yokohama),
        new StopStation(STATION_IDS.jr_east.hodogaya),
        new StopStation(STATION_IDS.jr_east.higashitotsuka),
        new StopStation(STATION_IDS.jr_east.totsuka),
        new StopStation(STATION_IDS.jr_east.ofuna),
        new StopStation(STATION_IDS.jr_east.kitakamakura),
        new StopStation(STATION_IDS.jr_east.kamakura),
        new StopStation(STATION_IDS.jr_east.zushi),
        new StopStation(STATION_IDS.jr_east.hujisawa),
        new StopStation(STATION_IDS.jr_east.tsujido),
        new StopStation(STATION_IDS.jr_east.chigasaki),
        new StopStation(STATION_IDS.jr_east.hiratsuka),
        new StopStation(STATION_IDS.jr_east.oiso),
        new StopStation(STATION_IDS.jr_east.ninomiya),
        new StopStation(STATION_IDS.jr_east.koudu),
        new StopStation(STATION_IDS.jr_east.kamonomiya),
        new StopStation(STATION_IDS.jr_east.odawara),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.takasaki]: new TrainLine({
    name: "高崎線",
    reading: "たかさきせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.ueno),
        new StopStation(STATION_IDS.jr_east.oku),
        new StopStation(STATION_IDS.jr_east.akahane),
        new StopStation(STATION_IDS.jr_east.urawa),
        new StopStation(STATION_IDS.jr_east.saitama_shintoshin),
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.miyahara),
        new StopStation(STATION_IDS.jr_east.ageo),
        new StopStation(STATION_IDS.jr_east.kitaageo),
        new StopStation(STATION_IDS.jr_east.okegawa),
        new StopStation(STATION_IDS.jr_east.kitamoto),
        new StopStation(STATION_IDS.jr_east.kounosu),
        new StopStation(STATION_IDS.jr_east.kitakounosu),
        new StopStation(STATION_IDS.jr_east.hukiage),
        new StopStation(STATION_IDS.jr_east.gyouda),
        new StopStation(STATION_IDS.jr_east.kumagaya),
        new StopStation(STATION_IDS.jr_east.kagohara),
        new StopStation(STATION_IDS.jr_east.hukaya),
        new StopStation(STATION_IDS.jr_east.okabe),
        new StopStation(STATION_IDS.jr_east.honnjou),
        new StopStation(STATION_IDS.jr_east.jinbohara),
        new StopStation(STATION_IDS.jr_east.shinmachi),
        new StopStation(STATION_IDS.jr_east.kuragano),
        new StopStation(STATION_IDS.jr_east.takasaki),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.hachiko]: new TrainLine({
    name: "八高線",
    reading: "はちこうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.hachiouji),
        new StopStation(STATION_IDS.jr_east.kita_hachiouji),
        new StopStation(STATION_IDS.jr_east.komiya),
        new StopStation(STATION_IDS.jr_east.haijima),
        new StopStation(STATION_IDS.jr_east.higashi_fussa),
        new StopStation(STATION_IDS.jr_east.hakonegasaki),
        new StopStation(STATION_IDS.jr_east.kaneko),
        new StopStation(STATION_IDS.jr_east.higashi_hanno),
        new StopStation(STATION_IDS.jr_east.komagawa),
        new StopStation(STATION_IDS.jr_east.moro),
        new StopStation(STATION_IDS.jr_east.ogose),
        new StopStation(STATION_IDS.jr_east.myoukaku),
        new StopStation(STATION_IDS.jr_east.ogawamachi),
        new StopStation(STATION_IDS.jr_east.takezawa),
        new StopStation(STATION_IDS.jr_east.orihara),
        new StopStation(STATION_IDS.jr_east.yorii),
        new StopStation(STATION_IDS.jr_east.youdo),
        new StopStation(STATION_IDS.jr_east.matsuhisa),
        new StopStation(STATION_IDS.jr_east.kodama),
        new StopStation(STATION_IDS.jr_east.tanshou),
        new StopStation(STATION_IDS.jr_east.gunma_fujioka),
        new StopStation(STATION_IDS.jr_east.kita_fujioka),
        new StopStation(STATION_IDS.jr_east.kuragano),
        new StopStation(STATION_IDS.jr_east.takasaki),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.sagami]: new TrainLine({
    name: "相模線",
    reading: "さがみせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.chigasaki),
        new StopStation(STATION_IDS.jr_east.kita_chigasaki),
        new StopStation(STATION_IDS.jr_east.kagawa),
        new StopStation(STATION_IDS.jr_east.samukawa),
        new StopStation(STATION_IDS.jr_east.miyayama),
        new StopStation(STATION_IDS.jr_east.kurami),
        new StopStation(STATION_IDS.jr_east.kadosawabashi),
        new StopStation(STATION_IDS.jr_east.syake),
        new StopStation(STATION_IDS.jr_east.atsugi),
        new StopStation(STATION_IDS.jr_east.ebina),
        new StopStation(STATION_IDS.jr_east.iriya),
        new StopStation(STATION_IDS.jr_east.soubudai_shita),
        new StopStation(STATION_IDS.jr_east.shimomizo),
        new StopStation(STATION_IDS.jr_east.harataima),
        new StopStation(STATION_IDS.jr_east.banda),
        new StopStation(STATION_IDS.jr_east.kamimizo),
        new StopStation(STATION_IDS.jr_east.minami_hashimoto),
        new StopStation(STATION_IDS.jr_east.hashimoto),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.utunomiya]: new TrainLine({
    name: "宇都宮線",
    reading: "うつのみやせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.ueno),
        new StopStation(STATION_IDS.jr_east.oku),
        new StopStation(STATION_IDS.jr_east.akahane),
        new StopStation(STATION_IDS.jr_east.urawa),
        new StopStation(STATION_IDS.jr_east.saitama_shintoshin),
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.toro),
        new StopStation(STATION_IDS.jr_east.higashiomiya),
        new StopStation(STATION_IDS.jr_east.hasuda),
        new StopStation(STATION_IDS.jr_east.shiraoka),
        new StopStation(STATION_IDS.jr_east.shinshiraoka),
        new StopStation(STATION_IDS.jr_east.kuki),
        new StopStation(STATION_IDS.jr_east.higashiwashinomiya),
        new StopStation(STATION_IDS.jr_east.kurihashi),
        new StopStation(STATION_IDS.jr_east.koga),
        new StopStation(STATION_IDS.jr_east.nogi),
        new StopStation(STATION_IDS.jr_east.mamada),
        new StopStation(STATION_IDS.jr_east.oyama),
        new StopStation(STATION_IDS.jr_east.koganei),
        new StopStation(STATION_IDS.jr_east.jichiidai),
        new StopStation(STATION_IDS.jr_east.ishibashi),
        new StopStation(STATION_IDS.jr_east.suzumenomiya),
        new StopStation(STATION_IDS.jr_east.utsunomiya),
        new StopStation(STATION_IDS.jr_east.okamoto),
        new StopStation(STATION_IDS.jr_east.housyakuji),
        new StopStation(STATION_IDS.jr_east.ujiie),
        new StopStation(STATION_IDS.jr_east.kamasusaka),
        new StopStation(STATION_IDS.jr_east.kataoka),
        new StopStation(STATION_IDS.jr_east.yaita),
        new StopStation(STATION_IDS.jr_east.nozaki),
        new StopStation(STATION_IDS.jr_east.nishinasuno),
        new StopStation(STATION_IDS.jr_east.nasu_shiobara),
        new StopStation(STATION_IDS.jr_east.kuroiso),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.musashino]: new TrainLine({
    name: "武蔵野線",
    reading: "むさしのせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.fuchuhonmachi),
        new StopStation(STATION_IDS.jr_east.kitafuchu),
        new StopStation(STATION_IDS.jr_east.nishikokubunji),
        new StopStation(STATION_IDS.jr_east.shinkohira),
        new StopStation(STATION_IDS.jr_east.shinakitsu),
        new StopStation(STATION_IDS.jr_east.higashi_tokorozawa),
        new StopStation(STATION_IDS.jr_east.shinza),
        new StopStation(STATION_IDS.jr_east.kita_asaka),
        new StopStation(STATION_IDS.jr_east.nishi_urawa),
        new StopStation(STATION_IDS.jr_east.musashi_urawa),
        new StopStation(STATION_IDS.jr_east.higashi_urawa),
        new StopStation(STATION_IDS.jr_east.higashi_kawaguchi),
        new StopStation(STATION_IDS.jr_east.minami_koshigaya),
        new StopStation(STATION_IDS.jr_east.koshigaya_laketown),
        new StopStation(STATION_IDS.jr_east.yoshikawa),
        new StopStation(STATION_IDS.jr_east.yoshikawa_minami),
        new StopStation(STATION_IDS.jr_east.shin_sango),
        new StopStation(STATION_IDS.jr_east.sango),
        new StopStation(STATION_IDS.jr_east.minami_nagareyama),
        new StopStation(STATION_IDS.jr_east.shin_matsudo),
        new StopStation(STATION_IDS.jr_east.shin_yahashira),
        new StopStation(STATION_IDS.jr_east.higashi_matsudo),
        new StopStation(STATION_IDS.jr_east.ichikawa_ono),
        new StopStation(STATION_IDS.jr_east.funabashi_houden),
        new StopStation(STATION_IDS.jr_east.nishi_funabashi),
        new StopStation(STATION_IDS.jr_east.minami_funabashi),
        new StopStation(STATION_IDS.jr_east.shin_narashino),
        new StopStation(STATION_IDS.jr_east.makuhari_toyosuna),
        new StopStation(STATION_IDS.jr_east.kaihin_makuhari),
        new StopStation(STATION_IDS.jr_east.ichikawa_shiohama),
        new StopStation(STATION_IDS.jr_east.shin_urayasu),
        new StopStation(STATION_IDS.jr_east.maihama),
        new StopStation(STATION_IDS.jr_east.kasai_rinkai_kouen),
        new StopStation(STATION_IDS.jr_east.shiomi),
        new StopStation(STATION_IDS.jr_east.ecchujima),
        new StopStation(STATION_IDS.jr_east.hacchobori),
        new StopStation(STATION_IDS.jr_east.tokyo),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.keiyou]: new TrainLine({
    name: "京葉線",
    reading: "けいようせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.hacchobori),
        new StopStation(STATION_IDS.jr_east.ecchujima),
        new StopStation(STATION_IDS.jr_east.shiomi),
        new StopStation(STATION_IDS.jr_east.shin_kiba),
        new StopStation(STATION_IDS.jr_east.kasai_rinkai_kouen),
        new StopStation(STATION_IDS.jr_east.maihama),
        new StopStation(STATION_IDS.jr_east.shin_urayasu),
        new StopStation(STATION_IDS.jr_east.ichikawa_shiohama),
        new StopStation(STATION_IDS.jr_east.futamata_shinmachi),
        new StopStation(STATION_IDS.jr_east.minami_funabashi),
        new StopStation(STATION_IDS.jr_east.kaihin_makuhari),
        new StopStation(STATION_IDS.jr_east.shin_narashino),
        new StopStation(STATION_IDS.jr_east.makuhari_toyosuna),
        new StopStation(STATION_IDS.jr_east.kaihin_makuhari),
        new StopStation(STATION_IDS.jr_east.kemigawahama),
        new StopStation(STATION_IDS.jr_east.inage_kaigan),
        new StopStation(STATION_IDS.jr_east.chiba_minato),
        new StopStation(STATION_IDS.jr_east.soga),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.nanbu]: new TrainLine({
    name: "南武線",
    reading: "なんぶせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.kawasaki),
        new StopStation(STATION_IDS.jr_east.shitte),
        new StopStation(STATION_IDS.jr_east.yakou),
        new StopStation(STATION_IDS.jr_east.kashimada),
        new StopStation(STATION_IDS.jr_east.hirama),
        new StopStation(STATION_IDS.jr_east.mukougawara),
        new StopStation(STATION_IDS.jr_east.musashi_kosugi),
        new StopStation(STATION_IDS.jr_east.musashinakahara),
        new StopStation(STATION_IDS.jr_east.musashishinjou),
        new StopStation(STATION_IDS.jr_east.musashimizonokuchi),
        new StopStation(STATION_IDS.jr_east.tsudayama),
        new StopStation(STATION_IDS.jr_east.kuji),
        new StopStation(STATION_IDS.jr_east.syukugawara),
        new StopStation(STATION_IDS.jr_east.noborito),
        new StopStation(STATION_IDS.jr_east.nakanojima),
        new StopStation(STATION_IDS.jr_east.inadatsutsumi),
        new StopStation(STATION_IDS.jr_east.yanoguchi),
        new StopStation(STATION_IDS.jr_east.inaginaganuma),
        new StopStation(STATION_IDS.jr_east.minamitama),
        new StopStation(STATION_IDS.jr_east.fuchuhonmachi),
        new StopStation(STATION_IDS.jr_east.bubaigawara),
        new StopStation(STATION_IDS.jr_east.nishifu),
        new StopStation(STATION_IDS.jr_east.yaho),
        new StopStation(STATION_IDS.jr_east.yakawa),
        new StopStation(STATION_IDS.jr_east.nishikunitachi),
        new StopStation(STATION_IDS.jr_east.tachikawa),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.nanbu_shisen]: new TrainLine({
    name: "南武線(支線)",
    reading: "なんぶせん(しせん)",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.hamakawasaki),
        new StopStation(STATION_IDS.jr_east.odasakae),
        new StopStation(STATION_IDS.jr_east.kawasaki_shinmachi),
        new StopStation(STATION_IDS.keikyu.hacchonawate),
        new StopStation(STATION_IDS.jr_east.shitte),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.tsurumi]: new TrainLine({
    name: "鶴見線",
    reading: "つるみせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tsurumi),
        new StopStation(STATION_IDS.jr_east.kokudou),
        new StopStation(STATION_IDS.jr_east.tsurumi_ono),
        new StopStation(STATION_IDS.jr_east.bentenbashi),
        new StopStation(STATION_IDS.jr_east.asano),
        new StopStation(STATION_IDS.jr_east.anzen),
        new StopStation(STATION_IDS.jr_east.musashi_shiraishi),
        new StopStation(STATION_IDS.jr_east.shouwa),
        new StopStation(STATION_IDS.jr_east.hamakawasaki),
        new StopStation(STATION_IDS.jr_east.ougimachi),
        new StopStation(STATION_IDS.jr_east.shin_shibaura),
        new StopStation(STATION_IDS.jr_east.umi_shibaura),
        new StopStation(STATION_IDS.jr_east.okawa),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.itsukaichi]: new TrainLine({
    name: "五日市線",
    reading: "いつかいちせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.haijima),
        new StopStation(STATION_IDS.jr_east.kumagawa),
        new StopStation(STATION_IDS.jr_east.higashi_akiru),
        new StopStation(STATION_IDS.jr_east.akigawa),
        new StopStation(STATION_IDS.jr_east.musashi_hikida),
        new StopStation(STATION_IDS.jr_east.musashi_masuko),
        new StopStation(STATION_IDS.jr_east.musashi_itsukaichi),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.nikkou]: new TrainLine({
    name: "日光線",
    reading: "にっこうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.utsunomiya),
        new StopStation(STATION_IDS.jr_east.tsuruta),
        new StopStation(STATION_IDS.jr_east.tsuruta),
        new StopStation(STATION_IDS.jr_east.kanuma),
        new StopStation(STATION_IDS.jr_east.fubasami),
        new StopStation(STATION_IDS.jr_east.shimotsuke_oosawa),
        new StopStation(STATION_IDS.jr_east.imaichi),
        new StopStation(STATION_IDS.jr_east.nikkou),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.jouetsu]: new TrainLine({
    name: "上越線",
    reading: "じょうえつせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.takasaki),
        new StopStation(STATION_IDS.jr_east.takasakitonyamachi),
        new StopStation(STATION_IDS.jr_east.ino),
        new StopStation(STATION_IDS.jr_east.shin_maebashi),
        new StopStation(STATION_IDS.jr_east.gunmasouja),
        new StopStation(STATION_IDS.jr_east.yagihara),
        new StopStation(STATION_IDS.jr_east.shibukawa),
        new StopStation(STATION_IDS.jr_east.shikishima),
        new StopStation(STATION_IDS.jr_east.tsukuda),
        new StopStation(STATION_IDS.jr_east.iwamoto),
        new StopStation(STATION_IDS.jr_east.numata),
        new StopStation(STATION_IDS.jr_east.gokan),
        new StopStation(STATION_IDS.jr_east.kamimoku),
        new StopStation(STATION_IDS.jr_east.minakami),
        new StopStation(STATION_IDS.jr_east.yubiso),
        new StopStation(STATION_IDS.jr_east.doai),
        new StopStation(STATION_IDS.jr_east.tsuchitaru),
        new StopStation(STATION_IDS.jr_east.echigo_nakazato),
        new StopStation(STATION_IDS.jr_east.iwappara_skijoumae),
        new StopStation(STATION_IDS.jr_east.echigo_yuzawa),
        new StopStation(STATION_IDS.jr_east.ishiuchi),
        new StopStation(STATION_IDS.jr_east.oosawa),
        new StopStation(STATION_IDS.jr_east.jouetsu_kokusai_skijoumae),
        new StopStation(STATION_IDS.jr_east.shiozawa),
        new StopStation(STATION_IDS.jr_east.muikamachi),
        new StopStation(STATION_IDS.jr_east.itsukamachi),
        new StopStation(STATION_IDS.jr_east.urasa),
        new StopStation(STATION_IDS.jr_east.yairo),
        new StopStation(STATION_IDS.jr_east.koide),
        new StopStation(STATION_IDS.jr_east.echigo_horinouchi),
        new StopStation(STATION_IDS.jr_east.kita_horinouchi),
        new StopStation(STATION_IDS.jr_east.echigo_kawaguchi),
        new StopStation(STATION_IDS.jr_east.odiya),
        new StopStation(STATION_IDS.jr_east.echigo_takiya),
        new StopStation(STATION_IDS.jr_east.miyauchi),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.ohito]: new TrainLine({
    name: "大糸線(JR東日本)",
    reading: "おおいとせん(じぇいあーるひがしにほん)",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.matsumoto),
        new StopStation(STATION_IDS.jr_east.kita_matsumoto),
        new StopStation(STATION_IDS.jr_east.shimauchi),
        new StopStation(STATION_IDS.jr_east.shima_takamatsu),
        new StopStation(STATION_IDS.jr_east.azusabashi),
        new StopStation(STATION_IDS.jr_east.hitoichiba),
        new StopStation(STATION_IDS.jr_east.nakagaya),
        new StopStation(STATION_IDS.jr_east.minami_toyoshina),
        new StopStation(STATION_IDS.jr_east.toyoshina),
        new StopStation(STATION_IDS.jr_east.hakuyachou),
        new StopStation(STATION_IDS.jr_east.hotaka),
        new StopStation(STATION_IDS.jr_east.ariake),
        new StopStation(STATION_IDS.jr_east.azumi_oiwake),
        new StopStation(STATION_IDS.jr_east.hosono),
        new StopStation(STATION_IDS.jr_east.kita_hosono),
        new StopStation(STATION_IDS.jr_east.shinano_matsukawa),
        new StopStation(STATION_IDS.jr_east.azumi_kutsukake),
        new StopStation(STATION_IDS.jr_east.shinano_tokiwa),
        new StopStation(STATION_IDS.jr_east.minami_ohmachi),
        new StopStation(STATION_IDS.jr_east.shinano_ohmachi),
        new StopStation(STATION_IDS.jr_east.kita_ohmachi),
        new StopStation(STATION_IDS.jr_east.shinano_kizaki),
        new StopStation(STATION_IDS.jr_east.inao),
        new StopStation(STATION_IDS.jr_east.uminokuchi),
        new StopStation(STATION_IDS.jr_east.yanaba),
        new StopStation(STATION_IDS.jr_east.minami_kamishiro),
        new StopStation(STATION_IDS.jr_east.kamishiro),
        new StopStation(STATION_IDS.jr_east.iimori),
        new StopStation(STATION_IDS.jr_east.hakuba),
        new StopStation(STATION_IDS.jr_east.shinano_moriue),
        new StopStation(STATION_IDS.jr_east.hakuba_ohike),
        new StopStation(STATION_IDS.jr_east.chikuni),
        new StopStation(STATION_IDS.jr_east.minami_otari),
      ]),
    ],
  }),

  // #region 千葉
  [LINE_IDS.jr_east.sotobou]: new TrainLine({
    name: "外房線",
    reading: "そとぼうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.chiba),
        new StopStation(STATION_IDS.jr_east.hon_chiba),
        new StopStation(STATION_IDS.jr_east.soga),
        new StopStation(STATION_IDS.jr_east.kamatori),
        new StopStation(STATION_IDS.jr_east.honda),
        new StopStation(STATION_IDS.jr_east.toke),
        new StopStation(STATION_IDS.jr_east.oami),
        new StopStation(STATION_IDS.jr_east.nagata),
        new StopStation(STATION_IDS.jr_east.honnou),
        new StopStation(STATION_IDS.jr_east.shin_mobara),
        new StopStation(STATION_IDS.jr_east.mobara),
        new StopStation(STATION_IDS.jr_east.yatsumi),
        new StopStation(STATION_IDS.jr_east.kazusa_ichinomiya),
        new StopStation(STATION_IDS.jr_east.torami),
        new StopStation(STATION_IDS.jr_east.taitou),
        new StopStation(STATION_IDS.jr_east.choujamachi),
        new StopStation(STATION_IDS.jr_east.mikado),
        new StopStation(STATION_IDS.jr_east.ohara),
        new StopStation(STATION_IDS.jr_east.namihana),
        new StopStation(STATION_IDS.jr_east.onjuku),
        new StopStation(STATION_IDS.jr_east.katsuura),
        new StopStation(STATION_IDS.jr_east.ubara),
        new StopStation(STATION_IDS.jr_east.kazusa_okitsu),
        new StopStation(STATION_IDS.jr_east.namegawa_island),
        new StopStation(STATION_IDS.jr_east.awa_kominato),
        new StopStation(STATION_IDS.jr_east.awa_amatsu),
        new StopStation(STATION_IDS.jr_east.awa_kamogawa),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.uchibou]: new TrainLine({
    name: "内房線",
    reading: "うちぼうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.soga),
        new StopStation(STATION_IDS.jr_east.hamano),
        new StopStation(STATION_IDS.jr_east.yawatajuku),
        new StopStation(STATION_IDS.jr_east.goi),
        new StopStation(STATION_IDS.jr_east.anegasaki),
        new StopStation(STATION_IDS.jr_east.nagaura),
        new StopStation(STATION_IDS.jr_east.sodegaura),
        new StopStation(STATION_IDS.jr_east.iwane),
        new StopStation(STATION_IDS.jr_east.kisaradu),
        new StopStation(STATION_IDS.jr_east.kimitsu),
        new StopStation(STATION_IDS.jr_east.aohori),
        new StopStation(STATION_IDS.jr_east.onuki),
        new StopStation(STATION_IDS.jr_east.sanukimachi),
        new StopStation(STATION_IDS.jr_east.kazusa_minato),
        new StopStation(STATION_IDS.jr_east.takeoka),
        new StopStation(STATION_IDS.jr_east.hamakanaya),
        new StopStation(STATION_IDS.jr_east.hota),
        new StopStation(STATION_IDS.jr_east.awa_katsuyama),
        new StopStation(STATION_IDS.jr_east.iwai),
        new StopStation(STATION_IDS.jr_east.tomiura),
        new StopStation(STATION_IDS.jr_east.nakofunakata),
        new StopStation(STATION_IDS.jr_east.kokonoe),
        new StopStation(STATION_IDS.jr_east.chikura),
        new StopStation(STATION_IDS.jr_east.chitose),
        new StopStation(STATION_IDS.jr_east.minamihara),
        new StopStation(STATION_IDS.jr_east.wadaura),
        new StopStation(STATION_IDS.jr_east.emi),
        new StopStation(STATION_IDS.jr_east.futomi),
        new StopStation(STATION_IDS.jr_east.awa_kamogawa),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.tougane]: new TrainLine({
    name: "東金線",
    reading: "とうがねせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.oami),
        new StopStation(STATION_IDS.jr_east.fukutawara),
        new StopStation(STATION_IDS.jr_east.tougane),
        new StopStation(STATION_IDS.jr_east.gumyou),
        new StopStation(STATION_IDS.jr_east.futomi),
        new StopStation(STATION_IDS.jr_east.narutou),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.kururi]: new TrainLine({
    name: "久留里線",
    reading: "くるりせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.kisaradu),
        new StopStation(STATION_IDS.jr_east.gion),
        new StopStation(STATION_IDS.jr_east.kazusa_kiyokawa),
        new StopStation(STATION_IDS.jr_east.higashi_kiyokawa),
        new StopStation(STATION_IDS.jr_east.yokota),
        new StopStation(STATION_IDS.jr_east.higashi_yokota),
        new StopStation(STATION_IDS.jr_east.makuta),
        new StopStation(STATION_IDS.jr_east.shimogoori),
        new StopStation(STATION_IDS.jr_east.obitsu),
        new StopStation(STATION_IDS.jr_east.tawarada),
        new StopStation(STATION_IDS.jr_east.kururi),
        new StopStation(STATION_IDS.jr_east.hirayama),
        new StopStation(STATION_IDS.jr_east.kazusa_matsuoka),
        new StopStation(STATION_IDS.jr_east.kazusa_kameyama),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.narita1]: new TrainLine({
    name: "成田線[我孫子-成田]",
    reading: "なりたせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.abiko),
        new StopStation(STATION_IDS.jr_east.higashi_abiko),
        new StopStation(STATION_IDS.jr_east.kohoku),
        new StopStation(STATION_IDS.jr_east.araki),
        new StopStation(STATION_IDS.jr_east.fusa),
        new StopStation(STATION_IDS.jr_east.kioroshi),
        new StopStation(STATION_IDS.jr_east.kobayashi),
        new StopStation(STATION_IDS.jr_east.ajiki),
        new StopStation(STATION_IDS.jr_east.shimousa_manzaki),
        new StopStation(STATION_IDS.jr_east.narita),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.narita2]: new TrainLine({
    name: "成田線[佐倉-銚子]",
    reading: "なりたせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.sakura),
        new StopStation(STATION_IDS.jr_east.shisui),
        new StopStation(STATION_IDS.jr_east.narita),
        new StopStation(STATION_IDS.jr_east.kuzumi),
        new StopStation(STATION_IDS.jr_east.namegawa),
        new StopStation(STATION_IDS.jr_east.shimousa_kouzaki),
        new StopStation(STATION_IDS.jr_east.oto),
        new StopStation(STATION_IDS.jr_east.sawara),
        new StopStation(STATION_IDS.jr_east.katori),
        new StopStation(STATION_IDS.jr_east.suigou),
        new StopStation(STATION_IDS.jr_east.omigawa),
        new StopStation(STATION_IDS.jr_east.sasagawa),
        new StopStation(STATION_IDS.jr_east.shimousa_tachibana),
        new StopStation(STATION_IDS.jr_east.shimousa_toyohasato),
        new StopStation(STATION_IDS.jr_east.shishiba),
        new StopStation(STATION_IDS.jr_east.matsugishi),
        new StopStation(STATION_IDS.jr_east.choushi),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.narita3]: new TrainLine({
    name: "成田線[成田-成田空港]",
    reading: "なりたせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.narita),
        new StopStation(STATION_IDS.keisei.kuko_daini_bill),
        new StopStation(STATION_IDS.keisei.narita_kuko),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.kashima]: new TrainLine({
    name: "鹿島線",
    reading: "かしません",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.katori),
        new StopStation(STATION_IDS.jr_east.junikyou),
        new StopStation(STATION_IDS.jr_east.itako),
        new StopStation(STATION_IDS.jr_east.nobukata),
        new StopStation(STATION_IDS.jr_east.kashima_jingu),
        new StopStation(STATION_IDS.jr_east.kashima_soccer_stadium),
      ]),
    ],
  }),
  // #endregion
  [LINE_IDS.jr_east.jouban]: new TrainLine({
    name: "常磐線",
    reading: "じょうばんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [RAPID],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.shinagawa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.shinbashi, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tokyo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.ueno, [RAPID]),
        new StopStation(STATION_IDS.jr_east.nippori, [RAPID]),
        new StopStation(STATION_IDS.jr_east.mikawashima, [RAPID]),
        new StopStation(STATION_IDS.jr_east.minami_senju, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kita_senju, [RAPID]),
        new StopStation(STATION_IDS.jr_east.ayase),
        new StopStation(STATION_IDS.jr_east.kameari),
        new StopStation(STATION_IDS.jr_east.kanamachi),
        new StopStation(STATION_IDS.jr_east.matsudo, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kita_matsudo),
        new StopStation(STATION_IDS.jr_east.bakurocho),
        new StopStation(STATION_IDS.jr_east.shin_matsudo),
        new StopStation(STATION_IDS.jr_east.kita_kogane),
        new StopStation(STATION_IDS.jr_east.minami_kashiwa),
        new StopStation(STATION_IDS.jr_east.kashiwa, [RAPID]),
        new StopStation(STATION_IDS.jr_east.kita_kashiwa),
        new StopStation(STATION_IDS.jr_east.abiko, [RAPID]),
        new StopStation(STATION_IDS.jr_east.tennodai, [RAPID]),
        new StopStation(STATION_IDS.jr_east.toride, [RAPID]),
        new StopStation(STATION_IDS.jr_east.fujishiro),
        new StopStation(STATION_IDS.jr_east.ryugasakishi),
        new StopStation(STATION_IDS.jr_east.ushiku),
        new StopStation(STATION_IDS.jr_east.hitachino_ushiku),
        new StopStation(STATION_IDS.jr_east.arakawaoki),
        new StopStation(STATION_IDS.jr_east.tuchiura),
        new StopStation(STATION_IDS.jr_east.kandachi),
        new StopStation(STATION_IDS.jr_east.takahama),
        new StopStation(STATION_IDS.jr_east.ishioka),
        new StopStation(STATION_IDS.jr_east.hadori),
        new StopStation(STATION_IDS.jr_east.iwama),
        new StopStation(STATION_IDS.jr_east.tomobe),
        new StopStation(STATION_IDS.jr_east.uchihara),
        new StopStation(STATION_IDS.jr_east.akatsuka),
        new StopStation(STATION_IDS.jr_east.kairakuen),
        new StopStation(STATION_IDS.jr_east.mito),
        new StopStation(STATION_IDS.jr_east.katsuta),
        new StopStation(STATION_IDS.jr_east.sawa),
        new StopStation(STATION_IDS.jr_east.toukai),
        new StopStation(STATION_IDS.jr_east.omika),
        new StopStation(STATION_IDS.jr_east.hitachi_taga),
        new StopStation(STATION_IDS.jr_east.hitachi),
        new StopStation(STATION_IDS.jr_east.ogitsu),
        new StopStation(STATION_IDS.jr_east.juo),
        new StopStation(STATION_IDS.jr_east.takahagi),
        new StopStation(STATION_IDS.jr_east.minami_nakazato),
        new StopStation(STATION_IDS.jr_east.isohara),
        new StopStation(STATION_IDS.jr_east.otsuko),
        new StopStation(STATION_IDS.jr_east.nakoso),
        new StopStation(STATION_IDS.jr_east.duplicate.fukushima.ueda),
        new StopStation(STATION_IDS.jr_east.izumi),
        new StopStation(STATION_IDS.jr_east.yumoto),
        new StopStation(STATION_IDS.jr_east.uchisato),
        new StopStation(STATION_IDS.jr_east.iwaki),
        new StopStation(STATION_IDS.jr_east.kusano),
        new StopStation(STATION_IDS.jr_east.yotsukura),
        new StopStation(STATION_IDS.jr_east.kunohama),
        new StopStation(STATION_IDS.jr_east.suetsugi),
        new StopStation(STATION_IDS.jr_east.hirono),
        new StopStation(STATION_IDS.jr_east.j_village),
        new StopStation(STATION_IDS.jr_east.kido),
        new StopStation(STATION_IDS.jr_east.tatsuta),
        new StopStation(STATION_IDS.jr_east.tomioka),
        new StopStation(STATION_IDS.jr_east.yorunomori),
        new StopStation(STATION_IDS.jr_east.ohno),
        new StopStation(STATION_IDS.jr_east.futaba),
        new StopStation(STATION_IDS.jr_east.namie),
        new StopStation(STATION_IDS.jr_east.momouchi),
        new StopStation(STATION_IDS.jr_east.odaka),
        new StopStation(STATION_IDS.jr_east.iwaki_ota),
        new StopStation(STATION_IDS.jr_east.haranocho),
        new StopStation(STATION_IDS.jr_east.kashima),
        new StopStation(STATION_IDS.jr_east.nittaki),
        new StopStation(STATION_IDS.jr_east.soma),
        new StopStation(STATION_IDS.jr_east.komagamine),
        new StopStation(STATION_IDS.jr_east.shinchi),
        new StopStation(STATION_IDS.jr_east.sakamoto),
        new StopStation(STATION_IDS.jr_east.yamashita),
        new StopStation(STATION_IDS.jr_east.hamayoshida),
        new StopStation(STATION_IDS.jr_east.watari),
        new StopStation(STATION_IDS.jr_east.okuma),
        new StopStation(STATION_IDS.jr_east.iwanuma),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.ryoumou]: new TrainLine({
    name: "両毛線",
    reading: "りょうもうせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.shinmaebashi),
        new StopStation(STATION_IDS.jr_east.maebashi),
        new StopStation(STATION_IDS.jr_east.maebashi_oshima),
        new StopStation(STATION_IDS.jr_east.komagata),
        new StopStation(STATION_IDS.jr_east.isezaki),
        new StopStation(STATION_IDS.jr_east.kunisada),
        new StopStation(STATION_IDS.jr_east.iwayado),
        new StopStation(STATION_IDS.jr_east.kiryu),
        new StopStation(STATION_IDS.jr_east.omata),
        new StopStation(STATION_IDS.jr_east.yamamae),
        new StopStation(STATION_IDS.jr_east.ashikaga),
        new StopStation(STATION_IDS.jr_east.ashikaga_flower_park),
        new StopStation(STATION_IDS.jr_east.tomita),
        new StopStation(STATION_IDS.jr_east.sano),
        new StopStation(STATION_IDS.jr_east.iwahune),
        new StopStation(STATION_IDS.jr_east.ohirashita),
        new StopStation(STATION_IDS.jr_east.tochigi),
        new StopStation(STATION_IDS.jr_east.omoigawa),
        new StopStation(STATION_IDS.jr_east.oyama),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.mito]: new TrainLine({
    name: "水戸線",
    reading: "みとせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.oyama),
        new StopStation(STATION_IDS.jr_east.odabayashi),
        new StopStation(STATION_IDS.jr_east.yuki),
        new StopStation(STATION_IDS.jr_east.higashi_yuki),
        new StopStation(STATION_IDS.jr_east.kawashima),
        new StopStation(STATION_IDS.jr_east.tamado),
        new StopStation(STATION_IDS.jr_east.shimodate),
        new StopStation(STATION_IDS.jr_east.niibari),
        new StopStation(STATION_IDS.jr_east.yamato),
        new StopStation(STATION_IDS.jr_east.iwase),
        new StopStation(STATION_IDS.jr_east.haguro),
        new StopStation(STATION_IDS.jr_east.fukuhara),
        new StopStation(STATION_IDS.jr_east.inada),
        new StopStation(STATION_IDS.jr_east.kasama),
        new StopStation(STATION_IDS.jr_east.shishido),
        new StopStation(STATION_IDS.jr_east.tomobe),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.touhoku_honsen]: new TrainLine({
    name: "東北本線",
    reading: "とうほくほんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.kuroiso),
        new StopStation(STATION_IDS.jr_east.takaku),
        new StopStation(STATION_IDS.jr_east.kurotawara),
        new StopStation(STATION_IDS.jr_east.toyohara),
        new StopStation(STATION_IDS.jr_east.shirasaka),
        new StopStation(STATION_IDS.jr_east.shin_shirakawa),
        new StopStation(STATION_IDS.jr_east.shirakawa),
        new StopStation(STATION_IDS.jr_east.kutano),
        new StopStation(STATION_IDS.jr_east.izumizaki),
        new StopStation(STATION_IDS.jr_east.yabuki),
        new StopStation(STATION_IDS.jr_east.kagamiishi),
        new StopStation(STATION_IDS.jr_east.sukagawa),
        new StopStation(STATION_IDS.jr_east.asakanagamori),
        new StopStation(STATION_IDS.jr_east.kooriyama),
        new StopStation(STATION_IDS.jr_east.hiwada),
        new StopStation(STATION_IDS.jr_east.gohyakugawa),
        new StopStation(STATION_IDS.jr_east.motomiya),
        new StopStation(STATION_IDS.jr_east.sugita),
        new StopStation(STATION_IDS.jr_east.nihonmatsu),
        new StopStation(STATION_IDS.jr_east.adachi),
        new StopStation(STATION_IDS.jr_east.matsukawa),
        new StopStation(STATION_IDS.jr_east.kanayagawa),
        new StopStation(STATION_IDS.jr_east.minami_fukushima),
        new StopStation(STATION_IDS.jr_east.fukushima),
        new StopStation(STATION_IDS.jr_east.higashi_fukushima),
        new StopStation(STATION_IDS.jr_east.date),
        new StopStation(STATION_IDS.jr_east.kori),
        new StopStation(STATION_IDS.jr_east.fujita),
        new StopStation(STATION_IDS.jr_east.kaida),
        new StopStation(STATION_IDS.jr_east.kosugou),
        new StopStation(STATION_IDS.jr_east.shiraishi),
        new StopStation(STATION_IDS.jr_east.higashi_shiraishi),
        new StopStation(STATION_IDS.jr_east.kita_shirakawa),
        new StopStation(STATION_IDS.jr_east.ohgawara),
        new StopStation(STATION_IDS.jr_east.funaoka),
        new StopStation(STATION_IDS.jr_east.tsukinoki),
        new StopStation(STATION_IDS.jr_east.tatekoshi),
        new StopStation(STATION_IDS.jr_east.natori),
        new StopStation(STATION_IDS.jr_east.minami_sendai),
        new StopStation(STATION_IDS.jr_east.taishidou),
        new StopStation(STATION_IDS.jr_east.nagamachi),
        new StopStation(STATION_IDS.jr_east.sendai),
        new StopStation(STATION_IDS.jr_east.higashi_sendai),
        new StopStation(STATION_IDS.jr_east.iwakiri),
        new StopStation(STATION_IDS.jr_east.rikuzensannou),
        new StopStation(STATION_IDS.jr_east.kokufutagajou),
        new StopStation(STATION_IDS.jr_east.shiogama),
        new StopStation(STATION_IDS.jr_east.matsushima),
        new StopStation(STATION_IDS.jr_east.atago),
        new StopStation(STATION_IDS.jr_east.shinainuma),
        new StopStation(STATION_IDS.jr_east.kashimadai),
        new StopStation(STATION_IDS.jr_east.matsuyamamachi),
        new StopStation(STATION_IDS.jr_east.kogota),
        new StopStation(STATION_IDS.jr_east.tajiri),
        new StopStation(STATION_IDS.jr_east.semine),
        new StopStation(STATION_IDS.jr_east.umegasawa),
        new StopStation(STATION_IDS.jr_east.nitta),
        new StopStation(STATION_IDS.jr_east.ishikoshi),
        new StopStation(STATION_IDS.jr_east.aburajima),
        new StopStation(STATION_IDS.jr_east.hanaizumi),
        new StopStation(STATION_IDS.jr_east.shimizuhara),
        new StopStation(STATION_IDS.jr_east.arikabe),
        new StopStation(STATION_IDS.jr_east.ichinoseki),
        new StopStation(STATION_IDS.jr_east.yamanome),
        new StopStation(STATION_IDS.jr_east.hiraizumi),
        new StopStation(STATION_IDS.jr_east.maezawa),
        new StopStation(STATION_IDS.jr_east.rikuchuorii),
        new StopStation(STATION_IDS.jr_east.mizusawa),
        new StopStation(STATION_IDS.jr_east.kanegasaki),
        new StopStation(STATION_IDS.jr_east.rokuhara),
        new StopStation(STATION_IDS.jr_east.kitakami),
        new StopStation(STATION_IDS.jr_east.murasakino),
        new StopStation(STATION_IDS.jr_east.hanamaki),
        new StopStation(STATION_IDS.jr_east.hanamaki_kuko),
        new StopStation(STATION_IDS.jr_east.ishidoriya),
        new StopStation(STATION_IDS.jr_east.hidume),
        new StopStation(STATION_IDS.jr_east.shiwa_chuou),
        new StopStation(STATION_IDS.jr_east.furudate),
        new StopStation(STATION_IDS.jr_east.yahaba),
        new StopStation(STATION_IDS.jr_east.iwate_iioka),
        new StopStation(STATION_IDS.jr_east.senbokumachi),
        new StopStation(STATION_IDS.jr_east.morioka),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.tokaido]: new TrainLine({
    name: "東海道新幹線",
    reading: "とうかいどうしんかんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [
      new ServiceType("こだま", "extra1"),
      new ServiceType("ひかり", "extra2"),
      new ServiceType("のぞみ", "extra3"),
    ],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, [
          "extra1",
          "extra2",
          "extra3",
        ]),
        new StopStation(STATION_IDS.jr_east.shinagawa, [
          "extra1",
          "extra2",
          "extra3",
        ]),
        new StopStation(STATION_IDS.jr_east.shin_yokohama, [
          "extra1",
          "extra2",
          "extra3",
        ]),
        new StopStation(STATION_IDS.jr_east.odawara, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_east.atami, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.mishima, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.shinfuji, ["extra1"]),
        new StopStation(STATION_IDS.jr_toukai.shizuoka, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.kakegawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_toukai.hamamatsu, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.toyohashi, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.mikawa_anjou, ["extra1"]),
        new StopStation(STATION_IDS.jr_toukai.nagoya, [
          "extra1",
          "extra2",
          "extra3",
        ]),
        new StopStation(STATION_IDS.jr_toukai.gifuhashima, [
          "extra1",
          "extra2",
        ]),
        new StopStation(STATION_IDS.jr_toukai.maibara, ["extra1", "extra2"]),
        new StopStation(STATION_IDS.jr_toukai.kyoto, [
          "extra1",
          "extra2",
          "extra3",
        ]),
        new StopStation(STATION_IDS.jr_toukai.shinosaka, [
          "extra1",
          "extra2",
          "extra3",
        ]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.jouetsu]: new TrainLine({
    name: "上越新幹線",
    reading: "じょうえつしんかんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.ueno),
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.kumagaya),
        new StopStation(STATION_IDS.jr_east.honjo_waseda),
        new StopStation(STATION_IDS.jr_east.takasaki),
        new StopStation(STATION_IDS.jr_east.joumoukougen),
        new StopStation(STATION_IDS.jr_east.echigo_yuzawa),
        new StopStation(STATION_IDS.jr_east.ueno),
        new StopStation(STATION_IDS.jr_east.gala_yuzawa),
        new StopStation(STATION_IDS.jr_east.urasa),
        new StopStation(STATION_IDS.jr_east.nagaoka),
        new StopStation(STATION_IDS.jr_east.tsubame_sanjo),
        new StopStation(STATION_IDS.jr_east.niigata),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.touhoku]: new TrainLine({
    name: "東北新幹線",
    reading: "とうほくしんかんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [new Extra1("はやぶさ")],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.ueno, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.omiya, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.oyama),
        new StopStation(STATION_IDS.jr_east.utsunomiya),
        new StopStation(STATION_IDS.jr_east.nasu_shiobara),
        new StopStation(STATION_IDS.jr_east.shin_shirakawa),
        new StopStation(STATION_IDS.jr_east.kooriyama),
        new StopStation(STATION_IDS.jr_east.fukushima),
        new StopStation(STATION_IDS.jr_east.shiroishi_zao),
        new StopStation(STATION_IDS.jr_east.sendai, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.furukawa, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.kurikoma_kogen, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.ichinoseki, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.mizusawaesashi, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.kitakami, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.shin_hanamaki, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.morioka, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.iwate_numakunai, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.ninohe, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.hachinohe, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.shichinohe_towada, [EXTRA1]),
        new StopStation(STATION_IDS.jr_east.shin_aomori, [EXTRA1]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.yamagata]: new TrainLine({
    name: "山形新幹線",
    reading: "やまがたしんかんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo),
        new StopStation(STATION_IDS.jr_east.ueno),
        new StopStation(STATION_IDS.jr_east.omiya),
        new StopStation(STATION_IDS.jr_east.utsunomiya),
        new StopStation(STATION_IDS.jr_east.kooriyama),
        new StopStation(STATION_IDS.jr_east.fukushima),
        new StopStation(STATION_IDS.jr_east.yonezawa),
        new StopStation(STATION_IDS.jr_east.takahata),
        new StopStation(STATION_IDS.jr_east.akayu),
        new StopStation(STATION_IDS.jr_east.kaminoyama_onsen),
        new StopStation(STATION_IDS.jr_east.yamagata),
        new StopStation(STATION_IDS.jr_east.tendo),
        new StopStation(STATION_IDS.jr_east.sakuranbo_higashine),
        new StopStation(STATION_IDS.jr_east.murayama),
        new StopStation(STATION_IDS.jr_east.oishida),
        new StopStation(STATION_IDS.jr_east.shinjo),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.akita]: new TrainLine({
    name: "秋田新幹線",
    reading: "あきたしんかんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [new ServiceType("はやぶさ", "extra1")],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ueno, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.omiya, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.sendai, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.furukawa, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kurikoma_kogen, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.ichinoseki, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.mizusawaesashi, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.kitakami, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.shin_hanamaki, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.morioka, ["extra1"]),
        new StopStation(STATION_IDS.jr_east.shizukuishi),
        new StopStation(STATION_IDS.jr_east.tazawako),
        new StopStation(STATION_IDS.jr_east.kakunodate),
        new StopStation(STATION_IDS.jr_east.omagari),
        new StopStation(STATION_IDS.jr_east.akita),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.hokuriku]: new TrainLine({
    name: "北陸新幹線",
    reading: "ほくりくしんかんせん",
    companyId: COMPANIES.jr_east.id,
    serviceTypes: [
      new Extra1("かがやき"),
      new Extra2("はくたか"),
      new Extra3("つるぎ"),
      new Extra4("あさま"),
    ],
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.tokyo, [EXTRA1, EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.ueno, [EXTRA1, EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.omiya, [EXTRA1, EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.kumagaya, [EXTRA4]),
        new StopStation(STATION_IDS.jr_east.honjo_waseda, [EXTRA4]),
        new StopStation(STATION_IDS.jr_east.takasaki, [EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.annaka_haruna, [EXTRA4]),
        new StopStation(STATION_IDS.jr_east.karuizawa, [EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.duplicate.nagano.ueda, [
          EXTRA2,
          EXTRA4,
        ]),
        new StopStation(STATION_IDS.jr_east.nagano, [EXTRA1, EXTRA2, EXTRA4]),
        new StopStation(STATION_IDS.jr_east.iiyama, [EXTRA2]), //飯山
        new StopStation(STATION_IDS.jr_east.joetsu_myoko, [EXTRA2]), //上越妙高
        new StopStation(STATION_IDS.jr_west.itoigawa, [EXTRA2]),
        new StopStation(STATION_IDS.jr_west.kurobe_unaduki_onsen, [EXTRA2]),
        new StopStation(STATION_IDS.jr_west.toyama, [EXTRA1, EXTRA2]),
        new StopStation(STATION_IDS.jr_west.shin_takaoka, [EXTRA2, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.kanazawa, [EXTRA1, EXTRA2, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.komatsu, [EXTRA1, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.kaga_onsen, [EXTRA1, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.awara_onsen, [EXTRA1, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.fukui, [EXTRA1, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.echizen_takefu, [EXTRA1, EXTRA3]),
        new StopStation(STATION_IDS.jr_west.tsuruga, [EXTRA1, EXTRA3]),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinkansen.hokkaido]: new TrainLine({
    name: "北海道新幹線",
    reading: "ほっかいどうしんかんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.shin_aomori),
        new StopStation(STATION_IDS.jr_east.oku_tsugaru_imabetsu),
        new StopStation(STATION_IDS.jr_hokkaidou.kikonai),
        new StopStation(STATION_IDS.jr_hokkaidou.shin_hakodate_hokuto),
      ]),
    ],
  }),
  // #endregion 千葉

  [LINE_IDS.jr_east.shinonoi]: new TrainLine({
    name: "篠ノ井線",
    reading: "しののいせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.shiojiri),
        new StopStation(STATION_IDS.jr_east.hirooka),
        new StopStation(STATION_IDS.jr_east.murai),
        new StopStation(STATION_IDS.jr_east.hirata),
        new StopStation(STATION_IDS.jr_east.minami_matsumoto),
        new StopStation(STATION_IDS.jr_east.matsumoto),
        new StopStation(STATION_IDS.jr_east.tazawa),
        new StopStation(STATION_IDS.jr_east.akashina),
        new StopStation(STATION_IDS.jr_east.nishijou),
        new StopStation(STATION_IDS.jr_east.sakakita),
        new StopStation(STATION_IDS.jr_east.hijirikougen),
        new StopStation(STATION_IDS.jr_east.kamuriki),
        new StopStation(STATION_IDS.jr_east.obasute),
        new StopStation(STATION_IDS.jr_east.inariyama),
        new StopStation(STATION_IDS.jr_east.shinonoi),
      ]),
    ],
  }),
  [LINE_IDS.jr_east.shinetsu_honsen]: new TrainLine({
    name: "信越本線",
    reading: "しんえつほんせん",
    companyId: COMPANIES.jr_east.id,
    sections: [
      new Section([
        new StopStation(STATION_IDS.jr_east.nagaoka),
        new StopStation(STATION_IDS.jr_east.kita_nagaoka),
        new StopStation(STATION_IDS.jr_east.oshikiri),
        new StopStation(STATION_IDS.jr_east.mitsuke),
        new StopStation(STATION_IDS.jr_east.obiori),
        new StopStation(STATION_IDS.jr_east.toukouji),
        new StopStation(STATION_IDS.jr_east.sanjou),
        new StopStation(STATION_IDS.jr_east.honai),
        new StopStation(STATION_IDS.jr_east.kamo),
        new StopStation(STATION_IDS.jr_east.hanyuda),
        new StopStation(STATION_IDS.jr_east.tagami),
        new StopStation(STATION_IDS.jr_east.yashiroda),
        new StopStation(STATION_IDS.jr_east.furutsu),
        new StopStation(STATION_IDS.jr_east.niitsu),
        new StopStation(STATION_IDS.jr_east.satsukino),
        new StopStation(STATION_IDS.jr_east.ogikawa),
        new StopStation(STATION_IDS.jr_east.kameda),
        new StopStation(STATION_IDS.jr_east.echigo_ishiyama),
        new StopStation(STATION_IDS.jr_east.niigata),
      ])
    ]
  })
};
